// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package porkbun

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/porkbun/porkbun/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDomain(ctx *pulumi.Context, args *GetDomainArgs, opts ...pulumi.InvokeOption) (*GetDomainResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetDomainResult
	err = ctx.InvokePackage("porkbun:index/getDomain:getDomain", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDomain.
type GetDomainArgs struct {
	Domain string `pulumi:"domain"`
}

// A collection of values returned by getDomain.
type GetDomainResult struct {
	AutoRenew    bool             `pulumi:"autoRenew"`
	Domain       string           `pulumi:"domain"`
	Labels       []GetDomainLabel `pulumi:"labels"`
	NotLocal     bool             `pulumi:"notLocal"`
	SecurityLock bool             `pulumi:"securityLock"`
	Status       string           `pulumi:"status"`
	Tld          string           `pulumi:"tld"`
	WhoisPrivacy bool             `pulumi:"whoisPrivacy"`
}

func GetDomainOutput(ctx *pulumi.Context, args GetDomainOutputArgs, opts ...pulumi.InvokeOption) GetDomainResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("porkbun:index/getDomain:getDomain", args, GetDomainResultOutput{}, options).(GetDomainResultOutput)
}

// A collection of arguments for invoking getDomain.
type GetDomainOutputArgs struct {
	Domain pulumi.StringInput `pulumi:"domain"`
}

func (GetDomainOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDomainArgs)(nil)).Elem()
}

// A collection of values returned by getDomain.
type GetDomainResultOutput struct{ *pulumi.OutputState }

func (GetDomainResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDomainResult)(nil)).Elem()
}

func (o GetDomainResultOutput) ToGetDomainResultOutput() GetDomainResultOutput {
	return o
}

func (o GetDomainResultOutput) ToGetDomainResultOutputWithContext(ctx context.Context) GetDomainResultOutput {
	return o
}

func (o GetDomainResultOutput) AutoRenew() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDomainResult) bool { return v.AutoRenew }).(pulumi.BoolOutput)
}

func (o GetDomainResultOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v GetDomainResult) string { return v.Domain }).(pulumi.StringOutput)
}

func (o GetDomainResultOutput) Labels() GetDomainLabelArrayOutput {
	return o.ApplyT(func(v GetDomainResult) []GetDomainLabel { return v.Labels }).(GetDomainLabelArrayOutput)
}

func (o GetDomainResultOutput) NotLocal() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDomainResult) bool { return v.NotLocal }).(pulumi.BoolOutput)
}

func (o GetDomainResultOutput) SecurityLock() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDomainResult) bool { return v.SecurityLock }).(pulumi.BoolOutput)
}

func (o GetDomainResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetDomainResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o GetDomainResultOutput) Tld() pulumi.StringOutput {
	return o.ApplyT(func(v GetDomainResult) string { return v.Tld }).(pulumi.StringOutput)
}

func (o GetDomainResultOutput) WhoisPrivacy() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDomainResult) bool { return v.WhoisPrivacy }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDomainResultOutput{})
}
