// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package porkbun

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/porkbun/porkbun/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Nameservers struct {
	pulumi.CustomResourceState

	// The domain name to manage nameservers for. Must be a domain registered with Porkbun.
	Domain pulumi.StringOutput `pulumi:"domain"`
	// A list of name server host names.
	Nameservers pulumi.StringArrayOutput `pulumi:"nameservers"`
}

// NewNameservers registers a new resource with the given unique name, arguments, and options.
func NewNameservers(ctx *pulumi.Context,
	name string, args *NameserversArgs, opts ...pulumi.ResourceOption) (*Nameservers, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Domain == nil {
		return nil, errors.New("invalid value for required argument 'Domain'")
	}
	if args.Nameservers == nil {
		return nil, errors.New("invalid value for required argument 'Nameservers'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Nameservers
	err = ctx.RegisterPackageResource("porkbun:index/nameservers:Nameservers", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNameservers gets an existing Nameservers resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNameservers(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NameserversState, opts ...pulumi.ResourceOption) (*Nameservers, error) {
	var resource Nameservers
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("porkbun:index/nameservers:Nameservers", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Nameservers resources.
type nameserversState struct {
	// The domain name to manage nameservers for. Must be a domain registered with Porkbun.
	Domain *string `pulumi:"domain"`
	// A list of name server host names.
	Nameservers []string `pulumi:"nameservers"`
}

type NameserversState struct {
	// The domain name to manage nameservers for. Must be a domain registered with Porkbun.
	Domain pulumi.StringPtrInput
	// A list of name server host names.
	Nameservers pulumi.StringArrayInput
}

func (NameserversState) ElementType() reflect.Type {
	return reflect.TypeOf((*nameserversState)(nil)).Elem()
}

type nameserversArgs struct {
	// The domain name to manage nameservers for. Must be a domain registered with Porkbun.
	Domain string `pulumi:"domain"`
	// A list of name server host names.
	Nameservers []string `pulumi:"nameservers"`
}

// The set of arguments for constructing a Nameservers resource.
type NameserversArgs struct {
	// The domain name to manage nameservers for. Must be a domain registered with Porkbun.
	Domain pulumi.StringInput
	// A list of name server host names.
	Nameservers pulumi.StringArrayInput
}

func (NameserversArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*nameserversArgs)(nil)).Elem()
}

type NameserversInput interface {
	pulumi.Input

	ToNameserversOutput() NameserversOutput
	ToNameserversOutputWithContext(ctx context.Context) NameserversOutput
}

func (*Nameservers) ElementType() reflect.Type {
	return reflect.TypeOf((**Nameservers)(nil)).Elem()
}

func (i *Nameservers) ToNameserversOutput() NameserversOutput {
	return i.ToNameserversOutputWithContext(context.Background())
}

func (i *Nameservers) ToNameserversOutputWithContext(ctx context.Context) NameserversOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NameserversOutput)
}

type NameserversOutput struct{ *pulumi.OutputState }

func (NameserversOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Nameservers)(nil)).Elem()
}

func (o NameserversOutput) ToNameserversOutput() NameserversOutput {
	return o
}

func (o NameserversOutput) ToNameserversOutputWithContext(ctx context.Context) NameserversOutput {
	return o
}

// The domain name to manage nameservers for. Must be a domain registered with Porkbun.
func (o NameserversOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *Nameservers) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

// A list of name server host names.
func (o NameserversOutput) Nameservers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Nameservers) pulumi.StringArrayOutput { return v.Nameservers }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NameserversInput)(nil)).Elem(), &Nameservers{})
	pulumi.RegisterOutputType(NameserversOutput{})
}
