// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package porkbun

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/porkbun/porkbun/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the porkbun package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// API key for authentication. Can also be set using the `PORKBUN_API_KEY` environment variable.
	ApiKey pulumi.StringPtrOutput `pulumi:"apiKey"`
	// Secret API key for authentication. Can also be set using the `PORKBUN_SECRET_API_KEY` environment variable.
	SecretApiKey pulumi.StringPtrOutput `pulumi:"secretApiKey"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.ApiKey != nil {
		args.ApiKey = pulumi.ToSecret(args.ApiKey).(pulumi.StringPtrInput)
	}
	if args.SecretApiKey != nil {
		args.SecretApiKey = pulumi.ToSecret(args.SecretApiKey).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiKey",
		"secretApiKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Provider
	err = ctx.RegisterPackageResource("pulumi:providers:porkbun", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// API key for authentication. Can also be set using the `PORKBUN_API_KEY` environment variable.
	ApiKey *string `pulumi:"apiKey"`
	// Use IPv4 only for API requests. Defaults to false.
	Ipv4Only *bool `pulumi:"ipv4Only"`
	// Maximum number of retries for API requests. Defaults to 3.
	MaxRetries *float64 `pulumi:"maxRetries"`
	// Secret API key for authentication. Can also be set using the `PORKBUN_SECRET_API_KEY` environment variable.
	SecretApiKey *string `pulumi:"secretApiKey"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// API key for authentication. Can also be set using the `PORKBUN_API_KEY` environment variable.
	ApiKey pulumi.StringPtrInput
	// Use IPv4 only for API requests. Defaults to false.
	Ipv4Only pulumi.BoolPtrInput
	// Maximum number of retries for API requests. Defaults to 3.
	MaxRetries pulumi.Float64PtrInput
	// Secret API key for authentication. Can also be set using the `PORKBUN_SECRET_API_KEY` environment variable.
	SecretApiKey pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

// This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
func (r *Provider) TerraformConfig(ctx *pulumi.Context) (pulumi.MapOutput, error) {
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return pulumi.MapOutput{}, err
	}
	out, err := ctx.CallPackage("pulumi:providers:porkbun/terraformConfig", nil, providerTerraformConfigResultOutput{}, r, ref)
	if err != nil {
		return pulumi.MapOutput{}, err
	}
	return out.(providerTerraformConfigResultOutput).Result(), nil
}

type providerTerraformConfigResult struct {
	Result map[string]interface{} `pulumi:"result"`
}

type providerTerraformConfigResultOutput struct{ *pulumi.OutputState }

func (providerTerraformConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*providerTerraformConfigResult)(nil)).Elem()
}

func (o providerTerraformConfigResultOutput) Result() pulumi.MapOutput {
	return o.ApplyT(func(v providerTerraformConfigResult) map[string]interface{} { return v.Result }).(pulumi.MapOutput)
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// API key for authentication. Can also be set using the `PORKBUN_API_KEY` environment variable.
func (o ProviderOutput) ApiKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ApiKey }).(pulumi.StringPtrOutput)
}

// Secret API key for authentication. Can also be set using the `PORKBUN_SECRET_API_KEY` environment variable.
func (o ProviderOutput) SecretApiKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.SecretApiKey }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
	pulumi.RegisterOutputType(providerTerraformConfigResultOutput{})
}
