// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package porkbun

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/porkbun/porkbun/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type UrlForward struct {
	pulumi.CustomResourceState

	// The domain name for which to configure URL forwarding (e.g., example.com).
	Domain pulumi.StringOutput `pulumi:"domain"`
	// Whether or not to include the URI path in the redirection.
	IncludePath pulumi.BoolOutput `pulumi:"includePath"`
	// Where you'd like to forward the domain to.
	Location pulumi.StringOutput `pulumi:"location"`
	// A subdomain that you would like to add URL forwarding for. Leave this blank to forward the root domain.
	Subdomain pulumi.StringPtrOutput `pulumi:"subdomain"`
	// The type of forward (temporary, permanent).
	Type pulumi.StringOutput `pulumi:"type"`
	// Also forward all subdomains of the domain.
	Wildcard pulumi.BoolOutput `pulumi:"wildcard"`
}

// NewUrlForward registers a new resource with the given unique name, arguments, and options.
func NewUrlForward(ctx *pulumi.Context,
	name string, args *UrlForwardArgs, opts ...pulumi.ResourceOption) (*UrlForward, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Domain == nil {
		return nil, errors.New("invalid value for required argument 'Domain'")
	}
	if args.IncludePath == nil {
		return nil, errors.New("invalid value for required argument 'IncludePath'")
	}
	if args.Location == nil {
		return nil, errors.New("invalid value for required argument 'Location'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	if args.Wildcard == nil {
		return nil, errors.New("invalid value for required argument 'Wildcard'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource UrlForward
	err = ctx.RegisterPackageResource("porkbun:index/urlForward:UrlForward", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUrlForward gets an existing UrlForward resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUrlForward(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UrlForwardState, opts ...pulumi.ResourceOption) (*UrlForward, error) {
	var resource UrlForward
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("porkbun:index/urlForward:UrlForward", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering UrlForward resources.
type urlForwardState struct {
	// The domain name for which to configure URL forwarding (e.g., example.com).
	Domain *string `pulumi:"domain"`
	// Whether or not to include the URI path in the redirection.
	IncludePath *bool `pulumi:"includePath"`
	// Where you'd like to forward the domain to.
	Location *string `pulumi:"location"`
	// A subdomain that you would like to add URL forwarding for. Leave this blank to forward the root domain.
	Subdomain *string `pulumi:"subdomain"`
	// The type of forward (temporary, permanent).
	Type *string `pulumi:"type"`
	// Also forward all subdomains of the domain.
	Wildcard *bool `pulumi:"wildcard"`
}

type UrlForwardState struct {
	// The domain name for which to configure URL forwarding (e.g., example.com).
	Domain pulumi.StringPtrInput
	// Whether or not to include the URI path in the redirection.
	IncludePath pulumi.BoolPtrInput
	// Where you'd like to forward the domain to.
	Location pulumi.StringPtrInput
	// A subdomain that you would like to add URL forwarding for. Leave this blank to forward the root domain.
	Subdomain pulumi.StringPtrInput
	// The type of forward (temporary, permanent).
	Type pulumi.StringPtrInput
	// Also forward all subdomains of the domain.
	Wildcard pulumi.BoolPtrInput
}

func (UrlForwardState) ElementType() reflect.Type {
	return reflect.TypeOf((*urlForwardState)(nil)).Elem()
}

type urlForwardArgs struct {
	// The domain name for which to configure URL forwarding (e.g., example.com).
	Domain string `pulumi:"domain"`
	// Whether or not to include the URI path in the redirection.
	IncludePath bool `pulumi:"includePath"`
	// Where you'd like to forward the domain to.
	Location string `pulumi:"location"`
	// A subdomain that you would like to add URL forwarding for. Leave this blank to forward the root domain.
	Subdomain *string `pulumi:"subdomain"`
	// The type of forward (temporary, permanent).
	Type string `pulumi:"type"`
	// Also forward all subdomains of the domain.
	Wildcard bool `pulumi:"wildcard"`
}

// The set of arguments for constructing a UrlForward resource.
type UrlForwardArgs struct {
	// The domain name for which to configure URL forwarding (e.g., example.com).
	Domain pulumi.StringInput
	// Whether or not to include the URI path in the redirection.
	IncludePath pulumi.BoolInput
	// Where you'd like to forward the domain to.
	Location pulumi.StringInput
	// A subdomain that you would like to add URL forwarding for. Leave this blank to forward the root domain.
	Subdomain pulumi.StringPtrInput
	// The type of forward (temporary, permanent).
	Type pulumi.StringInput
	// Also forward all subdomains of the domain.
	Wildcard pulumi.BoolInput
}

func (UrlForwardArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*urlForwardArgs)(nil)).Elem()
}

type UrlForwardInput interface {
	pulumi.Input

	ToUrlForwardOutput() UrlForwardOutput
	ToUrlForwardOutputWithContext(ctx context.Context) UrlForwardOutput
}

func (*UrlForward) ElementType() reflect.Type {
	return reflect.TypeOf((**UrlForward)(nil)).Elem()
}

func (i *UrlForward) ToUrlForwardOutput() UrlForwardOutput {
	return i.ToUrlForwardOutputWithContext(context.Background())
}

func (i *UrlForward) ToUrlForwardOutputWithContext(ctx context.Context) UrlForwardOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UrlForwardOutput)
}

type UrlForwardOutput struct{ *pulumi.OutputState }

func (UrlForwardOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**UrlForward)(nil)).Elem()
}

func (o UrlForwardOutput) ToUrlForwardOutput() UrlForwardOutput {
	return o
}

func (o UrlForwardOutput) ToUrlForwardOutputWithContext(ctx context.Context) UrlForwardOutput {
	return o
}

// The domain name for which to configure URL forwarding (e.g., example.com).
func (o UrlForwardOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *UrlForward) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

// Whether or not to include the URI path in the redirection.
func (o UrlForwardOutput) IncludePath() pulumi.BoolOutput {
	return o.ApplyT(func(v *UrlForward) pulumi.BoolOutput { return v.IncludePath }).(pulumi.BoolOutput)
}

// Where you'd like to forward the domain to.
func (o UrlForwardOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v *UrlForward) pulumi.StringOutput { return v.Location }).(pulumi.StringOutput)
}

// A subdomain that you would like to add URL forwarding for. Leave this blank to forward the root domain.
func (o UrlForwardOutput) Subdomain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *UrlForward) pulumi.StringPtrOutput { return v.Subdomain }).(pulumi.StringPtrOutput)
}

// The type of forward (temporary, permanent).
func (o UrlForwardOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *UrlForward) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

// Also forward all subdomains of the domain.
func (o UrlForwardOutput) Wildcard() pulumi.BoolOutput {
	return o.ApplyT(func(v *UrlForward) pulumi.BoolOutput { return v.Wildcard }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UrlForwardInput)(nil)).Elem(), &UrlForward{})
	pulumi.RegisterOutputType(UrlForwardOutput{})
}
