encryptionsalt: v1:b2/LH1+YaqU=:v1:3NvGjk46y0U1qIWc:ZZWxBnh68U9rOKthDHruODIio9wbqg==
config:
  kamori:databaseStandbyMode: disabled
  kamori:opaqueServerSetup:
    secure: v1:GfSbHGbH+WthS4uW:X/f1BA8gLNVEc1DpMidNRyA0m0RfzNZlwpL6qMmW7QqjKMveHQUs/nmrS0/g3UpBivRfBqX9S8dukZhCUG5SVRxfbZWfLNOPaTYHgVDFvQ2QpqeFR/7So7NfNt6Ofsdl+QO8hx/P+T7JSIczGva98m1Ou5erXZQrmb2JFNqAib1swVRvET6EEsTrav27IX88TG2bAlQR+S1oUJSXLJ/XVZTCaWUUtRqlWlF4PyQvK+U1D0qlw10QGYe/hvc=
  kamori:refreshRotationKey:
    secure: v1:iEUuZAteP4hHNOcy:cq9z3VN5Mp0cHehWV78XetIk2WPrN79XKB13iJUifW0rxWTVrU5QzHpqM7nkutDsJQFCzeP72P6g8dwl
  kamori:sshKeys: operator-key-main
  kamori:hcloudToken:
    secure: v1:elX98GB5aOYOpMtM:JjD/8PNgPc7Q57HNKIO1K50NOaJapgs/CBc1/2lg6UHK/Qu65/R++m8EHpdbSdMkqgvc11mhItoQA9idv79zD6BMCv5AdKDS+U38Np1gvGc=
  kamori:porkbunApiKey:
    secure: v1:GBMSmkIf0Jn4MQ7D:4W2cc2W79VF0tBKIZ44dRuOlt8yKirhb0nkL9j8lntSNfjRt3JLvkVB4DcP/q2ppSyCFaFCeslgFYFsPkyQa5hVZumNbTD3ELcUhZsQYMn0dG9SM
  kamori:porkbunSecretApiKey:
    secure: v1:g3zTUOx6Q9US5b4n:tBQiL7+KltccJR5Xvr4zoGV8bg+054ogaKXmpsalrQ25k4QGnc6jKSGBAFtOeMWNbAxDSpXvQEDhH4R6VShXIADZ2ebb7lTEDGeg0gAOpZh064va
  kamori:b2RuntimeKeyId:
    secure: v1:HVSMwAkFUAW2lqpg:787sSv6BWEnx0zsfTPC/J10bc+Ft+3MBneTFf3DfI2N6t1BRbTafLsE=
  kamori:b2RuntimeApplicationKey:
    secure: v1:C22JFbp5oIakDuDW:1dm8t62xOAbxGUaNY7+A+Jqc/LXk56bFWwJQ68k0tvFPWpdRdF6qD8URYmGSvN97
  kamori:hetznerObjectAccessKey:
    secure: v1:LiiVXtudS+//Q3h5:XbiyjQ0iK86ncjiVo/y9hrshaHbgHx+hlPTaZZ/hVW6oUUym
  kamori:hetznerObjectSecretKey:
    secure: v1:9vtJBxGj6onC+T0o:9/c+q3LtTbq7thx+0PTcTC/DqFp83m8QvbaEyTN3AOZsdYcT0ZWhrA0oqj2lu/EVkCwUiu+qiV8=
  kamori:databasePassword:
    secure: v1:TWzB+a+gDLJr3VBz:OUppp4fS81OEgcv4Bb2Lq9ThIBRf3y+h+65BdjEteH32UFvMmj6/i1Ac4zXU2pNzGIBo1BcCotPf5KpRcCklAEach5TwU9UW+7yRdPuczso=
  kamori:valkeyPassword:
    secure: v1:BU5kG31IFpVtOcml:IL/54GzliNHxDiyq2nAgYAZ8KJMopxbwyELXjHYg1vtdN0F+JKaTi74BSVQOvrZfOYw36Hy/4krZkddSyvrkYxXEcYANLxojcTohn0Pqj34=
  kamori:postgresCaCertificate: |
    -----BEGIN CERTIFICATE-----
    MIICDzCCAZWgAwIBAgIUZgsNQlVKZpuvtOqA7C4MAZ1+fsIwCgYIKoZIzj0EAwMw
    NTEiMCAGA1UEAwwZS2Ftb3JpIFBvc3RncmVTUUwgUm9vdCBDQTEPMA0GA1UECgwG
    S2Ftb3JpMB4XDTI2MDgxOTA1MzMzNFoXDTM2MDgxNjA1MzMzNFowNTEiMCAGA1UE
    AwwZS2Ftb3JpIFBvc3RncmVTUUwgUm9vdCBDQTEPMA0GA1UECgwGS2Ftb3JpMHYw
    EAYHKoZIzj0CAQYFK4EEACIDYgAEDb439S5SnwLjL5HBNcv0S+IVONgtMU5HJY/s
    oxFzZ4ZmDS6dNT+cDwUIHqiiNcFxXfAJmleYoNLUSB/jOzEVITwkrQ/je/IMd2TM
    JIcDSHQduhDlaJxXtFVtvoaX/lA4o2YwZDAfBgNVHSMEGDAWgBSvmylCFzn2bnFY
    2aswWaHWhzdXmzASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAd
    BgNVHQ4EFgQUr5spQhc59m5xWNmrMFmh1oc3V5swCgYIKoZIzj0EAwMDaAAwZQIx
    ALcS7Uc+QMB4YzsQZfV6pjQJ63DujbOkZm7uZECFlmroDwxP7n4jYJne/oxg2a1R
    SgIwL2UCdmVwdclZkdWNdRdvEzZSn3vSmGJlErci6HM1iKy4skkO4tgjERCq+l/D
    Sr7y
    -----END CERTIFICATE-----
  kamori:postgresClientCertificate: |
    -----BEGIN CERTIFICATE-----
    MIICPjCCAcSgAwIBAgIUVz8+XWdYvxmlNkg+Pez3eQ523jIwCgYIKoZIzj0EAwMw
    NTEiMCAGA1UEAwwZS2Ftb3JpIFBvc3RncmVTUUwgUm9vdCBDQTEPMA0GA1UECgwG
    S2Ftb3JpMB4XDTI2MDgxOTA1MzMzNFoXDTI3MDkyMDA1MzMzNFowJjETMBEGA1UE
    AwwKa2Ftb3JpX2FwcDEPMA0GA1UECgwGS2Ftb3JpMHYwEAYHKoZIzj0CAQYFK4EE
    ACIDYgAEeUrM5OTe1CcL15dvaXgeKRdO40IT7SyPWtLEAkfEwTCq6t/X1HoNLiwo
    f0dna5WrCjWQ2XGsVxouFcx2MlMkFsfZA9sSb4+bISw3+hprmDDtcSb2XV0gDJW1
    pvIGXvzUo4GjMIGgMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgeAMBMGA1Ud
    JQQMMAoGCCsGAQUFBwMCMB0GA1UdDgQWBBR0X9De8kfEzMyxYQ6AGjnxgR8nGzAf
    BgNVHSMEGDAWgBSvmylCFzn2bnFY2aswWaHWhzdXmzArBgNVHREEJDAihiBzcGlm
    ZmU6Ly9rYW1vcmkuYXBwL3Bvc3RncmVzL2FwcDAKBggqhkjOPQQDAwNoADBlAjBV
    Mit4bBdNinl4/MQCZsF2lFwoFej2CauDZb5ogcNRCpjpNNF5WN9YwDqB/5USZgwC
    MQCYGa6ob1/hH/JpqHSKGDzfRpr5v1g7E+omE6rNNlDe5JjCIEuSvGUwJy+Xt6NR
    cDY=
    -----END CERTIFICATE-----
  kamori:postgresClientKey:
    secure: v1:UfUG6wmISH74ytbM:09pV9ZpvEAfwjZ4gWpBMvmhaTbZk0pUBAG/gAR+5AHrmdcixewOGTQx30dStoQYC8tFo7N8SR4Au8TnmQr73PyKUYXkGB58uecEIa1q3k6mm8zkQJiXU0SQDoJEhPUL+w5VnQyQGIp0ZjjLvB87k0lqr3fkS+3w7/9vx8rXKl7cmcQ28HY7701Dg7dKxSF87c9GktjZ4molRBoxysLdwWLwEOOYOkuzCmqXAJU5I3jE6CnRZuei2uKCdDyIfXtC0u1+6U7gy8oaYVDQk0+8UMI0Nujw0T/x/uL4zwQUwNmqUe3gJjv04CITS3bPFKmo99oqLC9SYswvYoo0KuaQIrxp0rNPa0bk0dSK0R//bgq9Nt57CYEvvP7Xh6NOSFd2Go5NRAwl7PJUQdPfRGFF2Fnl5oTK7GNApEhaoLacCwZpXRg==
  kamori:jwtSecret:
    secure: v1:0mXzY2nAXP3KvW+Y:H449toazaZK4xOMFv0bUjePeJ2KacTIw8gOZQ0flz5Ef1ReIawOJ10ayIFtOtciJyckZonCAwIDr0pZu
  kamori:adminTotpKek:
    secure: v1:/2OhwNGxBzVXzFHn:pjdxeoC6Pm7nlth6mkVcDvGl/F9tpOwXwysnkCPYGWmbGFtVB6N/9wgxROOnssfhEVi9ajh6W4/wgIKw
  kamori:authTotpKek:
    secure: v1:Ls3uVJeJkNCTH/nN:f7tvtNiC2d8oxwi83n4UC/okn4AylzaI3mJYzGt3+ZcjFkc7aM2Rfitb8ePBgjXNKdTeemSmRWmd2Q0S
  kamori:metricsBearerToken:
    secure: v1:2tp+h1X7AArBghWH:YHSInR25OOhsv4IplsHyCzHIrs4UhIOXTx19QEtuNIwaLerzhzoEAUmZ9xYoQnkewB8rTWwNQcLAW74c
