// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/porkbun/porkbun/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// API key for authentication. Can also be set using the `PORKBUN_API_KEY` environment variable.
func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "porkbun:apiKey")
}

// Use IPv4 only for API requests. Defaults to false.
func GetIpv4Only(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "porkbun:ipv4Only")
}

// Maximum number of retries for API requests. Defaults to 3.
func GetMaxRetries(ctx *pulumi.Context) float64 {
	return config.GetFloat64(ctx, "porkbun:maxRetries")
}

// Secret API key for authentication. Can also be set using the `PORKBUN_SECRET_API_KEY` environment variable.
func GetSecretApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "porkbun:secretApiKey")
}
