// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Use STS AssumeRole to obtain temporary credentials. When configured, the provider exchanges the static credentials for short-lived session credentials.
func GetAssumeRole(ctx *pulumi.Context) string {
	return config.Get(ctx, "minio:assumeRole")
}

// Use STS AssumeRoleWithWebIdentity to obtain credentials from an OIDC token (e.g., GitHub Actions, GitLab CI).
func GetAssumeRoleWithWebIdentity(ctx *pulumi.Context) string {
	return config.Get(ctx, "minio:assumeRoleWithWebIdentity")
}

// Maximum number of retries for failed operations (default: 6)
func GetMaxRetries(ctx *pulumi.Context) float64 {
	return config.GetFloat64(ctx, "minio:maxRetries")
}

// MinIO access key (deprecated: use<span pulumi-lang-nodejs=" minioUser " pulumi-lang-dotnet=" MinioUser " pulumi-lang-go=" minioUser " pulumi-lang-python=" minio_user " pulumi-lang-yaml=" minioUser " pulumi-lang-java=" minioUser " pulumi-lang-hcl=" minio_user "> minioUser </span>instead)
//
// Deprecated: Deprecated
func GetMinioAccessKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "minio:minioAccessKey")
}

// MinIO API Version (v2 or v4)
func GetMinioApiVersion(ctx *pulumi.Context) string {
	return config.Get(ctx, "minio:minioApiVersion")
}

// Path to CA certificate file for SSL verification
func GetMinioCacertFile(ctx *pulumi.Context) string {
	return config.Get(ctx, "minio:minioCacertFile")
}

// Path to client certificate file for SSL authentication
func GetMinioCertFile(ctx *pulumi.Context) string {
	return config.Get(ctx, "minio:minioCertFile")
}

// Enable debug logging for API requests
func GetMinioDebug(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "minio:minioDebug")
}

// Override the auto-detected MinIO edition (e.g. `AIStor` to force AIStor-shaped behaviors). Leave empty to auto-detect from `ServerInfo`. Set this only when the provider misclassifies your server — for example an AIStor build whose `ServerInfo` response does not surface the <span pulumi-lang-nodejs="`edition`" pulumi-lang-dotnet="`Edition`" pulumi-lang-go="`edition`" pulumi-lang-python="`edition`" pulumi-lang-yaml="`edition`" pulumi-lang-java="`edition`" pulumi-lang-hcl="`edition`">`edition`</span> field.
func GetMinioEdition(ctx *pulumi.Context) string {
	return config.Get(ctx, "minio:minioEdition")
}

// Skip SSL certificate verification (not recommended for production)
func GetMinioInsecure(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "minio:minioInsecure")
}

// Path to client private key file for SSL authentication
func GetMinioKeyFile(ctx *pulumi.Context) string {
	return config.Get(ctx, "minio:minioKeyFile")
}

// MinIO password (or secret key) for authentication
func GetMinioPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "minio:minioPassword")
}

// Region used for request signing and sent to the S3 client. Defaults to `us-east-1`. Set this to match the region configured on your server, or to any non-empty string when using S3-compatible stores that require a specific region (e.g. Versity Gateway, Hetzner Object Storage).
func GetMinioRegion(ctx *pulumi.Context) string {
	return config.Get(ctx, "minio:minioRegion")
}

// MinIO secret key (deprecated: use<span pulumi-lang-nodejs=" minioPassword " pulumi-lang-dotnet=" MinioPassword " pulumi-lang-go=" minioPassword " pulumi-lang-python=" minio_password " pulumi-lang-yaml=" minioPassword " pulumi-lang-java=" minioPassword " pulumi-lang-hcl=" minio_password "> minioPassword </span>instead)
//
// Deprecated: Deprecated
func GetMinioSecretKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "minio:minioSecretKey")
}

// MinIO server endpoint in the format host:port
func GetMinioServer(ctx *pulumi.Context) string {
	return config.Get(ctx, "minio:minioServer")
}

// MinIO session token for temporary credentials
func GetMinioSessionToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "minio:minioSessionToken")
}

// Enable SSL/TLS for MinIO connection
func GetMinioSsl(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "minio:minioSsl")
}

// MinIO user (or access key) for authentication
func GetMinioUser(ctx *pulumi.Context) string {
	return config.Get(ctx, "minio:minioUser")
}

// Global HTTP request timeout in seconds for all MinIO API calls (default: 30)
func GetRequestTimeoutSeconds(ctx *pulumi.Context) float64 {
	return config.GetFloat64(ctx, "minio:requestTimeoutSeconds")
}

// Base delay in milliseconds between retries, used with exponential backoff (default: 1000)
func GetRetryDelayMs(ctx *pulumi.Context) float64 {
	return config.GetFloat64(ctx, "minio:retryDelayMs")
}

// Enable S3 compatibility mode for non-MinIO backends (Hetzner, Cloudflare R2, Backblaze B2, DigitalOcean Spaces). Gracefully handles unsupported S3 features instead of erroring.
func GetS3CompatMode(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "minio:s3CompatMode")
}

// Skip bucket tagging API calls. Useful when your S3-compatible endpoint does not support tagging.
func GetSkipBucketTagging(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "minio:skipBucketTagging")
}
