// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Accesskey struct {
	pulumi.CustomResourceState

	// The access key. If provided, must be between 8 and 20 characters.
	AccessKey   pulumi.StringOutput `pulumi:"accessKey"`
	AccesskeyId pulumi.StringOutput `pulumi:"accesskeyId"`
	// Description for the access key (max 256 characters).
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Policy to attach to the access key (policy name or JSON document).
	Policy pulumi.StringPtrOutput `pulumi:"policy"`
	// The secret key. If provided, must be at least 8 characters. This is a write-only field and will not be stored in state.
	SecretKey pulumi.StringPtrOutput `pulumi:"secretKey"`
	// Version identifier for the secret key. Change this value to trigger a secret key rotation. Can be a hash, version number, timestamp, or any string that changes when the secret changes.
	SecretKeyVersion pulumi.StringPtrOutput `pulumi:"secretKeyVersion"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Write-only secret key for the access key.
	SecretKeyWo pulumi.StringPtrOutput `pulumi:"secretKeyWo"`
	// Version identifier for secret_key_wo. Increment this integer to trigger rotation when using secret_key_wo.
	SecretKeyWoVersion pulumi.Float64PtrOutput `pulumi:"secretKeyWoVersion"`
	// The status of the access key (enabled/disabled).
	Status   pulumi.StringPtrOutput     `pulumi:"status"`
	Timeouts AccesskeyTimeoutsPtrOutput `pulumi:"timeouts"`
	// The user for whom the access key is managed.
	User pulumi.StringOutput `pulumi:"user"`
}

// NewAccesskey registers a new resource with the given unique name, arguments, and options.
func NewAccesskey(ctx *pulumi.Context,
	name string, args *AccesskeyArgs, opts ...pulumi.ResourceOption) (*Accesskey, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.User == nil {
		return nil, errors.New("invalid value for required argument 'User'")
	}
	if args.AccessKey != nil {
		args.AccessKey = pulumi.ToSecret(args.AccessKey).(pulumi.StringPtrInput)
	}
	if args.SecretKey != nil {
		args.SecretKey = pulumi.ToSecret(args.SecretKey).(pulumi.StringPtrInput)
	}
	if args.SecretKeyWo != nil {
		args.SecretKeyWo = pulumi.ToSecret(args.SecretKeyWo).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"accessKey",
		"secretKey",
		"secretKeyWo",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Accesskey
	err = ctx.RegisterPackageResource("minio:index/accesskey:Accesskey", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAccesskey gets an existing Accesskey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAccesskey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AccesskeyState, opts ...pulumi.ResourceOption) (*Accesskey, error) {
	var resource Accesskey
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/accesskey:Accesskey", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Accesskey resources.
type accesskeyState struct {
	// The access key. If provided, must be between 8 and 20 characters.
	AccessKey   *string `pulumi:"accessKey"`
	AccesskeyId *string `pulumi:"accesskeyId"`
	// Description for the access key (max 256 characters).
	Description *string `pulumi:"description"`
	// Policy to attach to the access key (policy name or JSON document).
	Policy *string `pulumi:"policy"`
	// The secret key. If provided, must be at least 8 characters. This is a write-only field and will not be stored in state.
	SecretKey *string `pulumi:"secretKey"`
	// Version identifier for the secret key. Change this value to trigger a secret key rotation. Can be a hash, version number, timestamp, or any string that changes when the secret changes.
	SecretKeyVersion *string `pulumi:"secretKeyVersion"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Write-only secret key for the access key.
	SecretKeyWo *string `pulumi:"secretKeyWo"`
	// Version identifier for secret_key_wo. Increment this integer to trigger rotation when using secret_key_wo.
	SecretKeyWoVersion *float64 `pulumi:"secretKeyWoVersion"`
	// The status of the access key (enabled/disabled).
	Status   *string            `pulumi:"status"`
	Timeouts *AccesskeyTimeouts `pulumi:"timeouts"`
	// The user for whom the access key is managed.
	User *string `pulumi:"user"`
}

type AccesskeyState struct {
	// The access key. If provided, must be between 8 and 20 characters.
	AccessKey   pulumi.StringPtrInput
	AccesskeyId pulumi.StringPtrInput
	// Description for the access key (max 256 characters).
	Description pulumi.StringPtrInput
	// Policy to attach to the access key (policy name or JSON document).
	Policy pulumi.StringPtrInput
	// The secret key. If provided, must be at least 8 characters. This is a write-only field and will not be stored in state.
	SecretKey pulumi.StringPtrInput
	// Version identifier for the secret key. Change this value to trigger a secret key rotation. Can be a hash, version number, timestamp, or any string that changes when the secret changes.
	SecretKeyVersion pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Write-only secret key for the access key.
	SecretKeyWo pulumi.StringPtrInput
	// Version identifier for secret_key_wo. Increment this integer to trigger rotation when using secret_key_wo.
	SecretKeyWoVersion pulumi.Float64PtrInput
	// The status of the access key (enabled/disabled).
	Status   pulumi.StringPtrInput
	Timeouts AccesskeyTimeoutsPtrInput
	// The user for whom the access key is managed.
	User pulumi.StringPtrInput
}

func (AccesskeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*accesskeyState)(nil)).Elem()
}

type accesskeyArgs struct {
	// The access key. If provided, must be between 8 and 20 characters.
	AccessKey   *string `pulumi:"accessKey"`
	AccesskeyId *string `pulumi:"accesskeyId"`
	// Description for the access key (max 256 characters).
	Description *string `pulumi:"description"`
	// Policy to attach to the access key (policy name or JSON document).
	Policy *string `pulumi:"policy"`
	// The secret key. If provided, must be at least 8 characters. This is a write-only field and will not be stored in state.
	SecretKey *string `pulumi:"secretKey"`
	// Version identifier for the secret key. Change this value to trigger a secret key rotation. Can be a hash, version number, timestamp, or any string that changes when the secret changes.
	SecretKeyVersion *string `pulumi:"secretKeyVersion"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Write-only secret key for the access key.
	SecretKeyWo *string `pulumi:"secretKeyWo"`
	// Version identifier for secret_key_wo. Increment this integer to trigger rotation when using secret_key_wo.
	SecretKeyWoVersion *float64 `pulumi:"secretKeyWoVersion"`
	// The status of the access key (enabled/disabled).
	Status   *string            `pulumi:"status"`
	Timeouts *AccesskeyTimeouts `pulumi:"timeouts"`
	// The user for whom the access key is managed.
	User string `pulumi:"user"`
}

// The set of arguments for constructing a Accesskey resource.
type AccesskeyArgs struct {
	// The access key. If provided, must be between 8 and 20 characters.
	AccessKey   pulumi.StringPtrInput
	AccesskeyId pulumi.StringPtrInput
	// Description for the access key (max 256 characters).
	Description pulumi.StringPtrInput
	// Policy to attach to the access key (policy name or JSON document).
	Policy pulumi.StringPtrInput
	// The secret key. If provided, must be at least 8 characters. This is a write-only field and will not be stored in state.
	SecretKey pulumi.StringPtrInput
	// Version identifier for the secret key. Change this value to trigger a secret key rotation. Can be a hash, version number, timestamp, or any string that changes when the secret changes.
	SecretKeyVersion pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Write-only secret key for the access key.
	SecretKeyWo pulumi.StringPtrInput
	// Version identifier for secret_key_wo. Increment this integer to trigger rotation when using secret_key_wo.
	SecretKeyWoVersion pulumi.Float64PtrInput
	// The status of the access key (enabled/disabled).
	Status   pulumi.StringPtrInput
	Timeouts AccesskeyTimeoutsPtrInput
	// The user for whom the access key is managed.
	User pulumi.StringInput
}

func (AccesskeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*accesskeyArgs)(nil)).Elem()
}

type AccesskeyInput interface {
	pulumi.Input

	ToAccesskeyOutput() AccesskeyOutput
	ToAccesskeyOutputWithContext(ctx context.Context) AccesskeyOutput
}

func (*Accesskey) ElementType() reflect.Type {
	return reflect.TypeOf((**Accesskey)(nil)).Elem()
}

func (i *Accesskey) ToAccesskeyOutput() AccesskeyOutput {
	return i.ToAccesskeyOutputWithContext(context.Background())
}

func (i *Accesskey) ToAccesskeyOutputWithContext(ctx context.Context) AccesskeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccesskeyOutput)
}

type AccesskeyOutput struct{ *pulumi.OutputState }

func (AccesskeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Accesskey)(nil)).Elem()
}

func (o AccesskeyOutput) ToAccesskeyOutput() AccesskeyOutput {
	return o
}

func (o AccesskeyOutput) ToAccesskeyOutputWithContext(ctx context.Context) AccesskeyOutput {
	return o
}

// The access key. If provided, must be between 8 and 20 characters.
func (o AccesskeyOutput) AccessKey() pulumi.StringOutput {
	return o.ApplyT(func(v *Accesskey) pulumi.StringOutput { return v.AccessKey }).(pulumi.StringOutput)
}

func (o AccesskeyOutput) AccesskeyId() pulumi.StringOutput {
	return o.ApplyT(func(v *Accesskey) pulumi.StringOutput { return v.AccesskeyId }).(pulumi.StringOutput)
}

// Description for the access key (max 256 characters).
func (o AccesskeyOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Accesskey) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Policy to attach to the access key (policy name or JSON document).
func (o AccesskeyOutput) Policy() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Accesskey) pulumi.StringPtrOutput { return v.Policy }).(pulumi.StringPtrOutput)
}

// The secret key. If provided, must be at least 8 characters. This is a write-only field and will not be stored in state.
func (o AccesskeyOutput) SecretKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Accesskey) pulumi.StringPtrOutput { return v.SecretKey }).(pulumi.StringPtrOutput)
}

// Version identifier for the secret key. Change this value to trigger a secret key rotation. Can be a hash, version number, timestamp, or any string that changes when the secret changes.
func (o AccesskeyOutput) SecretKeyVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Accesskey) pulumi.StringPtrOutput { return v.SecretKeyVersion }).(pulumi.StringPtrOutput)
}

// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
// Write-only secret key for the access key.
func (o AccesskeyOutput) SecretKeyWo() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Accesskey) pulumi.StringPtrOutput { return v.SecretKeyWo }).(pulumi.StringPtrOutput)
}

// Version identifier for secret_key_wo. Increment this integer to trigger rotation when using secret_key_wo.
func (o AccesskeyOutput) SecretKeyWoVersion() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *Accesskey) pulumi.Float64PtrOutput { return v.SecretKeyWoVersion }).(pulumi.Float64PtrOutput)
}

// The status of the access key (enabled/disabled).
func (o AccesskeyOutput) Status() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Accesskey) pulumi.StringPtrOutput { return v.Status }).(pulumi.StringPtrOutput)
}

func (o AccesskeyOutput) Timeouts() AccesskeyTimeoutsPtrOutput {
	return o.ApplyT(func(v *Accesskey) AccesskeyTimeoutsPtrOutput { return v.Timeouts }).(AccesskeyTimeoutsPtrOutput)
}

// The user for whom the access key is managed.
func (o AccesskeyOutput) User() pulumi.StringOutput {
	return o.ApplyT(func(v *Accesskey) pulumi.StringOutput { return v.User }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AccesskeyInput)(nil)).Elem(), &Accesskey{})
	pulumi.RegisterOutputType(AccesskeyOutput{})
}
