// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type AuditKafka struct {
	pulumi.CustomResourceState

	AuditKafkaId pulumi.StringOutput `pulumi:"auditKafkaId"`
	// Comma-separated list of Kafka broker addresses.
	Brokers pulumi.StringOutput `pulumi:"brokers"`
	// Path to client TLS certificate.
	ClientTlsCert pulumi.StringPtrOutput `pulumi:"clientTlsCert"`
	// Path to client TLS private key.
	ClientTlsKey pulumi.StringPtrOutput `pulumi:"clientTlsKey"`
	// Comment or description for this notification target.
	Comment pulumi.StringPtrOutput `pulumi:"comment"`
	// Whether this notification target is enabled.
	Enable pulumi.BoolPtrOutput `pulumi:"enable"`
	// Target name identifier.
	Name pulumi.StringOutput `pulumi:"name"`
	// Directory path for persistent event store when the target is offline.
	QueueDir pulumi.StringPtrOutput `pulumi:"queueDir"`
	// Maximum number of undelivered messages to queue.
	QueueLimit pulumi.Float64Output `pulumi:"queueLimit"`
	// Indicates whether a MinIO server restart is required.
	RestartRequired pulumi.BoolOutput `pulumi:"restartRequired"`
	// SASL mechanism (plain, scram-sha-256, scram-sha-512).
	SaslMechanism pulumi.StringOutput `pulumi:"saslMechanism"`
	// SASL password for Kafka authentication.
	SaslPassword pulumi.StringPtrOutput `pulumi:"saslPassword"`
	// SASL username for Kafka authentication.
	SaslUsername pulumi.StringPtrOutput `pulumi:"saslUsername"`
	// Enable TLS for Kafka connections.
	Tls pulumi.BoolPtrOutput `pulumi:"tls"`
	// Skip TLS certificate verification.
	TlsSkipVerify pulumi.BoolPtrOutput `pulumi:"tlsSkipVerify"`
	// Kafka topic for audit events.
	Topic pulumi.StringOutput `pulumi:"topic"`
	// Kafka protocol version.
	Version pulumi.StringPtrOutput `pulumi:"version"`
}

// NewAuditKafka registers a new resource with the given unique name, arguments, and options.
func NewAuditKafka(ctx *pulumi.Context,
	name string, args *AuditKafkaArgs, opts ...pulumi.ResourceOption) (*AuditKafka, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Brokers == nil {
		return nil, errors.New("invalid value for required argument 'Brokers'")
	}
	if args.Topic == nil {
		return nil, errors.New("invalid value for required argument 'Topic'")
	}
	if args.ClientTlsKey != nil {
		args.ClientTlsKey = pulumi.ToSecret(args.ClientTlsKey).(pulumi.StringPtrInput)
	}
	if args.SaslPassword != nil {
		args.SaslPassword = pulumi.ToSecret(args.SaslPassword).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientTlsKey",
		"saslPassword",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource AuditKafka
	err = ctx.RegisterPackageResource("minio:index/auditKafka:AuditKafka", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAuditKafka gets an existing AuditKafka resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAuditKafka(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AuditKafkaState, opts ...pulumi.ResourceOption) (*AuditKafka, error) {
	var resource AuditKafka
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/auditKafka:AuditKafka", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AuditKafka resources.
type auditKafkaState struct {
	AuditKafkaId *string `pulumi:"auditKafkaId"`
	// Comma-separated list of Kafka broker addresses.
	Brokers *string `pulumi:"brokers"`
	// Path to client TLS certificate.
	ClientTlsCert *string `pulumi:"clientTlsCert"`
	// Path to client TLS private key.
	ClientTlsKey *string `pulumi:"clientTlsKey"`
	// Comment or description for this notification target.
	Comment *string `pulumi:"comment"`
	// Whether this notification target is enabled.
	Enable *bool `pulumi:"enable"`
	// Target name identifier.
	Name *string `pulumi:"name"`
	// Directory path for persistent event store when the target is offline.
	QueueDir *string `pulumi:"queueDir"`
	// Maximum number of undelivered messages to queue.
	QueueLimit *float64 `pulumi:"queueLimit"`
	// Indicates whether a MinIO server restart is required.
	RestartRequired *bool `pulumi:"restartRequired"`
	// SASL mechanism (plain, scram-sha-256, scram-sha-512).
	SaslMechanism *string `pulumi:"saslMechanism"`
	// SASL password for Kafka authentication.
	SaslPassword *string `pulumi:"saslPassword"`
	// SASL username for Kafka authentication.
	SaslUsername *string `pulumi:"saslUsername"`
	// Enable TLS for Kafka connections.
	Tls *bool `pulumi:"tls"`
	// Skip TLS certificate verification.
	TlsSkipVerify *bool `pulumi:"tlsSkipVerify"`
	// Kafka topic for audit events.
	Topic *string `pulumi:"topic"`
	// Kafka protocol version.
	Version *string `pulumi:"version"`
}

type AuditKafkaState struct {
	AuditKafkaId pulumi.StringPtrInput
	// Comma-separated list of Kafka broker addresses.
	Brokers pulumi.StringPtrInput
	// Path to client TLS certificate.
	ClientTlsCert pulumi.StringPtrInput
	// Path to client TLS private key.
	ClientTlsKey pulumi.StringPtrInput
	// Comment or description for this notification target.
	Comment pulumi.StringPtrInput
	// Whether this notification target is enabled.
	Enable pulumi.BoolPtrInput
	// Target name identifier.
	Name pulumi.StringPtrInput
	// Directory path for persistent event store when the target is offline.
	QueueDir pulumi.StringPtrInput
	// Maximum number of undelivered messages to queue.
	QueueLimit pulumi.Float64PtrInput
	// Indicates whether a MinIO server restart is required.
	RestartRequired pulumi.BoolPtrInput
	// SASL mechanism (plain, scram-sha-256, scram-sha-512).
	SaslMechanism pulumi.StringPtrInput
	// SASL password for Kafka authentication.
	SaslPassword pulumi.StringPtrInput
	// SASL username for Kafka authentication.
	SaslUsername pulumi.StringPtrInput
	// Enable TLS for Kafka connections.
	Tls pulumi.BoolPtrInput
	// Skip TLS certificate verification.
	TlsSkipVerify pulumi.BoolPtrInput
	// Kafka topic for audit events.
	Topic pulumi.StringPtrInput
	// Kafka protocol version.
	Version pulumi.StringPtrInput
}

func (AuditKafkaState) ElementType() reflect.Type {
	return reflect.TypeOf((*auditKafkaState)(nil)).Elem()
}

type auditKafkaArgs struct {
	AuditKafkaId *string `pulumi:"auditKafkaId"`
	// Comma-separated list of Kafka broker addresses.
	Brokers string `pulumi:"brokers"`
	// Path to client TLS certificate.
	ClientTlsCert *string `pulumi:"clientTlsCert"`
	// Path to client TLS private key.
	ClientTlsKey *string `pulumi:"clientTlsKey"`
	// Comment or description for this notification target.
	Comment *string `pulumi:"comment"`
	// Whether this notification target is enabled.
	Enable *bool `pulumi:"enable"`
	// Target name identifier.
	Name *string `pulumi:"name"`
	// Directory path for persistent event store when the target is offline.
	QueueDir *string `pulumi:"queueDir"`
	// Maximum number of undelivered messages to queue.
	QueueLimit *float64 `pulumi:"queueLimit"`
	// SASL mechanism (plain, scram-sha-256, scram-sha-512).
	SaslMechanism *string `pulumi:"saslMechanism"`
	// SASL password for Kafka authentication.
	SaslPassword *string `pulumi:"saslPassword"`
	// SASL username for Kafka authentication.
	SaslUsername *string `pulumi:"saslUsername"`
	// Enable TLS for Kafka connections.
	Tls *bool `pulumi:"tls"`
	// Skip TLS certificate verification.
	TlsSkipVerify *bool `pulumi:"tlsSkipVerify"`
	// Kafka topic for audit events.
	Topic string `pulumi:"topic"`
	// Kafka protocol version.
	Version *string `pulumi:"version"`
}

// The set of arguments for constructing a AuditKafka resource.
type AuditKafkaArgs struct {
	AuditKafkaId pulumi.StringPtrInput
	// Comma-separated list of Kafka broker addresses.
	Brokers pulumi.StringInput
	// Path to client TLS certificate.
	ClientTlsCert pulumi.StringPtrInput
	// Path to client TLS private key.
	ClientTlsKey pulumi.StringPtrInput
	// Comment or description for this notification target.
	Comment pulumi.StringPtrInput
	// Whether this notification target is enabled.
	Enable pulumi.BoolPtrInput
	// Target name identifier.
	Name pulumi.StringPtrInput
	// Directory path for persistent event store when the target is offline.
	QueueDir pulumi.StringPtrInput
	// Maximum number of undelivered messages to queue.
	QueueLimit pulumi.Float64PtrInput
	// SASL mechanism (plain, scram-sha-256, scram-sha-512).
	SaslMechanism pulumi.StringPtrInput
	// SASL password for Kafka authentication.
	SaslPassword pulumi.StringPtrInput
	// SASL username for Kafka authentication.
	SaslUsername pulumi.StringPtrInput
	// Enable TLS for Kafka connections.
	Tls pulumi.BoolPtrInput
	// Skip TLS certificate verification.
	TlsSkipVerify pulumi.BoolPtrInput
	// Kafka topic for audit events.
	Topic pulumi.StringInput
	// Kafka protocol version.
	Version pulumi.StringPtrInput
}

func (AuditKafkaArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*auditKafkaArgs)(nil)).Elem()
}

type AuditKafkaInput interface {
	pulumi.Input

	ToAuditKafkaOutput() AuditKafkaOutput
	ToAuditKafkaOutputWithContext(ctx context.Context) AuditKafkaOutput
}

func (*AuditKafka) ElementType() reflect.Type {
	return reflect.TypeOf((**AuditKafka)(nil)).Elem()
}

func (i *AuditKafka) ToAuditKafkaOutput() AuditKafkaOutput {
	return i.ToAuditKafkaOutputWithContext(context.Background())
}

func (i *AuditKafka) ToAuditKafkaOutputWithContext(ctx context.Context) AuditKafkaOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuditKafkaOutput)
}

type AuditKafkaOutput struct{ *pulumi.OutputState }

func (AuditKafkaOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AuditKafka)(nil)).Elem()
}

func (o AuditKafkaOutput) ToAuditKafkaOutput() AuditKafkaOutput {
	return o
}

func (o AuditKafkaOutput) ToAuditKafkaOutputWithContext(ctx context.Context) AuditKafkaOutput {
	return o
}

func (o AuditKafkaOutput) AuditKafkaId() pulumi.StringOutput {
	return o.ApplyT(func(v *AuditKafka) pulumi.StringOutput { return v.AuditKafkaId }).(pulumi.StringOutput)
}

// Comma-separated list of Kafka broker addresses.
func (o AuditKafkaOutput) Brokers() pulumi.StringOutput {
	return o.ApplyT(func(v *AuditKafka) pulumi.StringOutput { return v.Brokers }).(pulumi.StringOutput)
}

// Path to client TLS certificate.
func (o AuditKafkaOutput) ClientTlsCert() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AuditKafka) pulumi.StringPtrOutput { return v.ClientTlsCert }).(pulumi.StringPtrOutput)
}

// Path to client TLS private key.
func (o AuditKafkaOutput) ClientTlsKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AuditKafka) pulumi.StringPtrOutput { return v.ClientTlsKey }).(pulumi.StringPtrOutput)
}

// Comment or description for this notification target.
func (o AuditKafkaOutput) Comment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AuditKafka) pulumi.StringPtrOutput { return v.Comment }).(pulumi.StringPtrOutput)
}

// Whether this notification target is enabled.
func (o AuditKafkaOutput) Enable() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AuditKafka) pulumi.BoolPtrOutput { return v.Enable }).(pulumi.BoolPtrOutput)
}

// Target name identifier.
func (o AuditKafkaOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *AuditKafka) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Directory path for persistent event store when the target is offline.
func (o AuditKafkaOutput) QueueDir() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AuditKafka) pulumi.StringPtrOutput { return v.QueueDir }).(pulumi.StringPtrOutput)
}

// Maximum number of undelivered messages to queue.
func (o AuditKafkaOutput) QueueLimit() pulumi.Float64Output {
	return o.ApplyT(func(v *AuditKafka) pulumi.Float64Output { return v.QueueLimit }).(pulumi.Float64Output)
}

// Indicates whether a MinIO server restart is required.
func (o AuditKafkaOutput) RestartRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v *AuditKafka) pulumi.BoolOutput { return v.RestartRequired }).(pulumi.BoolOutput)
}

// SASL mechanism (plain, scram-sha-256, scram-sha-512).
func (o AuditKafkaOutput) SaslMechanism() pulumi.StringOutput {
	return o.ApplyT(func(v *AuditKafka) pulumi.StringOutput { return v.SaslMechanism }).(pulumi.StringOutput)
}

// SASL password for Kafka authentication.
func (o AuditKafkaOutput) SaslPassword() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AuditKafka) pulumi.StringPtrOutput { return v.SaslPassword }).(pulumi.StringPtrOutput)
}

// SASL username for Kafka authentication.
func (o AuditKafkaOutput) SaslUsername() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AuditKafka) pulumi.StringPtrOutput { return v.SaslUsername }).(pulumi.StringPtrOutput)
}

// Enable TLS for Kafka connections.
func (o AuditKafkaOutput) Tls() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AuditKafka) pulumi.BoolPtrOutput { return v.Tls }).(pulumi.BoolPtrOutput)
}

// Skip TLS certificate verification.
func (o AuditKafkaOutput) TlsSkipVerify() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AuditKafka) pulumi.BoolPtrOutput { return v.TlsSkipVerify }).(pulumi.BoolPtrOutput)
}

// Kafka topic for audit events.
func (o AuditKafkaOutput) Topic() pulumi.StringOutput {
	return o.ApplyT(func(v *AuditKafka) pulumi.StringOutput { return v.Topic }).(pulumi.StringOutput)
}

// Kafka protocol version.
func (o AuditKafkaOutput) Version() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AuditKafka) pulumi.StringPtrOutput { return v.Version }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AuditKafkaInput)(nil)).Elem(), &AuditKafka{})
	pulumi.RegisterOutputType(AuditKafkaOutput{})
}
