// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type BucketMetadataImport struct {
	pulumi.CustomResourceState

	// Name of the bucket to import metadata into.
	Bucket                 pulumi.StringOutput `pulumi:"bucket"`
	BucketMetadataImportId pulumi.StringOutput `pulumi:"bucketMetadataImportId"`
	// RFC3339 timestamp of the successful import.
	ImportedAt pulumi.StringOutput `pulumi:"importedAt"`
	// Base64-encoded zip stream of bucket metadata (from <span pulumi-lang-nodejs="`minio.getBucketMetadataExport`" pulumi-lang-dotnet="`minio.getBucketMetadataExport`" pulumi-lang-go="`getBucketMetadataExport`" pulumi-lang-python="`get_bucket_metadata_export`" pulumi-lang-yaml="`minio.getBucketMetadataExport`" pulumi-lang-java="`minio.getBucketMetadataExport`" pulumi-lang-hcl="`data.minio_bucket_metadata_export`">`minio.getBucketMetadataExport`</span>). Bytes are not compared after the initial import because re-exports of the same bucket are not byte-identical (zip timestamps); use <span pulumi-lang-nodejs="`triggers`" pulumi-lang-dotnet="`Triggers`" pulumi-lang-go="`triggers`" pulumi-lang-python="`triggers`" pulumi-lang-yaml="`triggers`" pulumi-lang-java="`triggers`" pulumi-lang-hcl="`triggers`">`triggers`</span> to force a re-import.
	Metadata pulumi.StringOutput `pulumi:"metadata"`
	// Map of arbitrary strings that, when changed, force re-import of the metadata.
	Triggers pulumi.StringMapOutput `pulumi:"triggers"`
}

// NewBucketMetadataImport registers a new resource with the given unique name, arguments, and options.
func NewBucketMetadataImport(ctx *pulumi.Context,
	name string, args *BucketMetadataImportArgs, opts ...pulumi.ResourceOption) (*BucketMetadataImport, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Bucket == nil {
		return nil, errors.New("invalid value for required argument 'Bucket'")
	}
	if args.Metadata == nil {
		return nil, errors.New("invalid value for required argument 'Metadata'")
	}
	if args.Metadata != nil {
		args.Metadata = pulumi.ToSecret(args.Metadata).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"metadata",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource BucketMetadataImport
	err = ctx.RegisterPackageResource("minio:index/bucketMetadataImport:BucketMetadataImport", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBucketMetadataImport gets an existing BucketMetadataImport resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBucketMetadataImport(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BucketMetadataImportState, opts ...pulumi.ResourceOption) (*BucketMetadataImport, error) {
	var resource BucketMetadataImport
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/bucketMetadataImport:BucketMetadataImport", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering BucketMetadataImport resources.
type bucketMetadataImportState struct {
	// Name of the bucket to import metadata into.
	Bucket                 *string `pulumi:"bucket"`
	BucketMetadataImportId *string `pulumi:"bucketMetadataImportId"`
	// RFC3339 timestamp of the successful import.
	ImportedAt *string `pulumi:"importedAt"`
	// Base64-encoded zip stream of bucket metadata (from <span pulumi-lang-nodejs="`minio.getBucketMetadataExport`" pulumi-lang-dotnet="`minio.getBucketMetadataExport`" pulumi-lang-go="`getBucketMetadataExport`" pulumi-lang-python="`get_bucket_metadata_export`" pulumi-lang-yaml="`minio.getBucketMetadataExport`" pulumi-lang-java="`minio.getBucketMetadataExport`" pulumi-lang-hcl="`data.minio_bucket_metadata_export`">`minio.getBucketMetadataExport`</span>). Bytes are not compared after the initial import because re-exports of the same bucket are not byte-identical (zip timestamps); use <span pulumi-lang-nodejs="`triggers`" pulumi-lang-dotnet="`Triggers`" pulumi-lang-go="`triggers`" pulumi-lang-python="`triggers`" pulumi-lang-yaml="`triggers`" pulumi-lang-java="`triggers`" pulumi-lang-hcl="`triggers`">`triggers`</span> to force a re-import.
	Metadata *string `pulumi:"metadata"`
	// Map of arbitrary strings that, when changed, force re-import of the metadata.
	Triggers map[string]string `pulumi:"triggers"`
}

type BucketMetadataImportState struct {
	// Name of the bucket to import metadata into.
	Bucket                 pulumi.StringPtrInput
	BucketMetadataImportId pulumi.StringPtrInput
	// RFC3339 timestamp of the successful import.
	ImportedAt pulumi.StringPtrInput
	// Base64-encoded zip stream of bucket metadata (from <span pulumi-lang-nodejs="`minio.getBucketMetadataExport`" pulumi-lang-dotnet="`minio.getBucketMetadataExport`" pulumi-lang-go="`getBucketMetadataExport`" pulumi-lang-python="`get_bucket_metadata_export`" pulumi-lang-yaml="`minio.getBucketMetadataExport`" pulumi-lang-java="`minio.getBucketMetadataExport`" pulumi-lang-hcl="`data.minio_bucket_metadata_export`">`minio.getBucketMetadataExport`</span>). Bytes are not compared after the initial import because re-exports of the same bucket are not byte-identical (zip timestamps); use <span pulumi-lang-nodejs="`triggers`" pulumi-lang-dotnet="`Triggers`" pulumi-lang-go="`triggers`" pulumi-lang-python="`triggers`" pulumi-lang-yaml="`triggers`" pulumi-lang-java="`triggers`" pulumi-lang-hcl="`triggers`">`triggers`</span> to force a re-import.
	Metadata pulumi.StringPtrInput
	// Map of arbitrary strings that, when changed, force re-import of the metadata.
	Triggers pulumi.StringMapInput
}

func (BucketMetadataImportState) ElementType() reflect.Type {
	return reflect.TypeOf((*bucketMetadataImportState)(nil)).Elem()
}

type bucketMetadataImportArgs struct {
	// Name of the bucket to import metadata into.
	Bucket                 string  `pulumi:"bucket"`
	BucketMetadataImportId *string `pulumi:"bucketMetadataImportId"`
	// Base64-encoded zip stream of bucket metadata (from <span pulumi-lang-nodejs="`minio.getBucketMetadataExport`" pulumi-lang-dotnet="`minio.getBucketMetadataExport`" pulumi-lang-go="`getBucketMetadataExport`" pulumi-lang-python="`get_bucket_metadata_export`" pulumi-lang-yaml="`minio.getBucketMetadataExport`" pulumi-lang-java="`minio.getBucketMetadataExport`" pulumi-lang-hcl="`data.minio_bucket_metadata_export`">`minio.getBucketMetadataExport`</span>). Bytes are not compared after the initial import because re-exports of the same bucket are not byte-identical (zip timestamps); use <span pulumi-lang-nodejs="`triggers`" pulumi-lang-dotnet="`Triggers`" pulumi-lang-go="`triggers`" pulumi-lang-python="`triggers`" pulumi-lang-yaml="`triggers`" pulumi-lang-java="`triggers`" pulumi-lang-hcl="`triggers`">`triggers`</span> to force a re-import.
	Metadata string `pulumi:"metadata"`
	// Map of arbitrary strings that, when changed, force re-import of the metadata.
	Triggers map[string]string `pulumi:"triggers"`
}

// The set of arguments for constructing a BucketMetadataImport resource.
type BucketMetadataImportArgs struct {
	// Name of the bucket to import metadata into.
	Bucket                 pulumi.StringInput
	BucketMetadataImportId pulumi.StringPtrInput
	// Base64-encoded zip stream of bucket metadata (from <span pulumi-lang-nodejs="`minio.getBucketMetadataExport`" pulumi-lang-dotnet="`minio.getBucketMetadataExport`" pulumi-lang-go="`getBucketMetadataExport`" pulumi-lang-python="`get_bucket_metadata_export`" pulumi-lang-yaml="`minio.getBucketMetadataExport`" pulumi-lang-java="`minio.getBucketMetadataExport`" pulumi-lang-hcl="`data.minio_bucket_metadata_export`">`minio.getBucketMetadataExport`</span>). Bytes are not compared after the initial import because re-exports of the same bucket are not byte-identical (zip timestamps); use <span pulumi-lang-nodejs="`triggers`" pulumi-lang-dotnet="`Triggers`" pulumi-lang-go="`triggers`" pulumi-lang-python="`triggers`" pulumi-lang-yaml="`triggers`" pulumi-lang-java="`triggers`" pulumi-lang-hcl="`triggers`">`triggers`</span> to force a re-import.
	Metadata pulumi.StringInput
	// Map of arbitrary strings that, when changed, force re-import of the metadata.
	Triggers pulumi.StringMapInput
}

func (BucketMetadataImportArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*bucketMetadataImportArgs)(nil)).Elem()
}

type BucketMetadataImportInput interface {
	pulumi.Input

	ToBucketMetadataImportOutput() BucketMetadataImportOutput
	ToBucketMetadataImportOutputWithContext(ctx context.Context) BucketMetadataImportOutput
}

func (*BucketMetadataImport) ElementType() reflect.Type {
	return reflect.TypeOf((**BucketMetadataImport)(nil)).Elem()
}

func (i *BucketMetadataImport) ToBucketMetadataImportOutput() BucketMetadataImportOutput {
	return i.ToBucketMetadataImportOutputWithContext(context.Background())
}

func (i *BucketMetadataImport) ToBucketMetadataImportOutputWithContext(ctx context.Context) BucketMetadataImportOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BucketMetadataImportOutput)
}

type BucketMetadataImportOutput struct{ *pulumi.OutputState }

func (BucketMetadataImportOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**BucketMetadataImport)(nil)).Elem()
}

func (o BucketMetadataImportOutput) ToBucketMetadataImportOutput() BucketMetadataImportOutput {
	return o
}

func (o BucketMetadataImportOutput) ToBucketMetadataImportOutputWithContext(ctx context.Context) BucketMetadataImportOutput {
	return o
}

// Name of the bucket to import metadata into.
func (o BucketMetadataImportOutput) Bucket() pulumi.StringOutput {
	return o.ApplyT(func(v *BucketMetadataImport) pulumi.StringOutput { return v.Bucket }).(pulumi.StringOutput)
}

func (o BucketMetadataImportOutput) BucketMetadataImportId() pulumi.StringOutput {
	return o.ApplyT(func(v *BucketMetadataImport) pulumi.StringOutput { return v.BucketMetadataImportId }).(pulumi.StringOutput)
}

// RFC3339 timestamp of the successful import.
func (o BucketMetadataImportOutput) ImportedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *BucketMetadataImport) pulumi.StringOutput { return v.ImportedAt }).(pulumi.StringOutput)
}

// Base64-encoded zip stream of bucket metadata (from <span pulumi-lang-nodejs="`minio.getBucketMetadataExport`" pulumi-lang-dotnet="`minio.getBucketMetadataExport`" pulumi-lang-go="`getBucketMetadataExport`" pulumi-lang-python="`get_bucket_metadata_export`" pulumi-lang-yaml="`minio.getBucketMetadataExport`" pulumi-lang-java="`minio.getBucketMetadataExport`" pulumi-lang-hcl="`data.minio_bucket_metadata_export`">`minio.getBucketMetadataExport`</span>). Bytes are not compared after the initial import because re-exports of the same bucket are not byte-identical (zip timestamps); use <span pulumi-lang-nodejs="`triggers`" pulumi-lang-dotnet="`Triggers`" pulumi-lang-go="`triggers`" pulumi-lang-python="`triggers`" pulumi-lang-yaml="`triggers`" pulumi-lang-java="`triggers`" pulumi-lang-hcl="`triggers`">`triggers`</span> to force a re-import.
func (o BucketMetadataImportOutput) Metadata() pulumi.StringOutput {
	return o.ApplyT(func(v *BucketMetadataImport) pulumi.StringOutput { return v.Metadata }).(pulumi.StringOutput)
}

// Map of arbitrary strings that, when changed, force re-import of the metadata.
func (o BucketMetadataImportOutput) Triggers() pulumi.StringMapOutput {
	return o.ApplyT(func(v *BucketMetadataImport) pulumi.StringMapOutput { return v.Triggers }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BucketMetadataImportInput)(nil)).Elem(), &BucketMetadataImport{})
	pulumi.RegisterOutputType(BucketMetadataImportOutput{})
}
