// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ConfigRestore struct {
	pulumi.CustomResourceState

	ConfigRestoreId pulumi.StringOutput `pulumi:"configRestoreId"`
	// The configuration data that was restored.
	Data pulumi.StringOutput `pulumi:"data"`
	// The config history restore ID to restore.
	RestoreId pulumi.StringOutput `pulumi:"restoreId"`
}

// NewConfigRestore registers a new resource with the given unique name, arguments, and options.
func NewConfigRestore(ctx *pulumi.Context,
	name string, args *ConfigRestoreArgs, opts ...pulumi.ResourceOption) (*ConfigRestore, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.RestoreId == nil {
		return nil, errors.New("invalid value for required argument 'RestoreId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource ConfigRestore
	err = ctx.RegisterPackageResource("minio:index/configRestore:ConfigRestore", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetConfigRestore gets an existing ConfigRestore resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetConfigRestore(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ConfigRestoreState, opts ...pulumi.ResourceOption) (*ConfigRestore, error) {
	var resource ConfigRestore
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/configRestore:ConfigRestore", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ConfigRestore resources.
type configRestoreState struct {
	ConfigRestoreId *string `pulumi:"configRestoreId"`
	// The configuration data that was restored.
	Data *string `pulumi:"data"`
	// The config history restore ID to restore.
	RestoreId *string `pulumi:"restoreId"`
}

type ConfigRestoreState struct {
	ConfigRestoreId pulumi.StringPtrInput
	// The configuration data that was restored.
	Data pulumi.StringPtrInput
	// The config history restore ID to restore.
	RestoreId pulumi.StringPtrInput
}

func (ConfigRestoreState) ElementType() reflect.Type {
	return reflect.TypeOf((*configRestoreState)(nil)).Elem()
}

type configRestoreArgs struct {
	ConfigRestoreId *string `pulumi:"configRestoreId"`
	// The config history restore ID to restore.
	RestoreId string `pulumi:"restoreId"`
}

// The set of arguments for constructing a ConfigRestore resource.
type ConfigRestoreArgs struct {
	ConfigRestoreId pulumi.StringPtrInput
	// The config history restore ID to restore.
	RestoreId pulumi.StringInput
}

func (ConfigRestoreArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*configRestoreArgs)(nil)).Elem()
}

type ConfigRestoreInput interface {
	pulumi.Input

	ToConfigRestoreOutput() ConfigRestoreOutput
	ToConfigRestoreOutputWithContext(ctx context.Context) ConfigRestoreOutput
}

func (*ConfigRestore) ElementType() reflect.Type {
	return reflect.TypeOf((**ConfigRestore)(nil)).Elem()
}

func (i *ConfigRestore) ToConfigRestoreOutput() ConfigRestoreOutput {
	return i.ToConfigRestoreOutputWithContext(context.Background())
}

func (i *ConfigRestore) ToConfigRestoreOutputWithContext(ctx context.Context) ConfigRestoreOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ConfigRestoreOutput)
}

type ConfigRestoreOutput struct{ *pulumi.OutputState }

func (ConfigRestoreOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ConfigRestore)(nil)).Elem()
}

func (o ConfigRestoreOutput) ToConfigRestoreOutput() ConfigRestoreOutput {
	return o
}

func (o ConfigRestoreOutput) ToConfigRestoreOutputWithContext(ctx context.Context) ConfigRestoreOutput {
	return o
}

func (o ConfigRestoreOutput) ConfigRestoreId() pulumi.StringOutput {
	return o.ApplyT(func(v *ConfigRestore) pulumi.StringOutput { return v.ConfigRestoreId }).(pulumi.StringOutput)
}

// The configuration data that was restored.
func (o ConfigRestoreOutput) Data() pulumi.StringOutput {
	return o.ApplyT(func(v *ConfigRestore) pulumi.StringOutput { return v.Data }).(pulumi.StringOutput)
}

// The config history restore ID to restore.
func (o ConfigRestoreOutput) RestoreId() pulumi.StringOutput {
	return o.ApplyT(func(v *ConfigRestore) pulumi.StringOutput { return v.RestoreId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ConfigRestoreInput)(nil)).Elem(), &ConfigRestore{})
	pulumi.RegisterOutputType(ConfigRestoreOutput{})
}
