// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetAccountInfo(ctx *pulumi.Context, args *GetAccountInfoArgs, opts ...pulumi.InvokeOption) (*GetAccountInfoResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetAccountInfoResult
	err = ctx.InvokePackage("minio:index/getAccountInfo:getAccountInfo", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAccountInfo.
type GetAccountInfoArgs struct {
	Id *string `pulumi:"id"`
}

// A collection of values returned by getAccountInfo.
type GetAccountInfoResult struct {
	AccountName  string                 `pulumi:"accountName"`
	BucketCount  float64                `pulumi:"bucketCount"`
	Buckets      []GetAccountInfoBucket `pulumi:"buckets"`
	Id           string                 `pulumi:"id"`
	TotalObjects string                 `pulumi:"totalObjects"`
	TotalSize    string                 `pulumi:"totalSize"`
}

func GetAccountInfoOutput(ctx *pulumi.Context, args GetAccountInfoOutputArgs, opts ...pulumi.InvokeOption) GetAccountInfoResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getAccountInfo:getAccountInfo", args, GetAccountInfoResultOutput{}, options).(GetAccountInfoResultOutput)
}

// A collection of arguments for invoking getAccountInfo.
type GetAccountInfoOutputArgs struct {
	Id pulumi.StringPtrInput `pulumi:"id"`
}

func (GetAccountInfoOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAccountInfoArgs)(nil)).Elem()
}

// A collection of values returned by getAccountInfo.
type GetAccountInfoResultOutput struct{ *pulumi.OutputState }

func (GetAccountInfoResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAccountInfoResult)(nil)).Elem()
}

func (o GetAccountInfoResultOutput) ToGetAccountInfoResultOutput() GetAccountInfoResultOutput {
	return o
}

func (o GetAccountInfoResultOutput) ToGetAccountInfoResultOutputWithContext(ctx context.Context) GetAccountInfoResultOutput {
	return o
}

func (o GetAccountInfoResultOutput) AccountName() pulumi.StringOutput {
	return o.ApplyT(func(v GetAccountInfoResult) string { return v.AccountName }).(pulumi.StringOutput)
}

func (o GetAccountInfoResultOutput) BucketCount() pulumi.Float64Output {
	return o.ApplyT(func(v GetAccountInfoResult) float64 { return v.BucketCount }).(pulumi.Float64Output)
}

func (o GetAccountInfoResultOutput) Buckets() GetAccountInfoBucketArrayOutput {
	return o.ApplyT(func(v GetAccountInfoResult) []GetAccountInfoBucket { return v.Buckets }).(GetAccountInfoBucketArrayOutput)
}

func (o GetAccountInfoResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetAccountInfoResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetAccountInfoResultOutput) TotalObjects() pulumi.StringOutput {
	return o.ApplyT(func(v GetAccountInfoResult) string { return v.TotalObjects }).(pulumi.StringOutput)
}

func (o GetAccountInfoResultOutput) TotalSize() pulumi.StringOutput {
	return o.ApplyT(func(v GetAccountInfoResult) string { return v.TotalSize }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAccountInfoResultOutput{})
}
