// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetBatchJobTemplate(ctx *pulumi.Context, args *GetBatchJobTemplateArgs, opts ...pulumi.InvokeOption) (*GetBatchJobTemplateResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetBatchJobTemplateResult
	err = ctx.InvokePackage("minio:index/getBatchJobTemplate:getBatchJobTemplate", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBatchJobTemplate.
type GetBatchJobTemplateArgs struct {
	Id      *string `pulumi:"id"`
	JobType string  `pulumi:"jobType"`
}

// A collection of values returned by getBatchJobTemplate.
type GetBatchJobTemplateResult struct {
	Id      string `pulumi:"id"`
	JobType string `pulumi:"jobType"`
	Source  string `pulumi:"source"`
	Yaml    string `pulumi:"yaml"`
}

func GetBatchJobTemplateOutput(ctx *pulumi.Context, args GetBatchJobTemplateOutputArgs, opts ...pulumi.InvokeOption) GetBatchJobTemplateResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getBatchJobTemplate:getBatchJobTemplate", args, GetBatchJobTemplateResultOutput{}, options).(GetBatchJobTemplateResultOutput)
}

// A collection of arguments for invoking getBatchJobTemplate.
type GetBatchJobTemplateOutputArgs struct {
	Id      pulumi.StringPtrInput `pulumi:"id"`
	JobType pulumi.StringInput    `pulumi:"jobType"`
}

func (GetBatchJobTemplateOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBatchJobTemplateArgs)(nil)).Elem()
}

// A collection of values returned by getBatchJobTemplate.
type GetBatchJobTemplateResultOutput struct{ *pulumi.OutputState }

func (GetBatchJobTemplateResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBatchJobTemplateResult)(nil)).Elem()
}

func (o GetBatchJobTemplateResultOutput) ToGetBatchJobTemplateResultOutput() GetBatchJobTemplateResultOutput {
	return o
}

func (o GetBatchJobTemplateResultOutput) ToGetBatchJobTemplateResultOutputWithContext(ctx context.Context) GetBatchJobTemplateResultOutput {
	return o
}

func (o GetBatchJobTemplateResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetBatchJobTemplateResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetBatchJobTemplateResultOutput) JobType() pulumi.StringOutput {
	return o.ApplyT(func(v GetBatchJobTemplateResult) string { return v.JobType }).(pulumi.StringOutput)
}

func (o GetBatchJobTemplateResultOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v GetBatchJobTemplateResult) string { return v.Source }).(pulumi.StringOutput)
}

func (o GetBatchJobTemplateResultOutput) Yaml() pulumi.StringOutput {
	return o.ApplyT(func(v GetBatchJobTemplateResult) string { return v.Yaml }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetBatchJobTemplateResultOutput{})
}
