// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetConfigHistory(ctx *pulumi.Context, args *GetConfigHistoryArgs, opts ...pulumi.InvokeOption) (*GetConfigHistoryResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetConfigHistoryResult
	err = ctx.InvokePackage("minio:index/getConfigHistory:getConfigHistory", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getConfigHistory.
type GetConfigHistoryArgs struct {
	Id    *string  `pulumi:"id"`
	Limit *float64 `pulumi:"limit"`
}

// A collection of values returned by getConfigHistory.
type GetConfigHistoryResult struct {
	Entries []GetConfigHistoryEntry `pulumi:"entries"`
	Id      string                  `pulumi:"id"`
	Limit   *float64                `pulumi:"limit"`
}

func GetConfigHistoryOutput(ctx *pulumi.Context, args GetConfigHistoryOutputArgs, opts ...pulumi.InvokeOption) GetConfigHistoryResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getConfigHistory:getConfigHistory", args, GetConfigHistoryResultOutput{}, options).(GetConfigHistoryResultOutput)
}

// A collection of arguments for invoking getConfigHistory.
type GetConfigHistoryOutputArgs struct {
	Id    pulumi.StringPtrInput  `pulumi:"id"`
	Limit pulumi.Float64PtrInput `pulumi:"limit"`
}

func (GetConfigHistoryOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetConfigHistoryArgs)(nil)).Elem()
}

// A collection of values returned by getConfigHistory.
type GetConfigHistoryResultOutput struct{ *pulumi.OutputState }

func (GetConfigHistoryResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetConfigHistoryResult)(nil)).Elem()
}

func (o GetConfigHistoryResultOutput) ToGetConfigHistoryResultOutput() GetConfigHistoryResultOutput {
	return o
}

func (o GetConfigHistoryResultOutput) ToGetConfigHistoryResultOutputWithContext(ctx context.Context) GetConfigHistoryResultOutput {
	return o
}

func (o GetConfigHistoryResultOutput) Entries() GetConfigHistoryEntryArrayOutput {
	return o.ApplyT(func(v GetConfigHistoryResult) []GetConfigHistoryEntry { return v.Entries }).(GetConfigHistoryEntryArrayOutput)
}

func (o GetConfigHistoryResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetConfigHistoryResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetConfigHistoryResultOutput) Limit() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v GetConfigHistoryResult) *float64 { return v.Limit }).(pulumi.Float64PtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetConfigHistoryResultOutput{})
}
