// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDataUsage(ctx *pulumi.Context, args *GetDataUsageArgs, opts ...pulumi.InvokeOption) (*GetDataUsageResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetDataUsageResult
	err = ctx.InvokePackage("minio:index/getDataUsage:getDataUsage", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDataUsage.
type GetDataUsageArgs struct {
	Id *string `pulumi:"id"`
}

// A collection of values returned by getDataUsage.
type GetDataUsageResult struct {
	BucketsCount float64           `pulumi:"bucketsCount"`
	BucketsUsage map[string]string `pulumi:"bucketsUsage"`
	Id           string            `pulumi:"id"`
	LastUpdate   string            `pulumi:"lastUpdate"`
	TotalObjects string            `pulumi:"totalObjects"`
	TotalSize    string            `pulumi:"totalSize"`
}

func GetDataUsageOutput(ctx *pulumi.Context, args GetDataUsageOutputArgs, opts ...pulumi.InvokeOption) GetDataUsageResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getDataUsage:getDataUsage", args, GetDataUsageResultOutput{}, options).(GetDataUsageResultOutput)
}

// A collection of arguments for invoking getDataUsage.
type GetDataUsageOutputArgs struct {
	Id pulumi.StringPtrInput `pulumi:"id"`
}

func (GetDataUsageOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDataUsageArgs)(nil)).Elem()
}

// A collection of values returned by getDataUsage.
type GetDataUsageResultOutput struct{ *pulumi.OutputState }

func (GetDataUsageResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDataUsageResult)(nil)).Elem()
}

func (o GetDataUsageResultOutput) ToGetDataUsageResultOutput() GetDataUsageResultOutput {
	return o
}

func (o GetDataUsageResultOutput) ToGetDataUsageResultOutputWithContext(ctx context.Context) GetDataUsageResultOutput {
	return o
}

func (o GetDataUsageResultOutput) BucketsCount() pulumi.Float64Output {
	return o.ApplyT(func(v GetDataUsageResult) float64 { return v.BucketsCount }).(pulumi.Float64Output)
}

func (o GetDataUsageResultOutput) BucketsUsage() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetDataUsageResult) map[string]string { return v.BucketsUsage }).(pulumi.StringMapOutput)
}

func (o GetDataUsageResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDataUsageResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetDataUsageResultOutput) LastUpdate() pulumi.StringOutput {
	return o.ApplyT(func(v GetDataUsageResult) string { return v.LastUpdate }).(pulumi.StringOutput)
}

func (o GetDataUsageResultOutput) TotalObjects() pulumi.StringOutput {
	return o.ApplyT(func(v GetDataUsageResult) string { return v.TotalObjects }).(pulumi.StringOutput)
}

func (o GetDataUsageResultOutput) TotalSize() pulumi.StringOutput {
	return o.ApplyT(func(v GetDataUsageResult) string { return v.TotalSize }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDataUsageResultOutput{})
}
