// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupIamUser(ctx *pulumi.Context, args *LookupIamUserArgs, opts ...pulumi.InvokeOption) (*LookupIamUserResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupIamUserResult
	err = ctx.InvokePackage("minio:index/getIamUser:getIamUser", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIamUser.
type LookupIamUserArgs struct {
	Id   *string `pulumi:"id"`
	Name string  `pulumi:"name"`
}

// A collection of values returned by getIamUser.
type LookupIamUserResult struct {
	Id             string            `pulumi:"id"`
	MemberOfGroups []string          `pulumi:"memberOfGroups"`
	Name           string            `pulumi:"name"`
	PolicyNames    []string          `pulumi:"policyNames"`
	Status         string            `pulumi:"status"`
	Tags           map[string]string `pulumi:"tags"`
}

func LookupIamUserOutput(ctx *pulumi.Context, args LookupIamUserOutputArgs, opts ...pulumi.InvokeOption) LookupIamUserResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getIamUser:getIamUser", args, LookupIamUserResultOutput{}, options).(LookupIamUserResultOutput)
}

// A collection of arguments for invoking getIamUser.
type LookupIamUserOutputArgs struct {
	Id   pulumi.StringPtrInput `pulumi:"id"`
	Name pulumi.StringInput    `pulumi:"name"`
}

func (LookupIamUserOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIamUserArgs)(nil)).Elem()
}

// A collection of values returned by getIamUser.
type LookupIamUserResultOutput struct{ *pulumi.OutputState }

func (LookupIamUserResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIamUserResult)(nil)).Elem()
}

func (o LookupIamUserResultOutput) ToLookupIamUserResultOutput() LookupIamUserResultOutput {
	return o
}

func (o LookupIamUserResultOutput) ToLookupIamUserResultOutputWithContext(ctx context.Context) LookupIamUserResultOutput {
	return o
}

func (o LookupIamUserResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIamUserResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupIamUserResultOutput) MemberOfGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupIamUserResult) []string { return v.MemberOfGroups }).(pulumi.StringArrayOutput)
}

func (o LookupIamUserResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIamUserResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupIamUserResultOutput) PolicyNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupIamUserResult) []string { return v.PolicyNames }).(pulumi.StringArrayOutput)
}

func (o LookupIamUserResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIamUserResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupIamUserResultOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupIamUserResult) map[string]string { return v.Tags }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupIamUserResultOutput{})
}
