// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetIlmTiers(ctx *pulumi.Context, args *GetIlmTiersArgs, opts ...pulumi.InvokeOption) (*GetIlmTiersResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetIlmTiersResult
	err = ctx.InvokePackage("minio:index/getIlmTiers:getIlmTiers", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIlmTiers.
type GetIlmTiersArgs struct {
	Id *string `pulumi:"id"`
}

// A collection of values returned by getIlmTiers.
type GetIlmTiersResult struct {
	Id    string            `pulumi:"id"`
	Tiers []GetIlmTiersTier `pulumi:"tiers"`
}

func GetIlmTiersOutput(ctx *pulumi.Context, args GetIlmTiersOutputArgs, opts ...pulumi.InvokeOption) GetIlmTiersResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getIlmTiers:getIlmTiers", args, GetIlmTiersResultOutput{}, options).(GetIlmTiersResultOutput)
}

// A collection of arguments for invoking getIlmTiers.
type GetIlmTiersOutputArgs struct {
	Id pulumi.StringPtrInput `pulumi:"id"`
}

func (GetIlmTiersOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIlmTiersArgs)(nil)).Elem()
}

// A collection of values returned by getIlmTiers.
type GetIlmTiersResultOutput struct{ *pulumi.OutputState }

func (GetIlmTiersResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIlmTiersResult)(nil)).Elem()
}

func (o GetIlmTiersResultOutput) ToGetIlmTiersResultOutput() GetIlmTiersResultOutput {
	return o
}

func (o GetIlmTiersResultOutput) ToGetIlmTiersResultOutputWithContext(ctx context.Context) GetIlmTiersResultOutput {
	return o
}

func (o GetIlmTiersResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetIlmTiersResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetIlmTiersResultOutput) Tiers() GetIlmTiersTierArrayOutput {
	return o.ApplyT(func(v GetIlmTiersResult) []GetIlmTiersTier { return v.Tiers }).(GetIlmTiersTierArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetIlmTiersResultOutput{})
}
