// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNotifyNsq(ctx *pulumi.Context, args *LookupNotifyNsqArgs, opts ...pulumi.InvokeOption) (*LookupNotifyNsqResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupNotifyNsqResult
	err = ctx.InvokePackage("minio:index/getNotifyNsq:getNotifyNsq", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNotifyNsq.
type LookupNotifyNsqArgs struct {
	Id   *string `pulumi:"id"`
	Name string  `pulumi:"name"`
}

// A collection of values returned by getNotifyNsq.
type LookupNotifyNsqResult struct {
	Comment         string  `pulumi:"comment"`
	Enable          bool    `pulumi:"enable"`
	Id              string  `pulumi:"id"`
	Name            string  `pulumi:"name"`
	NsqdAddress     string  `pulumi:"nsqdAddress"`
	QueueDir        string  `pulumi:"queueDir"`
	QueueLimit      float64 `pulumi:"queueLimit"`
	RestartRequired bool    `pulumi:"restartRequired"`
	Tls             bool    `pulumi:"tls"`
	TlsSkipVerify   bool    `pulumi:"tlsSkipVerify"`
	Topic           string  `pulumi:"topic"`
}

func LookupNotifyNsqOutput(ctx *pulumi.Context, args LookupNotifyNsqOutputArgs, opts ...pulumi.InvokeOption) LookupNotifyNsqResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getNotifyNsq:getNotifyNsq", args, LookupNotifyNsqResultOutput{}, options).(LookupNotifyNsqResultOutput)
}

// A collection of arguments for invoking getNotifyNsq.
type LookupNotifyNsqOutputArgs struct {
	Id   pulumi.StringPtrInput `pulumi:"id"`
	Name pulumi.StringInput    `pulumi:"name"`
}

func (LookupNotifyNsqOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNotifyNsqArgs)(nil)).Elem()
}

// A collection of values returned by getNotifyNsq.
type LookupNotifyNsqResultOutput struct{ *pulumi.OutputState }

func (LookupNotifyNsqResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNotifyNsqResult)(nil)).Elem()
}

func (o LookupNotifyNsqResultOutput) ToLookupNotifyNsqResultOutput() LookupNotifyNsqResultOutput {
	return o
}

func (o LookupNotifyNsqResultOutput) ToLookupNotifyNsqResultOutputWithContext(ctx context.Context) LookupNotifyNsqResultOutput {
	return o
}

func (o LookupNotifyNsqResultOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyNsqResult) string { return v.Comment }).(pulumi.StringOutput)
}

func (o LookupNotifyNsqResultOutput) Enable() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotifyNsqResult) bool { return v.Enable }).(pulumi.BoolOutput)
}

func (o LookupNotifyNsqResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyNsqResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNotifyNsqResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyNsqResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNotifyNsqResultOutput) NsqdAddress() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyNsqResult) string { return v.NsqdAddress }).(pulumi.StringOutput)
}

func (o LookupNotifyNsqResultOutput) QueueDir() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyNsqResult) string { return v.QueueDir }).(pulumi.StringOutput)
}

func (o LookupNotifyNsqResultOutput) QueueLimit() pulumi.Float64Output {
	return o.ApplyT(func(v LookupNotifyNsqResult) float64 { return v.QueueLimit }).(pulumi.Float64Output)
}

func (o LookupNotifyNsqResultOutput) RestartRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotifyNsqResult) bool { return v.RestartRequired }).(pulumi.BoolOutput)
}

func (o LookupNotifyNsqResultOutput) Tls() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotifyNsqResult) bool { return v.Tls }).(pulumi.BoolOutput)
}

func (o LookupNotifyNsqResultOutput) TlsSkipVerify() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotifyNsqResult) bool { return v.TlsSkipVerify }).(pulumi.BoolOutput)
}

func (o LookupNotifyNsqResultOutput) Topic() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyNsqResult) string { return v.Topic }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNotifyNsqResultOutput{})
}
