// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNotifyPostgres(ctx *pulumi.Context, args *LookupNotifyPostgresArgs, opts ...pulumi.InvokeOption) (*LookupNotifyPostgresResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupNotifyPostgresResult
	err = ctx.InvokePackage("minio:index/getNotifyPostgres:getNotifyPostgres", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNotifyPostgres.
type LookupNotifyPostgresArgs struct {
	Id   *string `pulumi:"id"`
	Name string  `pulumi:"name"`
}

// A collection of values returned by getNotifyPostgres.
type LookupNotifyPostgresResult struct {
	Comment            string  `pulumi:"comment"`
	ConnectionString   string  `pulumi:"connectionString"`
	Enable             bool    `pulumi:"enable"`
	Format             string  `pulumi:"format"`
	Id                 string  `pulumi:"id"`
	MaxOpenConnections float64 `pulumi:"maxOpenConnections"`
	Name               string  `pulumi:"name"`
	QueueDir           string  `pulumi:"queueDir"`
	QueueLimit         float64 `pulumi:"queueLimit"`
	RestartRequired    bool    `pulumi:"restartRequired"`
	Table              string  `pulumi:"table"`
}

func LookupNotifyPostgresOutput(ctx *pulumi.Context, args LookupNotifyPostgresOutputArgs, opts ...pulumi.InvokeOption) LookupNotifyPostgresResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getNotifyPostgres:getNotifyPostgres", args, LookupNotifyPostgresResultOutput{}, options).(LookupNotifyPostgresResultOutput)
}

// A collection of arguments for invoking getNotifyPostgres.
type LookupNotifyPostgresOutputArgs struct {
	Id   pulumi.StringPtrInput `pulumi:"id"`
	Name pulumi.StringInput    `pulumi:"name"`
}

func (LookupNotifyPostgresOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNotifyPostgresArgs)(nil)).Elem()
}

// A collection of values returned by getNotifyPostgres.
type LookupNotifyPostgresResultOutput struct{ *pulumi.OutputState }

func (LookupNotifyPostgresResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNotifyPostgresResult)(nil)).Elem()
}

func (o LookupNotifyPostgresResultOutput) ToLookupNotifyPostgresResultOutput() LookupNotifyPostgresResultOutput {
	return o
}

func (o LookupNotifyPostgresResultOutput) ToLookupNotifyPostgresResultOutputWithContext(ctx context.Context) LookupNotifyPostgresResultOutput {
	return o
}

func (o LookupNotifyPostgresResultOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyPostgresResult) string { return v.Comment }).(pulumi.StringOutput)
}

func (o LookupNotifyPostgresResultOutput) ConnectionString() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyPostgresResult) string { return v.ConnectionString }).(pulumi.StringOutput)
}

func (o LookupNotifyPostgresResultOutput) Enable() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotifyPostgresResult) bool { return v.Enable }).(pulumi.BoolOutput)
}

func (o LookupNotifyPostgresResultOutput) Format() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyPostgresResult) string { return v.Format }).(pulumi.StringOutput)
}

func (o LookupNotifyPostgresResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyPostgresResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNotifyPostgresResultOutput) MaxOpenConnections() pulumi.Float64Output {
	return o.ApplyT(func(v LookupNotifyPostgresResult) float64 { return v.MaxOpenConnections }).(pulumi.Float64Output)
}

func (o LookupNotifyPostgresResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyPostgresResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNotifyPostgresResultOutput) QueueDir() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyPostgresResult) string { return v.QueueDir }).(pulumi.StringOutput)
}

func (o LookupNotifyPostgresResultOutput) QueueLimit() pulumi.Float64Output {
	return o.ApplyT(func(v LookupNotifyPostgresResult) float64 { return v.QueueLimit }).(pulumi.Float64Output)
}

func (o LookupNotifyPostgresResultOutput) RestartRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotifyPostgresResult) bool { return v.RestartRequired }).(pulumi.BoolOutput)
}

func (o LookupNotifyPostgresResultOutput) Table() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyPostgresResult) string { return v.Table }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNotifyPostgresResultOutput{})
}
