// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNotifyAmqp(ctx *pulumi.Context, args *LookupNotifyAmqpArgs, opts ...pulumi.InvokeOption) (*LookupNotifyAmqpResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupNotifyAmqpResult
	err = ctx.InvokePackage("minio:index/getNotifyAmqp:getNotifyAmqp", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNotifyAmqp.
type LookupNotifyAmqpArgs struct {
	Id   *string `pulumi:"id"`
	Name string  `pulumi:"name"`
}

// A collection of values returned by getNotifyAmqp.
type LookupNotifyAmqpResult struct {
	AutoDeleted     bool    `pulumi:"autoDeleted"`
	Comment         string  `pulumi:"comment"`
	DeliveryMode    float64 `pulumi:"deliveryMode"`
	Durable         bool    `pulumi:"durable"`
	Enable          bool    `pulumi:"enable"`
	Exchange        string  `pulumi:"exchange"`
	ExchangeType    string  `pulumi:"exchangeType"`
	Id              string  `pulumi:"id"`
	Internal        bool    `pulumi:"internal"`
	Mandatory       bool    `pulumi:"mandatory"`
	Name            string  `pulumi:"name"`
	NoWait          bool    `pulumi:"noWait"`
	QueueDir        string  `pulumi:"queueDir"`
	QueueLimit      float64 `pulumi:"queueLimit"`
	RestartRequired bool    `pulumi:"restartRequired"`
	RoutingKey      string  `pulumi:"routingKey"`
	Url             string  `pulumi:"url"`
}

func LookupNotifyAmqpOutput(ctx *pulumi.Context, args LookupNotifyAmqpOutputArgs, opts ...pulumi.InvokeOption) LookupNotifyAmqpResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getNotifyAmqp:getNotifyAmqp", args, LookupNotifyAmqpResultOutput{}, options).(LookupNotifyAmqpResultOutput)
}

// A collection of arguments for invoking getNotifyAmqp.
type LookupNotifyAmqpOutputArgs struct {
	Id   pulumi.StringPtrInput `pulumi:"id"`
	Name pulumi.StringInput    `pulumi:"name"`
}

func (LookupNotifyAmqpOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNotifyAmqpArgs)(nil)).Elem()
}

// A collection of values returned by getNotifyAmqp.
type LookupNotifyAmqpResultOutput struct{ *pulumi.OutputState }

func (LookupNotifyAmqpResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNotifyAmqpResult)(nil)).Elem()
}

func (o LookupNotifyAmqpResultOutput) ToLookupNotifyAmqpResultOutput() LookupNotifyAmqpResultOutput {
	return o
}

func (o LookupNotifyAmqpResultOutput) ToLookupNotifyAmqpResultOutputWithContext(ctx context.Context) LookupNotifyAmqpResultOutput {
	return o
}

func (o LookupNotifyAmqpResultOutput) AutoDeleted() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotifyAmqpResult) bool { return v.AutoDeleted }).(pulumi.BoolOutput)
}

func (o LookupNotifyAmqpResultOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyAmqpResult) string { return v.Comment }).(pulumi.StringOutput)
}

func (o LookupNotifyAmqpResultOutput) DeliveryMode() pulumi.Float64Output {
	return o.ApplyT(func(v LookupNotifyAmqpResult) float64 { return v.DeliveryMode }).(pulumi.Float64Output)
}

func (o LookupNotifyAmqpResultOutput) Durable() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotifyAmqpResult) bool { return v.Durable }).(pulumi.BoolOutput)
}

func (o LookupNotifyAmqpResultOutput) Enable() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotifyAmqpResult) bool { return v.Enable }).(pulumi.BoolOutput)
}

func (o LookupNotifyAmqpResultOutput) Exchange() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyAmqpResult) string { return v.Exchange }).(pulumi.StringOutput)
}

func (o LookupNotifyAmqpResultOutput) ExchangeType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyAmqpResult) string { return v.ExchangeType }).(pulumi.StringOutput)
}

func (o LookupNotifyAmqpResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyAmqpResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNotifyAmqpResultOutput) Internal() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotifyAmqpResult) bool { return v.Internal }).(pulumi.BoolOutput)
}

func (o LookupNotifyAmqpResultOutput) Mandatory() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotifyAmqpResult) bool { return v.Mandatory }).(pulumi.BoolOutput)
}

func (o LookupNotifyAmqpResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyAmqpResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNotifyAmqpResultOutput) NoWait() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotifyAmqpResult) bool { return v.NoWait }).(pulumi.BoolOutput)
}

func (o LookupNotifyAmqpResultOutput) QueueDir() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyAmqpResult) string { return v.QueueDir }).(pulumi.StringOutput)
}

func (o LookupNotifyAmqpResultOutput) QueueLimit() pulumi.Float64Output {
	return o.ApplyT(func(v LookupNotifyAmqpResult) float64 { return v.QueueLimit }).(pulumi.Float64Output)
}

func (o LookupNotifyAmqpResultOutput) RestartRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNotifyAmqpResult) bool { return v.RestartRequired }).(pulumi.BoolOutput)
}

func (o LookupNotifyAmqpResultOutput) RoutingKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyAmqpResult) string { return v.RoutingKey }).(pulumi.StringOutput)
}

func (o LookupNotifyAmqpResultOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNotifyAmqpResult) string { return v.Url }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNotifyAmqpResultOutput{})
}
