// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetPrometheusScrapeConfig(ctx *pulumi.Context, args *GetPrometheusScrapeConfigArgs, opts ...pulumi.InvokeOption) (*GetPrometheusScrapeConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetPrometheusScrapeConfigResult
	err = ctx.InvokePackage("minio:index/getPrometheusScrapeConfig:getPrometheusScrapeConfig", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPrometheusScrapeConfig.
type GetPrometheusScrapeConfigArgs struct {
	Alias          *string `pulumi:"alias"`
	BearerToken    *string `pulumi:"bearerToken"`
	Id             *string `pulumi:"id"`
	MetricType     string  `pulumi:"metricType"`
	MetricsVersion *string `pulumi:"metricsVersion"`
}

// A collection of values returned by getPrometheusScrapeConfig.
type GetPrometheusScrapeConfigResult struct {
	Alias          *string `pulumi:"alias"`
	BearerToken    *string `pulumi:"bearerToken"`
	Id             string  `pulumi:"id"`
	MetricType     string  `pulumi:"metricType"`
	MetricsPath    string  `pulumi:"metricsPath"`
	MetricsVersion *string `pulumi:"metricsVersion"`
	ScrapeConfig   string  `pulumi:"scrapeConfig"`
}

func GetPrometheusScrapeConfigOutput(ctx *pulumi.Context, args GetPrometheusScrapeConfigOutputArgs, opts ...pulumi.InvokeOption) GetPrometheusScrapeConfigResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getPrometheusScrapeConfig:getPrometheusScrapeConfig", args, GetPrometheusScrapeConfigResultOutput{}, options).(GetPrometheusScrapeConfigResultOutput)
}

// A collection of arguments for invoking getPrometheusScrapeConfig.
type GetPrometheusScrapeConfigOutputArgs struct {
	Alias          pulumi.StringPtrInput `pulumi:"alias"`
	BearerToken    pulumi.StringPtrInput `pulumi:"bearerToken"`
	Id             pulumi.StringPtrInput `pulumi:"id"`
	MetricType     pulumi.StringInput    `pulumi:"metricType"`
	MetricsVersion pulumi.StringPtrInput `pulumi:"metricsVersion"`
}

func (GetPrometheusScrapeConfigOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrometheusScrapeConfigArgs)(nil)).Elem()
}

// A collection of values returned by getPrometheusScrapeConfig.
type GetPrometheusScrapeConfigResultOutput struct{ *pulumi.OutputState }

func (GetPrometheusScrapeConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPrometheusScrapeConfigResult)(nil)).Elem()
}

func (o GetPrometheusScrapeConfigResultOutput) ToGetPrometheusScrapeConfigResultOutput() GetPrometheusScrapeConfigResultOutput {
	return o
}

func (o GetPrometheusScrapeConfigResultOutput) ToGetPrometheusScrapeConfigResultOutputWithContext(ctx context.Context) GetPrometheusScrapeConfigResultOutput {
	return o
}

func (o GetPrometheusScrapeConfigResultOutput) Alias() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPrometheusScrapeConfigResult) *string { return v.Alias }).(pulumi.StringPtrOutput)
}

func (o GetPrometheusScrapeConfigResultOutput) BearerToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPrometheusScrapeConfigResult) *string { return v.BearerToken }).(pulumi.StringPtrOutput)
}

func (o GetPrometheusScrapeConfigResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrometheusScrapeConfigResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetPrometheusScrapeConfigResultOutput) MetricType() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrometheusScrapeConfigResult) string { return v.MetricType }).(pulumi.StringOutput)
}

func (o GetPrometheusScrapeConfigResultOutput) MetricsPath() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrometheusScrapeConfigResult) string { return v.MetricsPath }).(pulumi.StringOutput)
}

func (o GetPrometheusScrapeConfigResultOutput) MetricsVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPrometheusScrapeConfigResult) *string { return v.MetricsVersion }).(pulumi.StringPtrOutput)
}

func (o GetPrometheusScrapeConfigResultOutput) ScrapeConfig() pulumi.StringOutput {
	return o.ApplyT(func(v GetPrometheusScrapeConfigResult) string { return v.ScrapeConfig }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPrometheusScrapeConfigResultOutput{})
}
