// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetPoolRebalanceStatus(ctx *pulumi.Context, args *GetPoolRebalanceStatusArgs, opts ...pulumi.InvokeOption) (*GetPoolRebalanceStatusResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetPoolRebalanceStatusResult
	err = ctx.InvokePackage("minio:index/getPoolRebalanceStatus:getPoolRebalanceStatus", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPoolRebalanceStatus.
type GetPoolRebalanceStatusArgs struct {
	Id *string `pulumi:"id"`
}

// A collection of values returned by getPoolRebalanceStatus.
type GetPoolRebalanceStatusResult struct {
	Id     string                       `pulumi:"id"`
	Pools  []GetPoolRebalanceStatusPool `pulumi:"pools"`
	Status string                       `pulumi:"status"`
}

func GetPoolRebalanceStatusOutput(ctx *pulumi.Context, args GetPoolRebalanceStatusOutputArgs, opts ...pulumi.InvokeOption) GetPoolRebalanceStatusResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getPoolRebalanceStatus:getPoolRebalanceStatus", args, GetPoolRebalanceStatusResultOutput{}, options).(GetPoolRebalanceStatusResultOutput)
}

// A collection of arguments for invoking getPoolRebalanceStatus.
type GetPoolRebalanceStatusOutputArgs struct {
	Id pulumi.StringPtrInput `pulumi:"id"`
}

func (GetPoolRebalanceStatusOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPoolRebalanceStatusArgs)(nil)).Elem()
}

// A collection of values returned by getPoolRebalanceStatus.
type GetPoolRebalanceStatusResultOutput struct{ *pulumi.OutputState }

func (GetPoolRebalanceStatusResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPoolRebalanceStatusResult)(nil)).Elem()
}

func (o GetPoolRebalanceStatusResultOutput) ToGetPoolRebalanceStatusResultOutput() GetPoolRebalanceStatusResultOutput {
	return o
}

func (o GetPoolRebalanceStatusResultOutput) ToGetPoolRebalanceStatusResultOutputWithContext(ctx context.Context) GetPoolRebalanceStatusResultOutput {
	return o
}

func (o GetPoolRebalanceStatusResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPoolRebalanceStatusResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetPoolRebalanceStatusResultOutput) Pools() GetPoolRebalanceStatusPoolArrayOutput {
	return o.ApplyT(func(v GetPoolRebalanceStatusResult) []GetPoolRebalanceStatusPool { return v.Pools }).(GetPoolRebalanceStatusPoolArrayOutput)
}

func (o GetPoolRebalanceStatusResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetPoolRebalanceStatusResult) string { return v.Status }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPoolRebalanceStatusResultOutput{})
}
