// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupS3BucketPolicy(ctx *pulumi.Context, args *LookupS3BucketPolicyArgs, opts ...pulumi.InvokeOption) (*LookupS3BucketPolicyResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupS3BucketPolicyResult
	err = ctx.InvokePackage("minio:index/getS3BucketPolicy:getS3BucketPolicy", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getS3BucketPolicy.
type LookupS3BucketPolicyArgs struct {
	Bucket string  `pulumi:"bucket"`
	Id     *string `pulumi:"id"`
}

// A collection of values returned by getS3BucketPolicy.
type LookupS3BucketPolicyResult struct {
	Bucket string `pulumi:"bucket"`
	Id     string `pulumi:"id"`
	Policy string `pulumi:"policy"`
}

func LookupS3BucketPolicyOutput(ctx *pulumi.Context, args LookupS3BucketPolicyOutputArgs, opts ...pulumi.InvokeOption) LookupS3BucketPolicyResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getS3BucketPolicy:getS3BucketPolicy", args, LookupS3BucketPolicyResultOutput{}, options).(LookupS3BucketPolicyResultOutput)
}

// A collection of arguments for invoking getS3BucketPolicy.
type LookupS3BucketPolicyOutputArgs struct {
	Bucket pulumi.StringInput    `pulumi:"bucket"`
	Id     pulumi.StringPtrInput `pulumi:"id"`
}

func (LookupS3BucketPolicyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupS3BucketPolicyArgs)(nil)).Elem()
}

// A collection of values returned by getS3BucketPolicy.
type LookupS3BucketPolicyResultOutput struct{ *pulumi.OutputState }

func (LookupS3BucketPolicyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupS3BucketPolicyResult)(nil)).Elem()
}

func (o LookupS3BucketPolicyResultOutput) ToLookupS3BucketPolicyResultOutput() LookupS3BucketPolicyResultOutput {
	return o
}

func (o LookupS3BucketPolicyResultOutput) ToLookupS3BucketPolicyResultOutputWithContext(ctx context.Context) LookupS3BucketPolicyResultOutput {
	return o
}

func (o LookupS3BucketPolicyResultOutput) Bucket() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3BucketPolicyResult) string { return v.Bucket }).(pulumi.StringOutput)
}

func (o LookupS3BucketPolicyResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3BucketPolicyResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupS3BucketPolicyResultOutput) Policy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3BucketPolicyResult) string { return v.Policy }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupS3BucketPolicyResultOutput{})
}
