// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetServerInfo(ctx *pulumi.Context, args *GetServerInfoArgs, opts ...pulumi.InvokeOption) (*GetServerInfoResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetServerInfoResult
	err = ctx.InvokePackage("minio:index/getServerInfo:getServerInfo", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServerInfo.
type GetServerInfoArgs struct {
	Id *string `pulumi:"id"`
}

// A collection of values returned by getServerInfo.
type GetServerInfoResult struct {
	Commit       string                `pulumi:"commit"`
	DeploymentId string                `pulumi:"deploymentId"`
	Edition      string                `pulumi:"edition"`
	Id           string                `pulumi:"id"`
	Region       string                `pulumi:"region"`
	Servers      []GetServerInfoServer `pulumi:"servers"`
	Sqsarns      []string              `pulumi:"sqsarns"`
	Version      string                `pulumi:"version"`
}

func GetServerInfoOutput(ctx *pulumi.Context, args GetServerInfoOutputArgs, opts ...pulumi.InvokeOption) GetServerInfoResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getServerInfo:getServerInfo", args, GetServerInfoResultOutput{}, options).(GetServerInfoResultOutput)
}

// A collection of arguments for invoking getServerInfo.
type GetServerInfoOutputArgs struct {
	Id pulumi.StringPtrInput `pulumi:"id"`
}

func (GetServerInfoOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServerInfoArgs)(nil)).Elem()
}

// A collection of values returned by getServerInfo.
type GetServerInfoResultOutput struct{ *pulumi.OutputState }

func (GetServerInfoResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServerInfoResult)(nil)).Elem()
}

func (o GetServerInfoResultOutput) ToGetServerInfoResultOutput() GetServerInfoResultOutput {
	return o
}

func (o GetServerInfoResultOutput) ToGetServerInfoResultOutputWithContext(ctx context.Context) GetServerInfoResultOutput {
	return o
}

func (o GetServerInfoResultOutput) Commit() pulumi.StringOutput {
	return o.ApplyT(func(v GetServerInfoResult) string { return v.Commit }).(pulumi.StringOutput)
}

func (o GetServerInfoResultOutput) DeploymentId() pulumi.StringOutput {
	return o.ApplyT(func(v GetServerInfoResult) string { return v.DeploymentId }).(pulumi.StringOutput)
}

func (o GetServerInfoResultOutput) Edition() pulumi.StringOutput {
	return o.ApplyT(func(v GetServerInfoResult) string { return v.Edition }).(pulumi.StringOutput)
}

func (o GetServerInfoResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetServerInfoResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetServerInfoResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v GetServerInfoResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o GetServerInfoResultOutput) Servers() GetServerInfoServerArrayOutput {
	return o.ApplyT(func(v GetServerInfoResult) []GetServerInfoServer { return v.Servers }).(GetServerInfoServerArrayOutput)
}

func (o GetServerInfoResultOutput) Sqsarns() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetServerInfoResult) []string { return v.Sqsarns }).(pulumi.StringArrayOutput)
}

func (o GetServerInfoResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v GetServerInfoResult) string { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetServerInfoResultOutput{})
}
