// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupS3BucketVersioning(ctx *pulumi.Context, args *LookupS3BucketVersioningArgs, opts ...pulumi.InvokeOption) (*LookupS3BucketVersioningResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupS3BucketVersioningResult
	err = ctx.InvokePackage("minio:index/getS3BucketVersioning:getS3BucketVersioning", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getS3BucketVersioning.
type LookupS3BucketVersioningArgs struct {
	Bucket string  `pulumi:"bucket"`
	Id     *string `pulumi:"id"`
}

// A collection of values returned by getS3BucketVersioning.
type LookupS3BucketVersioningResult struct {
	Bucket    string `pulumi:"bucket"`
	Enabled   bool   `pulumi:"enabled"`
	Id        string `pulumi:"id"`
	Suspended bool   `pulumi:"suspended"`
}

func LookupS3BucketVersioningOutput(ctx *pulumi.Context, args LookupS3BucketVersioningOutputArgs, opts ...pulumi.InvokeOption) LookupS3BucketVersioningResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getS3BucketVersioning:getS3BucketVersioning", args, LookupS3BucketVersioningResultOutput{}, options).(LookupS3BucketVersioningResultOutput)
}

// A collection of arguments for invoking getS3BucketVersioning.
type LookupS3BucketVersioningOutputArgs struct {
	Bucket pulumi.StringInput    `pulumi:"bucket"`
	Id     pulumi.StringPtrInput `pulumi:"id"`
}

func (LookupS3BucketVersioningOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupS3BucketVersioningArgs)(nil)).Elem()
}

// A collection of values returned by getS3BucketVersioning.
type LookupS3BucketVersioningResultOutput struct{ *pulumi.OutputState }

func (LookupS3BucketVersioningResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupS3BucketVersioningResult)(nil)).Elem()
}

func (o LookupS3BucketVersioningResultOutput) ToLookupS3BucketVersioningResultOutput() LookupS3BucketVersioningResultOutput {
	return o
}

func (o LookupS3BucketVersioningResultOutput) ToLookupS3BucketVersioningResultOutputWithContext(ctx context.Context) LookupS3BucketVersioningResultOutput {
	return o
}

func (o LookupS3BucketVersioningResultOutput) Bucket() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3BucketVersioningResult) string { return v.Bucket }).(pulumi.StringOutput)
}

func (o LookupS3BucketVersioningResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupS3BucketVersioningResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupS3BucketVersioningResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3BucketVersioningResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupS3BucketVersioningResultOutput) Suspended() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupS3BucketVersioningResult) bool { return v.Suspended }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupS3BucketVersioningResultOutput{})
}
