// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupS3BucketRetention(ctx *pulumi.Context, args *LookupS3BucketRetentionArgs, opts ...pulumi.InvokeOption) (*LookupS3BucketRetentionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupS3BucketRetentionResult
	err = ctx.InvokePackage("minio:index/getS3BucketRetention:getS3BucketRetention", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getS3BucketRetention.
type LookupS3BucketRetentionArgs struct {
	Bucket string  `pulumi:"bucket"`
	Id     *string `pulumi:"id"`
}

// A collection of values returned by getS3BucketRetention.
type LookupS3BucketRetentionResult struct {
	Bucket         string  `pulumi:"bucket"`
	Id             string  `pulumi:"id"`
	Mode           string  `pulumi:"mode"`
	Unit           string  `pulumi:"unit"`
	ValidityPeriod float64 `pulumi:"validityPeriod"`
}

func LookupS3BucketRetentionOutput(ctx *pulumi.Context, args LookupS3BucketRetentionOutputArgs, opts ...pulumi.InvokeOption) LookupS3BucketRetentionResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getS3BucketRetention:getS3BucketRetention", args, LookupS3BucketRetentionResultOutput{}, options).(LookupS3BucketRetentionResultOutput)
}

// A collection of arguments for invoking getS3BucketRetention.
type LookupS3BucketRetentionOutputArgs struct {
	Bucket pulumi.StringInput    `pulumi:"bucket"`
	Id     pulumi.StringPtrInput `pulumi:"id"`
}

func (LookupS3BucketRetentionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupS3BucketRetentionArgs)(nil)).Elem()
}

// A collection of values returned by getS3BucketRetention.
type LookupS3BucketRetentionResultOutput struct{ *pulumi.OutputState }

func (LookupS3BucketRetentionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupS3BucketRetentionResult)(nil)).Elem()
}

func (o LookupS3BucketRetentionResultOutput) ToLookupS3BucketRetentionResultOutput() LookupS3BucketRetentionResultOutput {
	return o
}

func (o LookupS3BucketRetentionResultOutput) ToLookupS3BucketRetentionResultOutputWithContext(ctx context.Context) LookupS3BucketRetentionResultOutput {
	return o
}

func (o LookupS3BucketRetentionResultOutput) Bucket() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3BucketRetentionResult) string { return v.Bucket }).(pulumi.StringOutput)
}

func (o LookupS3BucketRetentionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3BucketRetentionResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupS3BucketRetentionResultOutput) Mode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3BucketRetentionResult) string { return v.Mode }).(pulumi.StringOutput)
}

func (o LookupS3BucketRetentionResultOutput) Unit() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3BucketRetentionResult) string { return v.Unit }).(pulumi.StringOutput)
}

func (o LookupS3BucketRetentionResultOutput) ValidityPeriod() pulumi.Float64Output {
	return o.ApplyT(func(v LookupS3BucketRetentionResult) float64 { return v.ValidityPeriod }).(pulumi.Float64Output)
}

func init() {
	pulumi.RegisterOutputType(LookupS3BucketRetentionResultOutput{})
}
