// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetS3BucketReplicationMetrics(ctx *pulumi.Context, args *GetS3BucketReplicationMetricsArgs, opts ...pulumi.InvokeOption) (*GetS3BucketReplicationMetricsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetS3BucketReplicationMetricsResult
	err = ctx.InvokePackage("minio:index/getS3BucketReplicationMetrics:getS3BucketReplicationMetrics", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getS3BucketReplicationMetrics.
type GetS3BucketReplicationMetricsArgs struct {
	Bucket string  `pulumi:"bucket"`
	Id     *string `pulumi:"id"`
}

// A collection of values returned by getS3BucketReplicationMetrics.
type GetS3BucketReplicationMetricsResult struct {
	Bucket          string `pulumi:"bucket"`
	FailedCount     string `pulumi:"failedCount"`
	FailedSize      string `pulumi:"failedSize"`
	Id              string `pulumi:"id"`
	PendingCount    string `pulumi:"pendingCount"`
	PendingSize     string `pulumi:"pendingSize"`
	QueuedCount     string `pulumi:"queuedCount"`
	QueuedSize      string `pulumi:"queuedSize"`
	ReplicaCount    string `pulumi:"replicaCount"`
	ReplicaSize     string `pulumi:"replicaSize"`
	ReplicatedCount string `pulumi:"replicatedCount"`
	ReplicatedSize  string `pulumi:"replicatedSize"`
}

func GetS3BucketReplicationMetricsOutput(ctx *pulumi.Context, args GetS3BucketReplicationMetricsOutputArgs, opts ...pulumi.InvokeOption) GetS3BucketReplicationMetricsResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getS3BucketReplicationMetrics:getS3BucketReplicationMetrics", args, GetS3BucketReplicationMetricsResultOutput{}, options).(GetS3BucketReplicationMetricsResultOutput)
}

// A collection of arguments for invoking getS3BucketReplicationMetrics.
type GetS3BucketReplicationMetricsOutputArgs struct {
	Bucket pulumi.StringInput    `pulumi:"bucket"`
	Id     pulumi.StringPtrInput `pulumi:"id"`
}

func (GetS3BucketReplicationMetricsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetS3BucketReplicationMetricsArgs)(nil)).Elem()
}

// A collection of values returned by getS3BucketReplicationMetrics.
type GetS3BucketReplicationMetricsResultOutput struct{ *pulumi.OutputState }

func (GetS3BucketReplicationMetricsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetS3BucketReplicationMetricsResult)(nil)).Elem()
}

func (o GetS3BucketReplicationMetricsResultOutput) ToGetS3BucketReplicationMetricsResultOutput() GetS3BucketReplicationMetricsResultOutput {
	return o
}

func (o GetS3BucketReplicationMetricsResultOutput) ToGetS3BucketReplicationMetricsResultOutputWithContext(ctx context.Context) GetS3BucketReplicationMetricsResultOutput {
	return o
}

func (o GetS3BucketReplicationMetricsResultOutput) Bucket() pulumi.StringOutput {
	return o.ApplyT(func(v GetS3BucketReplicationMetricsResult) string { return v.Bucket }).(pulumi.StringOutput)
}

func (o GetS3BucketReplicationMetricsResultOutput) FailedCount() pulumi.StringOutput {
	return o.ApplyT(func(v GetS3BucketReplicationMetricsResult) string { return v.FailedCount }).(pulumi.StringOutput)
}

func (o GetS3BucketReplicationMetricsResultOutput) FailedSize() pulumi.StringOutput {
	return o.ApplyT(func(v GetS3BucketReplicationMetricsResult) string { return v.FailedSize }).(pulumi.StringOutput)
}

func (o GetS3BucketReplicationMetricsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetS3BucketReplicationMetricsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetS3BucketReplicationMetricsResultOutput) PendingCount() pulumi.StringOutput {
	return o.ApplyT(func(v GetS3BucketReplicationMetricsResult) string { return v.PendingCount }).(pulumi.StringOutput)
}

func (o GetS3BucketReplicationMetricsResultOutput) PendingSize() pulumi.StringOutput {
	return o.ApplyT(func(v GetS3BucketReplicationMetricsResult) string { return v.PendingSize }).(pulumi.StringOutput)
}

func (o GetS3BucketReplicationMetricsResultOutput) QueuedCount() pulumi.StringOutput {
	return o.ApplyT(func(v GetS3BucketReplicationMetricsResult) string { return v.QueuedCount }).(pulumi.StringOutput)
}

func (o GetS3BucketReplicationMetricsResultOutput) QueuedSize() pulumi.StringOutput {
	return o.ApplyT(func(v GetS3BucketReplicationMetricsResult) string { return v.QueuedSize }).(pulumi.StringOutput)
}

func (o GetS3BucketReplicationMetricsResultOutput) ReplicaCount() pulumi.StringOutput {
	return o.ApplyT(func(v GetS3BucketReplicationMetricsResult) string { return v.ReplicaCount }).(pulumi.StringOutput)
}

func (o GetS3BucketReplicationMetricsResultOutput) ReplicaSize() pulumi.StringOutput {
	return o.ApplyT(func(v GetS3BucketReplicationMetricsResult) string { return v.ReplicaSize }).(pulumi.StringOutput)
}

func (o GetS3BucketReplicationMetricsResultOutput) ReplicatedCount() pulumi.StringOutput {
	return o.ApplyT(func(v GetS3BucketReplicationMetricsResult) string { return v.ReplicatedCount }).(pulumi.StringOutput)
}

func (o GetS3BucketReplicationMetricsResultOutput) ReplicatedSize() pulumi.StringOutput {
	return o.ApplyT(func(v GetS3BucketReplicationMetricsResult) string { return v.ReplicatedSize }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetS3BucketReplicationMetricsResultOutput{})
}
