// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetStorageInfo(ctx *pulumi.Context, args *GetStorageInfoArgs, opts ...pulumi.InvokeOption) (*GetStorageInfoResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetStorageInfoResult
	err = ctx.InvokePackage("minio:index/getStorageInfo:getStorageInfo", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getStorageInfo.
type GetStorageInfoArgs struct {
	Id *string `pulumi:"id"`
}

// A collection of values returned by getStorageInfo.
type GetStorageInfoResult struct {
	AvailableSpace string               `pulumi:"availableSpace"`
	DiskCount      float64              `pulumi:"diskCount"`
	Disks          []GetStorageInfoDisk `pulumi:"disks"`
	Id             string               `pulumi:"id"`
	OfflineDisks   float64              `pulumi:"offlineDisks"`
	OnlineDisks    float64              `pulumi:"onlineDisks"`
	TotalSpace     string               `pulumi:"totalSpace"`
	UsedSpace      string               `pulumi:"usedSpace"`
}

func GetStorageInfoOutput(ctx *pulumi.Context, args GetStorageInfoOutputArgs, opts ...pulumi.InvokeOption) GetStorageInfoResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getStorageInfo:getStorageInfo", args, GetStorageInfoResultOutput{}, options).(GetStorageInfoResultOutput)
}

// A collection of arguments for invoking getStorageInfo.
type GetStorageInfoOutputArgs struct {
	Id pulumi.StringPtrInput `pulumi:"id"`
}

func (GetStorageInfoOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetStorageInfoArgs)(nil)).Elem()
}

// A collection of values returned by getStorageInfo.
type GetStorageInfoResultOutput struct{ *pulumi.OutputState }

func (GetStorageInfoResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetStorageInfoResult)(nil)).Elem()
}

func (o GetStorageInfoResultOutput) ToGetStorageInfoResultOutput() GetStorageInfoResultOutput {
	return o
}

func (o GetStorageInfoResultOutput) ToGetStorageInfoResultOutputWithContext(ctx context.Context) GetStorageInfoResultOutput {
	return o
}

func (o GetStorageInfoResultOutput) AvailableSpace() pulumi.StringOutput {
	return o.ApplyT(func(v GetStorageInfoResult) string { return v.AvailableSpace }).(pulumi.StringOutput)
}

func (o GetStorageInfoResultOutput) DiskCount() pulumi.Float64Output {
	return o.ApplyT(func(v GetStorageInfoResult) float64 { return v.DiskCount }).(pulumi.Float64Output)
}

func (o GetStorageInfoResultOutput) Disks() GetStorageInfoDiskArrayOutput {
	return o.ApplyT(func(v GetStorageInfoResult) []GetStorageInfoDisk { return v.Disks }).(GetStorageInfoDiskArrayOutput)
}

func (o GetStorageInfoResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetStorageInfoResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetStorageInfoResultOutput) OfflineDisks() pulumi.Float64Output {
	return o.ApplyT(func(v GetStorageInfoResult) float64 { return v.OfflineDisks }).(pulumi.Float64Output)
}

func (o GetStorageInfoResultOutput) OnlineDisks() pulumi.Float64Output {
	return o.ApplyT(func(v GetStorageInfoResult) float64 { return v.OnlineDisks }).(pulumi.Float64Output)
}

func (o GetStorageInfoResultOutput) TotalSpace() pulumi.StringOutput {
	return o.ApplyT(func(v GetStorageInfoResult) string { return v.TotalSpace }).(pulumi.StringOutput)
}

func (o GetStorageInfoResultOutput) UsedSpace() pulumi.StringOutput {
	return o.ApplyT(func(v GetStorageInfoResult) string { return v.UsedSpace }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetStorageInfoResultOutput{})
}
