// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupS3Bucket(ctx *pulumi.Context, args *LookupS3BucketArgs, opts ...pulumi.InvokeOption) (*LookupS3BucketResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupS3BucketResult
	err = ctx.InvokePackage("minio:index/getS3Bucket:getS3Bucket", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getS3Bucket.
type LookupS3BucketArgs struct {
	Bucket string  `pulumi:"bucket"`
	Id     *string `pulumi:"id"`
}

// A collection of values returned by getS3Bucket.
type LookupS3BucketResult struct {
	Bucket            string `pulumi:"bucket"`
	Id                string `pulumi:"id"`
	ObjectLockEnabled bool   `pulumi:"objectLockEnabled"`
	Policy            string `pulumi:"policy"`
	Region            string `pulumi:"region"`
	VersioningEnabled bool   `pulumi:"versioningEnabled"`
}

func LookupS3BucketOutput(ctx *pulumi.Context, args LookupS3BucketOutputArgs, opts ...pulumi.InvokeOption) LookupS3BucketResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getS3Bucket:getS3Bucket", args, LookupS3BucketResultOutput{}, options).(LookupS3BucketResultOutput)
}

// A collection of arguments for invoking getS3Bucket.
type LookupS3BucketOutputArgs struct {
	Bucket pulumi.StringInput    `pulumi:"bucket"`
	Id     pulumi.StringPtrInput `pulumi:"id"`
}

func (LookupS3BucketOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupS3BucketArgs)(nil)).Elem()
}

// A collection of values returned by getS3Bucket.
type LookupS3BucketResultOutput struct{ *pulumi.OutputState }

func (LookupS3BucketResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupS3BucketResult)(nil)).Elem()
}

func (o LookupS3BucketResultOutput) ToLookupS3BucketResultOutput() LookupS3BucketResultOutput {
	return o
}

func (o LookupS3BucketResultOutput) ToLookupS3BucketResultOutputWithContext(ctx context.Context) LookupS3BucketResultOutput {
	return o
}

func (o LookupS3BucketResultOutput) Bucket() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3BucketResult) string { return v.Bucket }).(pulumi.StringOutput)
}

func (o LookupS3BucketResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3BucketResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupS3BucketResultOutput) ObjectLockEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupS3BucketResult) bool { return v.ObjectLockEnabled }).(pulumi.BoolOutput)
}

func (o LookupS3BucketResultOutput) Policy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3BucketResult) string { return v.Policy }).(pulumi.StringOutput)
}

func (o LookupS3BucketResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3BucketResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o LookupS3BucketResultOutput) VersioningEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupS3BucketResult) bool { return v.VersioningEnabled }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupS3BucketResultOutput{})
}
