// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupS3BucketObjectLockConfiguration(ctx *pulumi.Context, args *LookupS3BucketObjectLockConfigurationArgs, opts ...pulumi.InvokeOption) (*LookupS3BucketObjectLockConfigurationResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupS3BucketObjectLockConfigurationResult
	err = ctx.InvokePackage("minio:index/getS3BucketObjectLockConfiguration:getS3BucketObjectLockConfiguration", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getS3BucketObjectLockConfiguration.
type LookupS3BucketObjectLockConfigurationArgs struct {
	Bucket string  `pulumi:"bucket"`
	Id     *string `pulumi:"id"`
}

// A collection of values returned by getS3BucketObjectLockConfiguration.
type LookupS3BucketObjectLockConfigurationResult struct {
	Bucket            string                                   `pulumi:"bucket"`
	Id                string                                   `pulumi:"id"`
	ObjectLockEnabled string                                   `pulumi:"objectLockEnabled"`
	Rules             []GetS3BucketObjectLockConfigurationRule `pulumi:"rules"`
}

func LookupS3BucketObjectLockConfigurationOutput(ctx *pulumi.Context, args LookupS3BucketObjectLockConfigurationOutputArgs, opts ...pulumi.InvokeOption) LookupS3BucketObjectLockConfigurationResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("minio:index/getS3BucketObjectLockConfiguration:getS3BucketObjectLockConfiguration", args, LookupS3BucketObjectLockConfigurationResultOutput{}, options).(LookupS3BucketObjectLockConfigurationResultOutput)
}

// A collection of arguments for invoking getS3BucketObjectLockConfiguration.
type LookupS3BucketObjectLockConfigurationOutputArgs struct {
	Bucket pulumi.StringInput    `pulumi:"bucket"`
	Id     pulumi.StringPtrInput `pulumi:"id"`
}

func (LookupS3BucketObjectLockConfigurationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupS3BucketObjectLockConfigurationArgs)(nil)).Elem()
}

// A collection of values returned by getS3BucketObjectLockConfiguration.
type LookupS3BucketObjectLockConfigurationResultOutput struct{ *pulumi.OutputState }

func (LookupS3BucketObjectLockConfigurationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupS3BucketObjectLockConfigurationResult)(nil)).Elem()
}

func (o LookupS3BucketObjectLockConfigurationResultOutput) ToLookupS3BucketObjectLockConfigurationResultOutput() LookupS3BucketObjectLockConfigurationResultOutput {
	return o
}

func (o LookupS3BucketObjectLockConfigurationResultOutput) ToLookupS3BucketObjectLockConfigurationResultOutputWithContext(ctx context.Context) LookupS3BucketObjectLockConfigurationResultOutput {
	return o
}

func (o LookupS3BucketObjectLockConfigurationResultOutput) Bucket() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3BucketObjectLockConfigurationResult) string { return v.Bucket }).(pulumi.StringOutput)
}

func (o LookupS3BucketObjectLockConfigurationResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3BucketObjectLockConfigurationResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupS3BucketObjectLockConfigurationResultOutput) ObjectLockEnabled() pulumi.StringOutput {
	return o.ApplyT(func(v LookupS3BucketObjectLockConfigurationResult) string { return v.ObjectLockEnabled }).(pulumi.StringOutput)
}

func (o LookupS3BucketObjectLockConfigurationResultOutput) Rules() GetS3BucketObjectLockConfigurationRuleArrayOutput {
	return o.ApplyT(func(v LookupS3BucketObjectLockConfigurationResult) []GetS3BucketObjectLockConfigurationRule {
		return v.Rules
	}).(GetS3BucketObjectLockConfigurationRuleArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupS3BucketObjectLockConfigurationResultOutput{})
}
