// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type IamGroupPolicy struct {
	pulumi.CustomResourceState

	// Name of group the policy belongs to.
	Group            pulumi.StringOutput `pulumi:"group"`
	IamGroupPolicyId pulumi.StringOutput `pulumi:"iamGroupPolicyId"`
	// Name of the policy. If omitted, Terraform will assign a random, unique name.
	Name pulumi.StringOutput `pulumi:"name"`
	// Prefix to the generated policy name. Do not use with <span pulumi-lang-nodejs="`name`" pulumi-lang-dotnet="`Name`" pulumi-lang-go="`name`" pulumi-lang-python="`name`" pulumi-lang-yaml="`name`" pulumi-lang-java="`name`" pulumi-lang-hcl="`name`">`name`</span>.
	NamePrefix pulumi.StringPtrOutput `pulumi:"namePrefix"`
	// Policy JSON string
	Policy pulumi.StringOutput `pulumi:"policy"`
}

// NewIamGroupPolicy registers a new resource with the given unique name, arguments, and options.
func NewIamGroupPolicy(ctx *pulumi.Context,
	name string, args *IamGroupPolicyArgs, opts ...pulumi.ResourceOption) (*IamGroupPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Group == nil {
		return nil, errors.New("invalid value for required argument 'Group'")
	}
	if args.Policy == nil {
		return nil, errors.New("invalid value for required argument 'Policy'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource IamGroupPolicy
	err = ctx.RegisterPackageResource("minio:index/iamGroupPolicy:IamGroupPolicy", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIamGroupPolicy gets an existing IamGroupPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIamGroupPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IamGroupPolicyState, opts ...pulumi.ResourceOption) (*IamGroupPolicy, error) {
	var resource IamGroupPolicy
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/iamGroupPolicy:IamGroupPolicy", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IamGroupPolicy resources.
type iamGroupPolicyState struct {
	// Name of group the policy belongs to.
	Group            *string `pulumi:"group"`
	IamGroupPolicyId *string `pulumi:"iamGroupPolicyId"`
	// Name of the policy. If omitted, Terraform will assign a random, unique name.
	Name *string `pulumi:"name"`
	// Prefix to the generated policy name. Do not use with <span pulumi-lang-nodejs="`name`" pulumi-lang-dotnet="`Name`" pulumi-lang-go="`name`" pulumi-lang-python="`name`" pulumi-lang-yaml="`name`" pulumi-lang-java="`name`" pulumi-lang-hcl="`name`">`name`</span>.
	NamePrefix *string `pulumi:"namePrefix"`
	// Policy JSON string
	Policy *string `pulumi:"policy"`
}

type IamGroupPolicyState struct {
	// Name of group the policy belongs to.
	Group            pulumi.StringPtrInput
	IamGroupPolicyId pulumi.StringPtrInput
	// Name of the policy. If omitted, Terraform will assign a random, unique name.
	Name pulumi.StringPtrInput
	// Prefix to the generated policy name. Do not use with <span pulumi-lang-nodejs="`name`" pulumi-lang-dotnet="`Name`" pulumi-lang-go="`name`" pulumi-lang-python="`name`" pulumi-lang-yaml="`name`" pulumi-lang-java="`name`" pulumi-lang-hcl="`name`">`name`</span>.
	NamePrefix pulumi.StringPtrInput
	// Policy JSON string
	Policy pulumi.StringPtrInput
}

func (IamGroupPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*iamGroupPolicyState)(nil)).Elem()
}

type iamGroupPolicyArgs struct {
	// Name of group the policy belongs to.
	Group            string  `pulumi:"group"`
	IamGroupPolicyId *string `pulumi:"iamGroupPolicyId"`
	// Name of the policy. If omitted, Terraform will assign a random, unique name.
	Name *string `pulumi:"name"`
	// Prefix to the generated policy name. Do not use with <span pulumi-lang-nodejs="`name`" pulumi-lang-dotnet="`Name`" pulumi-lang-go="`name`" pulumi-lang-python="`name`" pulumi-lang-yaml="`name`" pulumi-lang-java="`name`" pulumi-lang-hcl="`name`">`name`</span>.
	NamePrefix *string `pulumi:"namePrefix"`
	// Policy JSON string
	Policy string `pulumi:"policy"`
}

// The set of arguments for constructing a IamGroupPolicy resource.
type IamGroupPolicyArgs struct {
	// Name of group the policy belongs to.
	Group            pulumi.StringInput
	IamGroupPolicyId pulumi.StringPtrInput
	// Name of the policy. If omitted, Terraform will assign a random, unique name.
	Name pulumi.StringPtrInput
	// Prefix to the generated policy name. Do not use with <span pulumi-lang-nodejs="`name`" pulumi-lang-dotnet="`Name`" pulumi-lang-go="`name`" pulumi-lang-python="`name`" pulumi-lang-yaml="`name`" pulumi-lang-java="`name`" pulumi-lang-hcl="`name`">`name`</span>.
	NamePrefix pulumi.StringPtrInput
	// Policy JSON string
	Policy pulumi.StringInput
}

func (IamGroupPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*iamGroupPolicyArgs)(nil)).Elem()
}

type IamGroupPolicyInput interface {
	pulumi.Input

	ToIamGroupPolicyOutput() IamGroupPolicyOutput
	ToIamGroupPolicyOutputWithContext(ctx context.Context) IamGroupPolicyOutput
}

func (*IamGroupPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**IamGroupPolicy)(nil)).Elem()
}

func (i *IamGroupPolicy) ToIamGroupPolicyOutput() IamGroupPolicyOutput {
	return i.ToIamGroupPolicyOutputWithContext(context.Background())
}

func (i *IamGroupPolicy) ToIamGroupPolicyOutputWithContext(ctx context.Context) IamGroupPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IamGroupPolicyOutput)
}

type IamGroupPolicyOutput struct{ *pulumi.OutputState }

func (IamGroupPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IamGroupPolicy)(nil)).Elem()
}

func (o IamGroupPolicyOutput) ToIamGroupPolicyOutput() IamGroupPolicyOutput {
	return o
}

func (o IamGroupPolicyOutput) ToIamGroupPolicyOutputWithContext(ctx context.Context) IamGroupPolicyOutput {
	return o
}

// Name of group the policy belongs to.
func (o IamGroupPolicyOutput) Group() pulumi.StringOutput {
	return o.ApplyT(func(v *IamGroupPolicy) pulumi.StringOutput { return v.Group }).(pulumi.StringOutput)
}

func (o IamGroupPolicyOutput) IamGroupPolicyId() pulumi.StringOutput {
	return o.ApplyT(func(v *IamGroupPolicy) pulumi.StringOutput { return v.IamGroupPolicyId }).(pulumi.StringOutput)
}

// Name of the policy. If omitted, Terraform will assign a random, unique name.
func (o IamGroupPolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *IamGroupPolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Prefix to the generated policy name. Do not use with <span pulumi-lang-nodejs="`name`" pulumi-lang-dotnet="`Name`" pulumi-lang-go="`name`" pulumi-lang-python="`name`" pulumi-lang-yaml="`name`" pulumi-lang-java="`name`" pulumi-lang-hcl="`name`">`name`</span>.
func (o IamGroupPolicyOutput) NamePrefix() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamGroupPolicy) pulumi.StringPtrOutput { return v.NamePrefix }).(pulumi.StringPtrOutput)
}

// Policy JSON string
func (o IamGroupPolicyOutput) Policy() pulumi.StringOutput {
	return o.ApplyT(func(v *IamGroupPolicy) pulumi.StringOutput { return v.Policy }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IamGroupPolicyInput)(nil)).Elem(), &IamGroupPolicy{})
	pulumi.RegisterOutputType(IamGroupPolicyOutput{})
}
