// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type IamGroup struct {
	pulumi.CustomResourceState

	// Disable group
	DisableGroup pulumi.BoolPtrOutput `pulumi:"disableGroup"`
	// Delete group even if it has non-Terraform-managed members
	ForceDestroy pulumi.BoolPtrOutput `pulumi:"forceDestroy"`
	// The name of the group.
	GroupName  pulumi.StringOutput `pulumi:"groupName"`
	IamGroupId pulumi.StringOutput `pulumi:"iamGroupId"`
	// Name of the group
	Name pulumi.StringOutput `pulumi:"name"`
}

// NewIamGroup registers a new resource with the given unique name, arguments, and options.
func NewIamGroup(ctx *pulumi.Context,
	name string, args *IamGroupArgs, opts ...pulumi.ResourceOption) (*IamGroup, error) {
	if args == nil {
		args = &IamGroupArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource IamGroup
	err = ctx.RegisterPackageResource("minio:index/iamGroup:IamGroup", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIamGroup gets an existing IamGroup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIamGroup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IamGroupState, opts ...pulumi.ResourceOption) (*IamGroup, error) {
	var resource IamGroup
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/iamGroup:IamGroup", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IamGroup resources.
type iamGroupState struct {
	// Disable group
	DisableGroup *bool `pulumi:"disableGroup"`
	// Delete group even if it has non-Terraform-managed members
	ForceDestroy *bool `pulumi:"forceDestroy"`
	// The name of the group.
	GroupName  *string `pulumi:"groupName"`
	IamGroupId *string `pulumi:"iamGroupId"`
	// Name of the group
	Name *string `pulumi:"name"`
}

type IamGroupState struct {
	// Disable group
	DisableGroup pulumi.BoolPtrInput
	// Delete group even if it has non-Terraform-managed members
	ForceDestroy pulumi.BoolPtrInput
	// The name of the group.
	GroupName  pulumi.StringPtrInput
	IamGroupId pulumi.StringPtrInput
	// Name of the group
	Name pulumi.StringPtrInput
}

func (IamGroupState) ElementType() reflect.Type {
	return reflect.TypeOf((*iamGroupState)(nil)).Elem()
}

type iamGroupArgs struct {
	// Disable group
	DisableGroup *bool `pulumi:"disableGroup"`
	// Delete group even if it has non-Terraform-managed members
	ForceDestroy *bool   `pulumi:"forceDestroy"`
	IamGroupId   *string `pulumi:"iamGroupId"`
	// Name of the group
	Name *string `pulumi:"name"`
}

// The set of arguments for constructing a IamGroup resource.
type IamGroupArgs struct {
	// Disable group
	DisableGroup pulumi.BoolPtrInput
	// Delete group even if it has non-Terraform-managed members
	ForceDestroy pulumi.BoolPtrInput
	IamGroupId   pulumi.StringPtrInput
	// Name of the group
	Name pulumi.StringPtrInput
}

func (IamGroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*iamGroupArgs)(nil)).Elem()
}

type IamGroupInput interface {
	pulumi.Input

	ToIamGroupOutput() IamGroupOutput
	ToIamGroupOutputWithContext(ctx context.Context) IamGroupOutput
}

func (*IamGroup) ElementType() reflect.Type {
	return reflect.TypeOf((**IamGroup)(nil)).Elem()
}

func (i *IamGroup) ToIamGroupOutput() IamGroupOutput {
	return i.ToIamGroupOutputWithContext(context.Background())
}

func (i *IamGroup) ToIamGroupOutputWithContext(ctx context.Context) IamGroupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IamGroupOutput)
}

type IamGroupOutput struct{ *pulumi.OutputState }

func (IamGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IamGroup)(nil)).Elem()
}

func (o IamGroupOutput) ToIamGroupOutput() IamGroupOutput {
	return o
}

func (o IamGroupOutput) ToIamGroupOutputWithContext(ctx context.Context) IamGroupOutput {
	return o
}

// Disable group
func (o IamGroupOutput) DisableGroup() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *IamGroup) pulumi.BoolPtrOutput { return v.DisableGroup }).(pulumi.BoolPtrOutput)
}

// Delete group even if it has non-Terraform-managed members
func (o IamGroupOutput) ForceDestroy() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *IamGroup) pulumi.BoolPtrOutput { return v.ForceDestroy }).(pulumi.BoolPtrOutput)
}

// The name of the group.
func (o IamGroupOutput) GroupName() pulumi.StringOutput {
	return o.ApplyT(func(v *IamGroup) pulumi.StringOutput { return v.GroupName }).(pulumi.StringOutput)
}

func (o IamGroupOutput) IamGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v *IamGroup) pulumi.StringOutput { return v.IamGroupId }).(pulumi.StringOutput)
}

// Name of the group
func (o IamGroupOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *IamGroup) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IamGroupInput)(nil)).Elem(), &IamGroup{})
	pulumi.RegisterOutputType(IamGroupOutput{})
}
