// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type IamIdpOpenid struct {
	pulumi.CustomResourceState

	// JWT claim attribute used to identify the policy for the authenticated user. Defaults to 'policy'. Cannot be set together with role_policy.
	ClaimName pulumi.StringPtrOutput `pulumi:"claimName"`
	// Prefix to apply to JWT claim values when looking up policies. Cannot be set together with role_policy.
	ClaimPrefix pulumi.StringPtrOutput `pulumi:"claimPrefix"`
	// OAuth2 client ID registered with the identity provider.
	ClientId pulumi.StringOutput `pulumi:"clientId"`
	// OAuth2 client secret registered with the identity provider. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	ClientSecret pulumi.StringPtrOutput `pulumi:"clientSecret"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Write-only OAuth2 client secret for this OIDC configuration.
	ClientSecretWo pulumi.StringPtrOutput `pulumi:"clientSecretWo"`
	// Version identifier for client_secret_wo. Change this value to trigger updates when using client_secret_wo.
	ClientSecretWoVersion pulumi.Float64PtrOutput `pulumi:"clientSecretWoVersion"`
	// Comment or description for this OIDC configuration.
	Comment pulumi.StringPtrOutput `pulumi:"comment"`
	// URL to the OpenID Connect discovery document (e.g., https://accounts.example.com/.well-known/openid-configuration).
	ConfigUrl pulumi.StringOutput `pulumi:"configUrl"`
	// Display name for this identity provider shown on the MinIO login screen.
	DisplayName pulumi.StringPtrOutput `pulumi:"displayName"`
	// Whether this OIDC configuration is enabled.
	Enable         pulumi.BoolPtrOutput `pulumi:"enable"`
	IamIdpOpenidId pulumi.StringOutput  `pulumi:"iamIdpOpenidId"`
	// Name for this OIDC configuration. Use '_' (default) for the primary configuration or any identifier for named configurations.
	Name pulumi.StringOutput `pulumi:"name"`
	// Redirect URI registered with the identity provider for the OAuth2 callback.
	RedirectUri pulumi.StringPtrOutput `pulumi:"redirectUri"`
	// Indicates whether a MinIO server restart is required for the configuration to take effect.
	RestartRequired pulumi.BoolOutput `pulumi:"restartRequired"`
	// Policy for role-based OIDC access. When set, MinIO uses a role ARN approach and ignores claim_name/claim_prefix. Cannot be set together with<span pulumi-lang-nodejs=" claimName " pulumi-lang-dotnet=" ClaimName " pulumi-lang-go=" claimName " pulumi-lang-python=" claim_name " pulumi-lang-yaml=" claimName " pulumi-lang-java=" claimName " pulumi-lang-hcl=" claim_name "> claimName </span>or claim_prefix.
	RolePolicy pulumi.StringPtrOutput `pulumi:"rolePolicy"`
	// Comma-separated list of OAuth2 scopes to request (e.g., 'openid,email,profile').
	Scopes pulumi.StringPtrOutput `pulumi:"scopes"`
}

// NewIamIdpOpenid registers a new resource with the given unique name, arguments, and options.
func NewIamIdpOpenid(ctx *pulumi.Context,
	name string, args *IamIdpOpenidArgs, opts ...pulumi.ResourceOption) (*IamIdpOpenid, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	if args.ConfigUrl == nil {
		return nil, errors.New("invalid value for required argument 'ConfigUrl'")
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringPtrInput)
	}
	if args.ClientSecretWo != nil {
		args.ClientSecretWo = pulumi.ToSecret(args.ClientSecretWo).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientSecret",
		"clientSecretWo",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource IamIdpOpenid
	err = ctx.RegisterPackageResource("minio:index/iamIdpOpenid:IamIdpOpenid", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIamIdpOpenid gets an existing IamIdpOpenid resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIamIdpOpenid(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IamIdpOpenidState, opts ...pulumi.ResourceOption) (*IamIdpOpenid, error) {
	var resource IamIdpOpenid
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/iamIdpOpenid:IamIdpOpenid", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IamIdpOpenid resources.
type iamIdpOpenidState struct {
	// JWT claim attribute used to identify the policy for the authenticated user. Defaults to 'policy'. Cannot be set together with role_policy.
	ClaimName *string `pulumi:"claimName"`
	// Prefix to apply to JWT claim values when looking up policies. Cannot be set together with role_policy.
	ClaimPrefix *string `pulumi:"claimPrefix"`
	// OAuth2 client ID registered with the identity provider.
	ClientId *string `pulumi:"clientId"`
	// OAuth2 client secret registered with the identity provider. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	ClientSecret *string `pulumi:"clientSecret"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Write-only OAuth2 client secret for this OIDC configuration.
	ClientSecretWo *string `pulumi:"clientSecretWo"`
	// Version identifier for client_secret_wo. Change this value to trigger updates when using client_secret_wo.
	ClientSecretWoVersion *float64 `pulumi:"clientSecretWoVersion"`
	// Comment or description for this OIDC configuration.
	Comment *string `pulumi:"comment"`
	// URL to the OpenID Connect discovery document (e.g., https://accounts.example.com/.well-known/openid-configuration).
	ConfigUrl *string `pulumi:"configUrl"`
	// Display name for this identity provider shown on the MinIO login screen.
	DisplayName *string `pulumi:"displayName"`
	// Whether this OIDC configuration is enabled.
	Enable         *bool   `pulumi:"enable"`
	IamIdpOpenidId *string `pulumi:"iamIdpOpenidId"`
	// Name for this OIDC configuration. Use '_' (default) for the primary configuration or any identifier for named configurations.
	Name *string `pulumi:"name"`
	// Redirect URI registered with the identity provider for the OAuth2 callback.
	RedirectUri *string `pulumi:"redirectUri"`
	// Indicates whether a MinIO server restart is required for the configuration to take effect.
	RestartRequired *bool `pulumi:"restartRequired"`
	// Policy for role-based OIDC access. When set, MinIO uses a role ARN approach and ignores claim_name/claim_prefix. Cannot be set together with<span pulumi-lang-nodejs=" claimName " pulumi-lang-dotnet=" ClaimName " pulumi-lang-go=" claimName " pulumi-lang-python=" claim_name " pulumi-lang-yaml=" claimName " pulumi-lang-java=" claimName " pulumi-lang-hcl=" claim_name "> claimName </span>or claim_prefix.
	RolePolicy *string `pulumi:"rolePolicy"`
	// Comma-separated list of OAuth2 scopes to request (e.g., 'openid,email,profile').
	Scopes *string `pulumi:"scopes"`
}

type IamIdpOpenidState struct {
	// JWT claim attribute used to identify the policy for the authenticated user. Defaults to 'policy'. Cannot be set together with role_policy.
	ClaimName pulumi.StringPtrInput
	// Prefix to apply to JWT claim values when looking up policies. Cannot be set together with role_policy.
	ClaimPrefix pulumi.StringPtrInput
	// OAuth2 client ID registered with the identity provider.
	ClientId pulumi.StringPtrInput
	// OAuth2 client secret registered with the identity provider. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	ClientSecret pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Write-only OAuth2 client secret for this OIDC configuration.
	ClientSecretWo pulumi.StringPtrInput
	// Version identifier for client_secret_wo. Change this value to trigger updates when using client_secret_wo.
	ClientSecretWoVersion pulumi.Float64PtrInput
	// Comment or description for this OIDC configuration.
	Comment pulumi.StringPtrInput
	// URL to the OpenID Connect discovery document (e.g., https://accounts.example.com/.well-known/openid-configuration).
	ConfigUrl pulumi.StringPtrInput
	// Display name for this identity provider shown on the MinIO login screen.
	DisplayName pulumi.StringPtrInput
	// Whether this OIDC configuration is enabled.
	Enable         pulumi.BoolPtrInput
	IamIdpOpenidId pulumi.StringPtrInput
	// Name for this OIDC configuration. Use '_' (default) for the primary configuration or any identifier for named configurations.
	Name pulumi.StringPtrInput
	// Redirect URI registered with the identity provider for the OAuth2 callback.
	RedirectUri pulumi.StringPtrInput
	// Indicates whether a MinIO server restart is required for the configuration to take effect.
	RestartRequired pulumi.BoolPtrInput
	// Policy for role-based OIDC access. When set, MinIO uses a role ARN approach and ignores claim_name/claim_prefix. Cannot be set together with<span pulumi-lang-nodejs=" claimName " pulumi-lang-dotnet=" ClaimName " pulumi-lang-go=" claimName " pulumi-lang-python=" claim_name " pulumi-lang-yaml=" claimName " pulumi-lang-java=" claimName " pulumi-lang-hcl=" claim_name "> claimName </span>or claim_prefix.
	RolePolicy pulumi.StringPtrInput
	// Comma-separated list of OAuth2 scopes to request (e.g., 'openid,email,profile').
	Scopes pulumi.StringPtrInput
}

func (IamIdpOpenidState) ElementType() reflect.Type {
	return reflect.TypeOf((*iamIdpOpenidState)(nil)).Elem()
}

type iamIdpOpenidArgs struct {
	// JWT claim attribute used to identify the policy for the authenticated user. Defaults to 'policy'. Cannot be set together with role_policy.
	ClaimName *string `pulumi:"claimName"`
	// Prefix to apply to JWT claim values when looking up policies. Cannot be set together with role_policy.
	ClaimPrefix *string `pulumi:"claimPrefix"`
	// OAuth2 client ID registered with the identity provider.
	ClientId string `pulumi:"clientId"`
	// OAuth2 client secret registered with the identity provider. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	ClientSecret *string `pulumi:"clientSecret"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Write-only OAuth2 client secret for this OIDC configuration.
	ClientSecretWo *string `pulumi:"clientSecretWo"`
	// Version identifier for client_secret_wo. Change this value to trigger updates when using client_secret_wo.
	ClientSecretWoVersion *float64 `pulumi:"clientSecretWoVersion"`
	// Comment or description for this OIDC configuration.
	Comment *string `pulumi:"comment"`
	// URL to the OpenID Connect discovery document (e.g., https://accounts.example.com/.well-known/openid-configuration).
	ConfigUrl string `pulumi:"configUrl"`
	// Display name for this identity provider shown on the MinIO login screen.
	DisplayName *string `pulumi:"displayName"`
	// Whether this OIDC configuration is enabled.
	Enable         *bool   `pulumi:"enable"`
	IamIdpOpenidId *string `pulumi:"iamIdpOpenidId"`
	// Name for this OIDC configuration. Use '_' (default) for the primary configuration or any identifier for named configurations.
	Name *string `pulumi:"name"`
	// Redirect URI registered with the identity provider for the OAuth2 callback.
	RedirectUri *string `pulumi:"redirectUri"`
	// Policy for role-based OIDC access. When set, MinIO uses a role ARN approach and ignores claim_name/claim_prefix. Cannot be set together with<span pulumi-lang-nodejs=" claimName " pulumi-lang-dotnet=" ClaimName " pulumi-lang-go=" claimName " pulumi-lang-python=" claim_name " pulumi-lang-yaml=" claimName " pulumi-lang-java=" claimName " pulumi-lang-hcl=" claim_name "> claimName </span>or claim_prefix.
	RolePolicy *string `pulumi:"rolePolicy"`
	// Comma-separated list of OAuth2 scopes to request (e.g., 'openid,email,profile').
	Scopes *string `pulumi:"scopes"`
}

// The set of arguments for constructing a IamIdpOpenid resource.
type IamIdpOpenidArgs struct {
	// JWT claim attribute used to identify the policy for the authenticated user. Defaults to 'policy'. Cannot be set together with role_policy.
	ClaimName pulumi.StringPtrInput
	// Prefix to apply to JWT claim values when looking up policies. Cannot be set together with role_policy.
	ClaimPrefix pulumi.StringPtrInput
	// OAuth2 client ID registered with the identity provider.
	ClientId pulumi.StringInput
	// OAuth2 client secret registered with the identity provider. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	ClientSecret pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Write-only OAuth2 client secret for this OIDC configuration.
	ClientSecretWo pulumi.StringPtrInput
	// Version identifier for client_secret_wo. Change this value to trigger updates when using client_secret_wo.
	ClientSecretWoVersion pulumi.Float64PtrInput
	// Comment or description for this OIDC configuration.
	Comment pulumi.StringPtrInput
	// URL to the OpenID Connect discovery document (e.g., https://accounts.example.com/.well-known/openid-configuration).
	ConfigUrl pulumi.StringInput
	// Display name for this identity provider shown on the MinIO login screen.
	DisplayName pulumi.StringPtrInput
	// Whether this OIDC configuration is enabled.
	Enable         pulumi.BoolPtrInput
	IamIdpOpenidId pulumi.StringPtrInput
	// Name for this OIDC configuration. Use '_' (default) for the primary configuration or any identifier for named configurations.
	Name pulumi.StringPtrInput
	// Redirect URI registered with the identity provider for the OAuth2 callback.
	RedirectUri pulumi.StringPtrInput
	// Policy for role-based OIDC access. When set, MinIO uses a role ARN approach and ignores claim_name/claim_prefix. Cannot be set together with<span pulumi-lang-nodejs=" claimName " pulumi-lang-dotnet=" ClaimName " pulumi-lang-go=" claimName " pulumi-lang-python=" claim_name " pulumi-lang-yaml=" claimName " pulumi-lang-java=" claimName " pulumi-lang-hcl=" claim_name "> claimName </span>or claim_prefix.
	RolePolicy pulumi.StringPtrInput
	// Comma-separated list of OAuth2 scopes to request (e.g., 'openid,email,profile').
	Scopes pulumi.StringPtrInput
}

func (IamIdpOpenidArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*iamIdpOpenidArgs)(nil)).Elem()
}

type IamIdpOpenidInput interface {
	pulumi.Input

	ToIamIdpOpenidOutput() IamIdpOpenidOutput
	ToIamIdpOpenidOutputWithContext(ctx context.Context) IamIdpOpenidOutput
}

func (*IamIdpOpenid) ElementType() reflect.Type {
	return reflect.TypeOf((**IamIdpOpenid)(nil)).Elem()
}

func (i *IamIdpOpenid) ToIamIdpOpenidOutput() IamIdpOpenidOutput {
	return i.ToIamIdpOpenidOutputWithContext(context.Background())
}

func (i *IamIdpOpenid) ToIamIdpOpenidOutputWithContext(ctx context.Context) IamIdpOpenidOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IamIdpOpenidOutput)
}

type IamIdpOpenidOutput struct{ *pulumi.OutputState }

func (IamIdpOpenidOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IamIdpOpenid)(nil)).Elem()
}

func (o IamIdpOpenidOutput) ToIamIdpOpenidOutput() IamIdpOpenidOutput {
	return o
}

func (o IamIdpOpenidOutput) ToIamIdpOpenidOutputWithContext(ctx context.Context) IamIdpOpenidOutput {
	return o
}

// JWT claim attribute used to identify the policy for the authenticated user. Defaults to 'policy'. Cannot be set together with role_policy.
func (o IamIdpOpenidOutput) ClaimName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamIdpOpenid) pulumi.StringPtrOutput { return v.ClaimName }).(pulumi.StringPtrOutput)
}

// Prefix to apply to JWT claim values when looking up policies. Cannot be set together with role_policy.
func (o IamIdpOpenidOutput) ClaimPrefix() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamIdpOpenid) pulumi.StringPtrOutput { return v.ClaimPrefix }).(pulumi.StringPtrOutput)
}

// OAuth2 client ID registered with the identity provider.
func (o IamIdpOpenidOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *IamIdpOpenid) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

// OAuth2 client secret registered with the identity provider. MinIO does not return this value on read; Terraform keeps the value from your configuration.
func (o IamIdpOpenidOutput) ClientSecret() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamIdpOpenid) pulumi.StringPtrOutput { return v.ClientSecret }).(pulumi.StringPtrOutput)
}

// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
// Write-only OAuth2 client secret for this OIDC configuration.
func (o IamIdpOpenidOutput) ClientSecretWo() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamIdpOpenid) pulumi.StringPtrOutput { return v.ClientSecretWo }).(pulumi.StringPtrOutput)
}

// Version identifier for client_secret_wo. Change this value to trigger updates when using client_secret_wo.
func (o IamIdpOpenidOutput) ClientSecretWoVersion() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *IamIdpOpenid) pulumi.Float64PtrOutput { return v.ClientSecretWoVersion }).(pulumi.Float64PtrOutput)
}

// Comment or description for this OIDC configuration.
func (o IamIdpOpenidOutput) Comment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamIdpOpenid) pulumi.StringPtrOutput { return v.Comment }).(pulumi.StringPtrOutput)
}

// URL to the OpenID Connect discovery document (e.g., https://accounts.example.com/.well-known/openid-configuration).
func (o IamIdpOpenidOutput) ConfigUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *IamIdpOpenid) pulumi.StringOutput { return v.ConfigUrl }).(pulumi.StringOutput)
}

// Display name for this identity provider shown on the MinIO login screen.
func (o IamIdpOpenidOutput) DisplayName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamIdpOpenid) pulumi.StringPtrOutput { return v.DisplayName }).(pulumi.StringPtrOutput)
}

// Whether this OIDC configuration is enabled.
func (o IamIdpOpenidOutput) Enable() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *IamIdpOpenid) pulumi.BoolPtrOutput { return v.Enable }).(pulumi.BoolPtrOutput)
}

func (o IamIdpOpenidOutput) IamIdpOpenidId() pulumi.StringOutput {
	return o.ApplyT(func(v *IamIdpOpenid) pulumi.StringOutput { return v.IamIdpOpenidId }).(pulumi.StringOutput)
}

// Name for this OIDC configuration. Use '_' (default) for the primary configuration or any identifier for named configurations.
func (o IamIdpOpenidOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *IamIdpOpenid) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Redirect URI registered with the identity provider for the OAuth2 callback.
func (o IamIdpOpenidOutput) RedirectUri() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamIdpOpenid) pulumi.StringPtrOutput { return v.RedirectUri }).(pulumi.StringPtrOutput)
}

// Indicates whether a MinIO server restart is required for the configuration to take effect.
func (o IamIdpOpenidOutput) RestartRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v *IamIdpOpenid) pulumi.BoolOutput { return v.RestartRequired }).(pulumi.BoolOutput)
}

// Policy for role-based OIDC access. When set, MinIO uses a role ARN approach and ignores claim_name/claim_prefix. Cannot be set together with<span pulumi-lang-nodejs=" claimName " pulumi-lang-dotnet=" ClaimName " pulumi-lang-go=" claimName " pulumi-lang-python=" claim_name " pulumi-lang-yaml=" claimName " pulumi-lang-java=" claimName " pulumi-lang-hcl=" claim_name "> claimName </span>or claim_prefix.
func (o IamIdpOpenidOutput) RolePolicy() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamIdpOpenid) pulumi.StringPtrOutput { return v.RolePolicy }).(pulumi.StringPtrOutput)
}

// Comma-separated list of OAuth2 scopes to request (e.g., 'openid,email,profile').
func (o IamIdpOpenidOutput) Scopes() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamIdpOpenid) pulumi.StringPtrOutput { return v.Scopes }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IamIdpOpenidInput)(nil)).Elem(), &IamIdpOpenid{})
	pulumi.RegisterOutputType(IamIdpOpenidOutput{})
}
