// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type IamIdpLdap struct {
	pulumi.CustomResourceState

	// Whether this LDAP configuration is enabled.
	Enable pulumi.BoolPtrOutput `pulumi:"enable"`
	// Base DN for searching group entries (e.g., 'ou=groups,dc=example,dc=com').
	GroupSearchBaseDn pulumi.StringPtrOutput `pulumi:"groupSearchBaseDn"`
	// LDAP filter for group membership lookup (e.g., '(&(objectclass=groupOfNames)(member=%d))').
	GroupSearchFilter pulumi.StringPtrOutput `pulumi:"groupSearchFilter"`
	IamIdpLdapId      pulumi.StringOutput    `pulumi:"iamIdpLdapId"`
	// Distinguished name used to bind to the LDAP server for user/group lookups (e.g., 'cn=admin,dc=example,dc=com').
	LookupBindDn pulumi.StringPtrOutput `pulumi:"lookupBindDn"`
	// Password for the lookup bind DN. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	LookupBindPassword pulumi.StringPtrOutput `pulumi:"lookupBindPassword"`
	// Indicates whether a MinIO server restart is required for the configuration to take effect.
	RestartRequired pulumi.BoolOutput `pulumi:"restartRequired"`
	// LDAP server address in host:port format (e.g., 'ldap.example.com:389').
	ServerAddr pulumi.StringOutput `pulumi:"serverAddr"`
	// Allow plain (non-TLS) LDAP connections. Not recommended for production.
	ServerInsecure pulumi.BoolPtrOutput `pulumi:"serverInsecure"`
	// Use STARTTLS to upgrade a plain LDAP connection to TLS.
	Starttls pulumi.BoolPtrOutput `pulumi:"starttls"`
	// Disable TLS certificate verification. Not recommended for production.
	TlsSkipVerify pulumi.BoolPtrOutput `pulumi:"tlsSkipVerify"`
	// Base DN for searching user entries (e.g., 'ou=users,dc=example,dc=com').
	UserDnSearchBaseDn pulumi.StringPtrOutput `pulumi:"userDnSearchBaseDn"`
	// LDAP filter to locate a user by username (e.g., '(uid=%s)').
	UserDnSearchFilter pulumi.StringPtrOutput `pulumi:"userDnSearchFilter"`
}

// NewIamIdpLdap registers a new resource with the given unique name, arguments, and options.
func NewIamIdpLdap(ctx *pulumi.Context,
	name string, args *IamIdpLdapArgs, opts ...pulumi.ResourceOption) (*IamIdpLdap, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ServerAddr == nil {
		return nil, errors.New("invalid value for required argument 'ServerAddr'")
	}
	if args.LookupBindPassword != nil {
		args.LookupBindPassword = pulumi.ToSecret(args.LookupBindPassword).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"lookupBindPassword",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource IamIdpLdap
	err = ctx.RegisterPackageResource("minio:index/iamIdpLdap:IamIdpLdap", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIamIdpLdap gets an existing IamIdpLdap resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIamIdpLdap(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IamIdpLdapState, opts ...pulumi.ResourceOption) (*IamIdpLdap, error) {
	var resource IamIdpLdap
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/iamIdpLdap:IamIdpLdap", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IamIdpLdap resources.
type iamIdpLdapState struct {
	// Whether this LDAP configuration is enabled.
	Enable *bool `pulumi:"enable"`
	// Base DN for searching group entries (e.g., 'ou=groups,dc=example,dc=com').
	GroupSearchBaseDn *string `pulumi:"groupSearchBaseDn"`
	// LDAP filter for group membership lookup (e.g., '(&(objectclass=groupOfNames)(member=%d))').
	GroupSearchFilter *string `pulumi:"groupSearchFilter"`
	IamIdpLdapId      *string `pulumi:"iamIdpLdapId"`
	// Distinguished name used to bind to the LDAP server for user/group lookups (e.g., 'cn=admin,dc=example,dc=com').
	LookupBindDn *string `pulumi:"lookupBindDn"`
	// Password for the lookup bind DN. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	LookupBindPassword *string `pulumi:"lookupBindPassword"`
	// Indicates whether a MinIO server restart is required for the configuration to take effect.
	RestartRequired *bool `pulumi:"restartRequired"`
	// LDAP server address in host:port format (e.g., 'ldap.example.com:389').
	ServerAddr *string `pulumi:"serverAddr"`
	// Allow plain (non-TLS) LDAP connections. Not recommended for production.
	ServerInsecure *bool `pulumi:"serverInsecure"`
	// Use STARTTLS to upgrade a plain LDAP connection to TLS.
	Starttls *bool `pulumi:"starttls"`
	// Disable TLS certificate verification. Not recommended for production.
	TlsSkipVerify *bool `pulumi:"tlsSkipVerify"`
	// Base DN for searching user entries (e.g., 'ou=users,dc=example,dc=com').
	UserDnSearchBaseDn *string `pulumi:"userDnSearchBaseDn"`
	// LDAP filter to locate a user by username (e.g., '(uid=%s)').
	UserDnSearchFilter *string `pulumi:"userDnSearchFilter"`
}

type IamIdpLdapState struct {
	// Whether this LDAP configuration is enabled.
	Enable pulumi.BoolPtrInput
	// Base DN for searching group entries (e.g., 'ou=groups,dc=example,dc=com').
	GroupSearchBaseDn pulumi.StringPtrInput
	// LDAP filter for group membership lookup (e.g., '(&(objectclass=groupOfNames)(member=%d))').
	GroupSearchFilter pulumi.StringPtrInput
	IamIdpLdapId      pulumi.StringPtrInput
	// Distinguished name used to bind to the LDAP server for user/group lookups (e.g., 'cn=admin,dc=example,dc=com').
	LookupBindDn pulumi.StringPtrInput
	// Password for the lookup bind DN. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	LookupBindPassword pulumi.StringPtrInput
	// Indicates whether a MinIO server restart is required for the configuration to take effect.
	RestartRequired pulumi.BoolPtrInput
	// LDAP server address in host:port format (e.g., 'ldap.example.com:389').
	ServerAddr pulumi.StringPtrInput
	// Allow plain (non-TLS) LDAP connections. Not recommended for production.
	ServerInsecure pulumi.BoolPtrInput
	// Use STARTTLS to upgrade a plain LDAP connection to TLS.
	Starttls pulumi.BoolPtrInput
	// Disable TLS certificate verification. Not recommended for production.
	TlsSkipVerify pulumi.BoolPtrInput
	// Base DN for searching user entries (e.g., 'ou=users,dc=example,dc=com').
	UserDnSearchBaseDn pulumi.StringPtrInput
	// LDAP filter to locate a user by username (e.g., '(uid=%s)').
	UserDnSearchFilter pulumi.StringPtrInput
}

func (IamIdpLdapState) ElementType() reflect.Type {
	return reflect.TypeOf((*iamIdpLdapState)(nil)).Elem()
}

type iamIdpLdapArgs struct {
	// Whether this LDAP configuration is enabled.
	Enable *bool `pulumi:"enable"`
	// Base DN for searching group entries (e.g., 'ou=groups,dc=example,dc=com').
	GroupSearchBaseDn *string `pulumi:"groupSearchBaseDn"`
	// LDAP filter for group membership lookup (e.g., '(&(objectclass=groupOfNames)(member=%d))').
	GroupSearchFilter *string `pulumi:"groupSearchFilter"`
	IamIdpLdapId      *string `pulumi:"iamIdpLdapId"`
	// Distinguished name used to bind to the LDAP server for user/group lookups (e.g., 'cn=admin,dc=example,dc=com').
	LookupBindDn *string `pulumi:"lookupBindDn"`
	// Password for the lookup bind DN. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	LookupBindPassword *string `pulumi:"lookupBindPassword"`
	// LDAP server address in host:port format (e.g., 'ldap.example.com:389').
	ServerAddr string `pulumi:"serverAddr"`
	// Allow plain (non-TLS) LDAP connections. Not recommended for production.
	ServerInsecure *bool `pulumi:"serverInsecure"`
	// Use STARTTLS to upgrade a plain LDAP connection to TLS.
	Starttls *bool `pulumi:"starttls"`
	// Disable TLS certificate verification. Not recommended for production.
	TlsSkipVerify *bool `pulumi:"tlsSkipVerify"`
	// Base DN for searching user entries (e.g., 'ou=users,dc=example,dc=com').
	UserDnSearchBaseDn *string `pulumi:"userDnSearchBaseDn"`
	// LDAP filter to locate a user by username (e.g., '(uid=%s)').
	UserDnSearchFilter *string `pulumi:"userDnSearchFilter"`
}

// The set of arguments for constructing a IamIdpLdap resource.
type IamIdpLdapArgs struct {
	// Whether this LDAP configuration is enabled.
	Enable pulumi.BoolPtrInput
	// Base DN for searching group entries (e.g., 'ou=groups,dc=example,dc=com').
	GroupSearchBaseDn pulumi.StringPtrInput
	// LDAP filter for group membership lookup (e.g., '(&(objectclass=groupOfNames)(member=%d))').
	GroupSearchFilter pulumi.StringPtrInput
	IamIdpLdapId      pulumi.StringPtrInput
	// Distinguished name used to bind to the LDAP server for user/group lookups (e.g., 'cn=admin,dc=example,dc=com').
	LookupBindDn pulumi.StringPtrInput
	// Password for the lookup bind DN. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	LookupBindPassword pulumi.StringPtrInput
	// LDAP server address in host:port format (e.g., 'ldap.example.com:389').
	ServerAddr pulumi.StringInput
	// Allow plain (non-TLS) LDAP connections. Not recommended for production.
	ServerInsecure pulumi.BoolPtrInput
	// Use STARTTLS to upgrade a plain LDAP connection to TLS.
	Starttls pulumi.BoolPtrInput
	// Disable TLS certificate verification. Not recommended for production.
	TlsSkipVerify pulumi.BoolPtrInput
	// Base DN for searching user entries (e.g., 'ou=users,dc=example,dc=com').
	UserDnSearchBaseDn pulumi.StringPtrInput
	// LDAP filter to locate a user by username (e.g., '(uid=%s)').
	UserDnSearchFilter pulumi.StringPtrInput
}

func (IamIdpLdapArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*iamIdpLdapArgs)(nil)).Elem()
}

type IamIdpLdapInput interface {
	pulumi.Input

	ToIamIdpLdapOutput() IamIdpLdapOutput
	ToIamIdpLdapOutputWithContext(ctx context.Context) IamIdpLdapOutput
}

func (*IamIdpLdap) ElementType() reflect.Type {
	return reflect.TypeOf((**IamIdpLdap)(nil)).Elem()
}

func (i *IamIdpLdap) ToIamIdpLdapOutput() IamIdpLdapOutput {
	return i.ToIamIdpLdapOutputWithContext(context.Background())
}

func (i *IamIdpLdap) ToIamIdpLdapOutputWithContext(ctx context.Context) IamIdpLdapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IamIdpLdapOutput)
}

type IamIdpLdapOutput struct{ *pulumi.OutputState }

func (IamIdpLdapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IamIdpLdap)(nil)).Elem()
}

func (o IamIdpLdapOutput) ToIamIdpLdapOutput() IamIdpLdapOutput {
	return o
}

func (o IamIdpLdapOutput) ToIamIdpLdapOutputWithContext(ctx context.Context) IamIdpLdapOutput {
	return o
}

// Whether this LDAP configuration is enabled.
func (o IamIdpLdapOutput) Enable() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *IamIdpLdap) pulumi.BoolPtrOutput { return v.Enable }).(pulumi.BoolPtrOutput)
}

// Base DN for searching group entries (e.g., 'ou=groups,dc=example,dc=com').
func (o IamIdpLdapOutput) GroupSearchBaseDn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamIdpLdap) pulumi.StringPtrOutput { return v.GroupSearchBaseDn }).(pulumi.StringPtrOutput)
}

// LDAP filter for group membership lookup (e.g., '(&(objectclass=groupOfNames)(member=%d))').
func (o IamIdpLdapOutput) GroupSearchFilter() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamIdpLdap) pulumi.StringPtrOutput { return v.GroupSearchFilter }).(pulumi.StringPtrOutput)
}

func (o IamIdpLdapOutput) IamIdpLdapId() pulumi.StringOutput {
	return o.ApplyT(func(v *IamIdpLdap) pulumi.StringOutput { return v.IamIdpLdapId }).(pulumi.StringOutput)
}

// Distinguished name used to bind to the LDAP server for user/group lookups (e.g., 'cn=admin,dc=example,dc=com').
func (o IamIdpLdapOutput) LookupBindDn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamIdpLdap) pulumi.StringPtrOutput { return v.LookupBindDn }).(pulumi.StringPtrOutput)
}

// Password for the lookup bind DN. MinIO does not return this value on read; Terraform keeps the value from your configuration.
func (o IamIdpLdapOutput) LookupBindPassword() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamIdpLdap) pulumi.StringPtrOutput { return v.LookupBindPassword }).(pulumi.StringPtrOutput)
}

// Indicates whether a MinIO server restart is required for the configuration to take effect.
func (o IamIdpLdapOutput) RestartRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v *IamIdpLdap) pulumi.BoolOutput { return v.RestartRequired }).(pulumi.BoolOutput)
}

// LDAP server address in host:port format (e.g., 'ldap.example.com:389').
func (o IamIdpLdapOutput) ServerAddr() pulumi.StringOutput {
	return o.ApplyT(func(v *IamIdpLdap) pulumi.StringOutput { return v.ServerAddr }).(pulumi.StringOutput)
}

// Allow plain (non-TLS) LDAP connections. Not recommended for production.
func (o IamIdpLdapOutput) ServerInsecure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *IamIdpLdap) pulumi.BoolPtrOutput { return v.ServerInsecure }).(pulumi.BoolPtrOutput)
}

// Use STARTTLS to upgrade a plain LDAP connection to TLS.
func (o IamIdpLdapOutput) Starttls() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *IamIdpLdap) pulumi.BoolPtrOutput { return v.Starttls }).(pulumi.BoolPtrOutput)
}

// Disable TLS certificate verification. Not recommended for production.
func (o IamIdpLdapOutput) TlsSkipVerify() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *IamIdpLdap) pulumi.BoolPtrOutput { return v.TlsSkipVerify }).(pulumi.BoolPtrOutput)
}

// Base DN for searching user entries (e.g., 'ou=users,dc=example,dc=com').
func (o IamIdpLdapOutput) UserDnSearchBaseDn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamIdpLdap) pulumi.StringPtrOutput { return v.UserDnSearchBaseDn }).(pulumi.StringPtrOutput)
}

// LDAP filter to locate a user by username (e.g., '(uid=%s)').
func (o IamIdpLdapOutput) UserDnSearchFilter() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamIdpLdap) pulumi.StringPtrOutput { return v.UserDnSearchFilter }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IamIdpLdapInput)(nil)).Elem(), &IamIdpLdap{})
	pulumi.RegisterOutputType(IamIdpLdapOutput{})
}
