// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type IamLdapUserPolicyAttachment struct {
	pulumi.CustomResourceState

	IamLdapUserPolicyAttachmentId pulumi.StringOutput `pulumi:"iamLdapUserPolicyAttachmentId"`
	// Name of policy to attach to user
	PolicyName pulumi.StringOutput `pulumi:"policyName"`
	// The dn of user to attach policy to
	UserDn pulumi.StringOutput `pulumi:"userDn"`
}

// NewIamLdapUserPolicyAttachment registers a new resource with the given unique name, arguments, and options.
func NewIamLdapUserPolicyAttachment(ctx *pulumi.Context,
	name string, args *IamLdapUserPolicyAttachmentArgs, opts ...pulumi.ResourceOption) (*IamLdapUserPolicyAttachment, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PolicyName == nil {
		return nil, errors.New("invalid value for required argument 'PolicyName'")
	}
	if args.UserDn == nil {
		return nil, errors.New("invalid value for required argument 'UserDn'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource IamLdapUserPolicyAttachment
	err = ctx.RegisterPackageResource("minio:index/iamLdapUserPolicyAttachment:IamLdapUserPolicyAttachment", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIamLdapUserPolicyAttachment gets an existing IamLdapUserPolicyAttachment resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIamLdapUserPolicyAttachment(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IamLdapUserPolicyAttachmentState, opts ...pulumi.ResourceOption) (*IamLdapUserPolicyAttachment, error) {
	var resource IamLdapUserPolicyAttachment
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/iamLdapUserPolicyAttachment:IamLdapUserPolicyAttachment", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IamLdapUserPolicyAttachment resources.
type iamLdapUserPolicyAttachmentState struct {
	IamLdapUserPolicyAttachmentId *string `pulumi:"iamLdapUserPolicyAttachmentId"`
	// Name of policy to attach to user
	PolicyName *string `pulumi:"policyName"`
	// The dn of user to attach policy to
	UserDn *string `pulumi:"userDn"`
}

type IamLdapUserPolicyAttachmentState struct {
	IamLdapUserPolicyAttachmentId pulumi.StringPtrInput
	// Name of policy to attach to user
	PolicyName pulumi.StringPtrInput
	// The dn of user to attach policy to
	UserDn pulumi.StringPtrInput
}

func (IamLdapUserPolicyAttachmentState) ElementType() reflect.Type {
	return reflect.TypeOf((*iamLdapUserPolicyAttachmentState)(nil)).Elem()
}

type iamLdapUserPolicyAttachmentArgs struct {
	IamLdapUserPolicyAttachmentId *string `pulumi:"iamLdapUserPolicyAttachmentId"`
	// Name of policy to attach to user
	PolicyName string `pulumi:"policyName"`
	// The dn of user to attach policy to
	UserDn string `pulumi:"userDn"`
}

// The set of arguments for constructing a IamLdapUserPolicyAttachment resource.
type IamLdapUserPolicyAttachmentArgs struct {
	IamLdapUserPolicyAttachmentId pulumi.StringPtrInput
	// Name of policy to attach to user
	PolicyName pulumi.StringInput
	// The dn of user to attach policy to
	UserDn pulumi.StringInput
}

func (IamLdapUserPolicyAttachmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*iamLdapUserPolicyAttachmentArgs)(nil)).Elem()
}

type IamLdapUserPolicyAttachmentInput interface {
	pulumi.Input

	ToIamLdapUserPolicyAttachmentOutput() IamLdapUserPolicyAttachmentOutput
	ToIamLdapUserPolicyAttachmentOutputWithContext(ctx context.Context) IamLdapUserPolicyAttachmentOutput
}

func (*IamLdapUserPolicyAttachment) ElementType() reflect.Type {
	return reflect.TypeOf((**IamLdapUserPolicyAttachment)(nil)).Elem()
}

func (i *IamLdapUserPolicyAttachment) ToIamLdapUserPolicyAttachmentOutput() IamLdapUserPolicyAttachmentOutput {
	return i.ToIamLdapUserPolicyAttachmentOutputWithContext(context.Background())
}

func (i *IamLdapUserPolicyAttachment) ToIamLdapUserPolicyAttachmentOutputWithContext(ctx context.Context) IamLdapUserPolicyAttachmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IamLdapUserPolicyAttachmentOutput)
}

type IamLdapUserPolicyAttachmentOutput struct{ *pulumi.OutputState }

func (IamLdapUserPolicyAttachmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IamLdapUserPolicyAttachment)(nil)).Elem()
}

func (o IamLdapUserPolicyAttachmentOutput) ToIamLdapUserPolicyAttachmentOutput() IamLdapUserPolicyAttachmentOutput {
	return o
}

func (o IamLdapUserPolicyAttachmentOutput) ToIamLdapUserPolicyAttachmentOutputWithContext(ctx context.Context) IamLdapUserPolicyAttachmentOutput {
	return o
}

func (o IamLdapUserPolicyAttachmentOutput) IamLdapUserPolicyAttachmentId() pulumi.StringOutput {
	return o.ApplyT(func(v *IamLdapUserPolicyAttachment) pulumi.StringOutput { return v.IamLdapUserPolicyAttachmentId }).(pulumi.StringOutput)
}

// Name of policy to attach to user
func (o IamLdapUserPolicyAttachmentOutput) PolicyName() pulumi.StringOutput {
	return o.ApplyT(func(v *IamLdapUserPolicyAttachment) pulumi.StringOutput { return v.PolicyName }).(pulumi.StringOutput)
}

// The dn of user to attach policy to
func (o IamLdapUserPolicyAttachmentOutput) UserDn() pulumi.StringOutput {
	return o.ApplyT(func(v *IamLdapUserPolicyAttachment) pulumi.StringOutput { return v.UserDn }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IamLdapUserPolicyAttachmentInput)(nil)).Elem(), &IamLdapUserPolicyAttachment{})
	pulumi.RegisterOutputType(IamLdapUserPolicyAttachmentOutput{})
}
