// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type IamLdapGroupPolicyAttachment struct {
	pulumi.CustomResourceState

	// The distinguished name (dn) of group to attach policy to
	GroupDn                        pulumi.StringOutput `pulumi:"groupDn"`
	IamLdapGroupPolicyAttachmentId pulumi.StringOutput `pulumi:"iamLdapGroupPolicyAttachmentId"`
	// Name of policy to attach to group
	PolicyName pulumi.StringOutput `pulumi:"policyName"`
}

// NewIamLdapGroupPolicyAttachment registers a new resource with the given unique name, arguments, and options.
func NewIamLdapGroupPolicyAttachment(ctx *pulumi.Context,
	name string, args *IamLdapGroupPolicyAttachmentArgs, opts ...pulumi.ResourceOption) (*IamLdapGroupPolicyAttachment, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.GroupDn == nil {
		return nil, errors.New("invalid value for required argument 'GroupDn'")
	}
	if args.PolicyName == nil {
		return nil, errors.New("invalid value for required argument 'PolicyName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource IamLdapGroupPolicyAttachment
	err = ctx.RegisterPackageResource("minio:index/iamLdapGroupPolicyAttachment:IamLdapGroupPolicyAttachment", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIamLdapGroupPolicyAttachment gets an existing IamLdapGroupPolicyAttachment resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIamLdapGroupPolicyAttachment(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IamLdapGroupPolicyAttachmentState, opts ...pulumi.ResourceOption) (*IamLdapGroupPolicyAttachment, error) {
	var resource IamLdapGroupPolicyAttachment
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/iamLdapGroupPolicyAttachment:IamLdapGroupPolicyAttachment", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IamLdapGroupPolicyAttachment resources.
type iamLdapGroupPolicyAttachmentState struct {
	// The distinguished name (dn) of group to attach policy to
	GroupDn                        *string `pulumi:"groupDn"`
	IamLdapGroupPolicyAttachmentId *string `pulumi:"iamLdapGroupPolicyAttachmentId"`
	// Name of policy to attach to group
	PolicyName *string `pulumi:"policyName"`
}

type IamLdapGroupPolicyAttachmentState struct {
	// The distinguished name (dn) of group to attach policy to
	GroupDn                        pulumi.StringPtrInput
	IamLdapGroupPolicyAttachmentId pulumi.StringPtrInput
	// Name of policy to attach to group
	PolicyName pulumi.StringPtrInput
}

func (IamLdapGroupPolicyAttachmentState) ElementType() reflect.Type {
	return reflect.TypeOf((*iamLdapGroupPolicyAttachmentState)(nil)).Elem()
}

type iamLdapGroupPolicyAttachmentArgs struct {
	// The distinguished name (dn) of group to attach policy to
	GroupDn                        string  `pulumi:"groupDn"`
	IamLdapGroupPolicyAttachmentId *string `pulumi:"iamLdapGroupPolicyAttachmentId"`
	// Name of policy to attach to group
	PolicyName string `pulumi:"policyName"`
}

// The set of arguments for constructing a IamLdapGroupPolicyAttachment resource.
type IamLdapGroupPolicyAttachmentArgs struct {
	// The distinguished name (dn) of group to attach policy to
	GroupDn                        pulumi.StringInput
	IamLdapGroupPolicyAttachmentId pulumi.StringPtrInput
	// Name of policy to attach to group
	PolicyName pulumi.StringInput
}

func (IamLdapGroupPolicyAttachmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*iamLdapGroupPolicyAttachmentArgs)(nil)).Elem()
}

type IamLdapGroupPolicyAttachmentInput interface {
	pulumi.Input

	ToIamLdapGroupPolicyAttachmentOutput() IamLdapGroupPolicyAttachmentOutput
	ToIamLdapGroupPolicyAttachmentOutputWithContext(ctx context.Context) IamLdapGroupPolicyAttachmentOutput
}

func (*IamLdapGroupPolicyAttachment) ElementType() reflect.Type {
	return reflect.TypeOf((**IamLdapGroupPolicyAttachment)(nil)).Elem()
}

func (i *IamLdapGroupPolicyAttachment) ToIamLdapGroupPolicyAttachmentOutput() IamLdapGroupPolicyAttachmentOutput {
	return i.ToIamLdapGroupPolicyAttachmentOutputWithContext(context.Background())
}

func (i *IamLdapGroupPolicyAttachment) ToIamLdapGroupPolicyAttachmentOutputWithContext(ctx context.Context) IamLdapGroupPolicyAttachmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IamLdapGroupPolicyAttachmentOutput)
}

type IamLdapGroupPolicyAttachmentOutput struct{ *pulumi.OutputState }

func (IamLdapGroupPolicyAttachmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IamLdapGroupPolicyAttachment)(nil)).Elem()
}

func (o IamLdapGroupPolicyAttachmentOutput) ToIamLdapGroupPolicyAttachmentOutput() IamLdapGroupPolicyAttachmentOutput {
	return o
}

func (o IamLdapGroupPolicyAttachmentOutput) ToIamLdapGroupPolicyAttachmentOutputWithContext(ctx context.Context) IamLdapGroupPolicyAttachmentOutput {
	return o
}

// The distinguished name (dn) of group to attach policy to
func (o IamLdapGroupPolicyAttachmentOutput) GroupDn() pulumi.StringOutput {
	return o.ApplyT(func(v *IamLdapGroupPolicyAttachment) pulumi.StringOutput { return v.GroupDn }).(pulumi.StringOutput)
}

func (o IamLdapGroupPolicyAttachmentOutput) IamLdapGroupPolicyAttachmentId() pulumi.StringOutput {
	return o.ApplyT(func(v *IamLdapGroupPolicyAttachment) pulumi.StringOutput { return v.IamLdapGroupPolicyAttachmentId }).(pulumi.StringOutput)
}

// Name of policy to attach to group
func (o IamLdapGroupPolicyAttachmentOutput) PolicyName() pulumi.StringOutput {
	return o.ApplyT(func(v *IamLdapGroupPolicyAttachment) pulumi.StringOutput { return v.PolicyName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IamLdapGroupPolicyAttachmentInput)(nil)).Elem(), &IamLdapGroupPolicyAttachment{})
	pulumi.RegisterOutputType(IamLdapGroupPolicyAttachmentOutput{})
}
