// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type IamServiceAccount struct {
	pulumi.CustomResourceState

	// access key of service account
	AccessKey pulumi.StringOutput `pulumi:"accessKey"`
	// Description of service account (256 bytes max), can't be cleared once set
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Disable service account
	DisableUser pulumi.BoolPtrOutput `pulumi:"disableUser"`
	// Expiration of service account in RFC3339 format. Must be between NOW+15min & NOW+365d. If not set, the service account will not expire.
	Expiration          pulumi.StringPtrOutput `pulumi:"expiration"`
	IamServiceAccountId pulumi.StringOutput    `pulumi:"iamServiceAccountId"`
	// Name of service account (32 bytes max), can't be cleared once set
	Name pulumi.StringOutput `pulumi:"name"`
	// policy of service account as encoded JSON string
	Policy pulumi.StringPtrOutput `pulumi:"policy"`
	// secret key of service account
	SecretKey pulumi.StringOutput `pulumi:"secretKey"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// write-only secret key of service account
	SecretKeyWo pulumi.StringPtrOutput `pulumi:"secretKeyWo"`
	// Version identifier for secret_key_wo. Change this value to trigger secret key rotation when using secret_key_wo.
	SecretKeyWoVersion pulumi.Float64PtrOutput `pulumi:"secretKeyWoVersion"`
	Status             pulumi.StringOutput     `pulumi:"status"`
	// User the service account will be created for
	TargetUser pulumi.StringOutput `pulumi:"targetUser"`
	// rotate secret key
	UpdateSecret pulumi.BoolPtrOutput `pulumi:"updateSecret"`
}

// NewIamServiceAccount registers a new resource with the given unique name, arguments, and options.
func NewIamServiceAccount(ctx *pulumi.Context,
	name string, args *IamServiceAccountArgs, opts ...pulumi.ResourceOption) (*IamServiceAccount, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.TargetUser == nil {
		return nil, errors.New("invalid value for required argument 'TargetUser'")
	}
	if args.SecretKeyWo != nil {
		args.SecretKeyWo = pulumi.ToSecret(args.SecretKeyWo).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"secretKey",
		"secretKeyWo",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource IamServiceAccount
	err = ctx.RegisterPackageResource("minio:index/iamServiceAccount:IamServiceAccount", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIamServiceAccount gets an existing IamServiceAccount resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIamServiceAccount(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IamServiceAccountState, opts ...pulumi.ResourceOption) (*IamServiceAccount, error) {
	var resource IamServiceAccount
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/iamServiceAccount:IamServiceAccount", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IamServiceAccount resources.
type iamServiceAccountState struct {
	// access key of service account
	AccessKey *string `pulumi:"accessKey"`
	// Description of service account (256 bytes max), can't be cleared once set
	Description *string `pulumi:"description"`
	// Disable service account
	DisableUser *bool `pulumi:"disableUser"`
	// Expiration of service account in RFC3339 format. Must be between NOW+15min & NOW+365d. If not set, the service account will not expire.
	Expiration          *string `pulumi:"expiration"`
	IamServiceAccountId *string `pulumi:"iamServiceAccountId"`
	// Name of service account (32 bytes max), can't be cleared once set
	Name *string `pulumi:"name"`
	// policy of service account as encoded JSON string
	Policy *string `pulumi:"policy"`
	// secret key of service account
	SecretKey *string `pulumi:"secretKey"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// write-only secret key of service account
	SecretKeyWo *string `pulumi:"secretKeyWo"`
	// Version identifier for secret_key_wo. Change this value to trigger secret key rotation when using secret_key_wo.
	SecretKeyWoVersion *float64 `pulumi:"secretKeyWoVersion"`
	Status             *string  `pulumi:"status"`
	// User the service account will be created for
	TargetUser *string `pulumi:"targetUser"`
	// rotate secret key
	UpdateSecret *bool `pulumi:"updateSecret"`
}

type IamServiceAccountState struct {
	// access key of service account
	AccessKey pulumi.StringPtrInput
	// Description of service account (256 bytes max), can't be cleared once set
	Description pulumi.StringPtrInput
	// Disable service account
	DisableUser pulumi.BoolPtrInput
	// Expiration of service account in RFC3339 format. Must be between NOW+15min & NOW+365d. If not set, the service account will not expire.
	Expiration          pulumi.StringPtrInput
	IamServiceAccountId pulumi.StringPtrInput
	// Name of service account (32 bytes max), can't be cleared once set
	Name pulumi.StringPtrInput
	// policy of service account as encoded JSON string
	Policy pulumi.StringPtrInput
	// secret key of service account
	SecretKey pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// write-only secret key of service account
	SecretKeyWo pulumi.StringPtrInput
	// Version identifier for secret_key_wo. Change this value to trigger secret key rotation when using secret_key_wo.
	SecretKeyWoVersion pulumi.Float64PtrInput
	Status             pulumi.StringPtrInput
	// User the service account will be created for
	TargetUser pulumi.StringPtrInput
	// rotate secret key
	UpdateSecret pulumi.BoolPtrInput
}

func (IamServiceAccountState) ElementType() reflect.Type {
	return reflect.TypeOf((*iamServiceAccountState)(nil)).Elem()
}

type iamServiceAccountArgs struct {
	// Description of service account (256 bytes max), can't be cleared once set
	Description *string `pulumi:"description"`
	// Disable service account
	DisableUser *bool `pulumi:"disableUser"`
	// Expiration of service account in RFC3339 format. Must be between NOW+15min & NOW+365d. If not set, the service account will not expire.
	Expiration          *string `pulumi:"expiration"`
	IamServiceAccountId *string `pulumi:"iamServiceAccountId"`
	// Name of service account (32 bytes max), can't be cleared once set
	Name *string `pulumi:"name"`
	// policy of service account as encoded JSON string
	Policy *string `pulumi:"policy"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// write-only secret key of service account
	SecretKeyWo *string `pulumi:"secretKeyWo"`
	// Version identifier for secret_key_wo. Change this value to trigger secret key rotation when using secret_key_wo.
	SecretKeyWoVersion *float64 `pulumi:"secretKeyWoVersion"`
	// User the service account will be created for
	TargetUser string `pulumi:"targetUser"`
	// rotate secret key
	UpdateSecret *bool `pulumi:"updateSecret"`
}

// The set of arguments for constructing a IamServiceAccount resource.
type IamServiceAccountArgs struct {
	// Description of service account (256 bytes max), can't be cleared once set
	Description pulumi.StringPtrInput
	// Disable service account
	DisableUser pulumi.BoolPtrInput
	// Expiration of service account in RFC3339 format. Must be between NOW+15min & NOW+365d. If not set, the service account will not expire.
	Expiration          pulumi.StringPtrInput
	IamServiceAccountId pulumi.StringPtrInput
	// Name of service account (32 bytes max), can't be cleared once set
	Name pulumi.StringPtrInput
	// policy of service account as encoded JSON string
	Policy pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// write-only secret key of service account
	SecretKeyWo pulumi.StringPtrInput
	// Version identifier for secret_key_wo. Change this value to trigger secret key rotation when using secret_key_wo.
	SecretKeyWoVersion pulumi.Float64PtrInput
	// User the service account will be created for
	TargetUser pulumi.StringInput
	// rotate secret key
	UpdateSecret pulumi.BoolPtrInput
}

func (IamServiceAccountArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*iamServiceAccountArgs)(nil)).Elem()
}

type IamServiceAccountInput interface {
	pulumi.Input

	ToIamServiceAccountOutput() IamServiceAccountOutput
	ToIamServiceAccountOutputWithContext(ctx context.Context) IamServiceAccountOutput
}

func (*IamServiceAccount) ElementType() reflect.Type {
	return reflect.TypeOf((**IamServiceAccount)(nil)).Elem()
}

func (i *IamServiceAccount) ToIamServiceAccountOutput() IamServiceAccountOutput {
	return i.ToIamServiceAccountOutputWithContext(context.Background())
}

func (i *IamServiceAccount) ToIamServiceAccountOutputWithContext(ctx context.Context) IamServiceAccountOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IamServiceAccountOutput)
}

type IamServiceAccountOutput struct{ *pulumi.OutputState }

func (IamServiceAccountOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IamServiceAccount)(nil)).Elem()
}

func (o IamServiceAccountOutput) ToIamServiceAccountOutput() IamServiceAccountOutput {
	return o
}

func (o IamServiceAccountOutput) ToIamServiceAccountOutputWithContext(ctx context.Context) IamServiceAccountOutput {
	return o
}

// access key of service account
func (o IamServiceAccountOutput) AccessKey() pulumi.StringOutput {
	return o.ApplyT(func(v *IamServiceAccount) pulumi.StringOutput { return v.AccessKey }).(pulumi.StringOutput)
}

// Description of service account (256 bytes max), can't be cleared once set
func (o IamServiceAccountOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamServiceAccount) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Disable service account
func (o IamServiceAccountOutput) DisableUser() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *IamServiceAccount) pulumi.BoolPtrOutput { return v.DisableUser }).(pulumi.BoolPtrOutput)
}

// Expiration of service account in RFC3339 format. Must be between NOW+15min & NOW+365d. If not set, the service account will not expire.
func (o IamServiceAccountOutput) Expiration() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamServiceAccount) pulumi.StringPtrOutput { return v.Expiration }).(pulumi.StringPtrOutput)
}

func (o IamServiceAccountOutput) IamServiceAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *IamServiceAccount) pulumi.StringOutput { return v.IamServiceAccountId }).(pulumi.StringOutput)
}

// Name of service account (32 bytes max), can't be cleared once set
func (o IamServiceAccountOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *IamServiceAccount) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// policy of service account as encoded JSON string
func (o IamServiceAccountOutput) Policy() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamServiceAccount) pulumi.StringPtrOutput { return v.Policy }).(pulumi.StringPtrOutput)
}

// secret key of service account
func (o IamServiceAccountOutput) SecretKey() pulumi.StringOutput {
	return o.ApplyT(func(v *IamServiceAccount) pulumi.StringOutput { return v.SecretKey }).(pulumi.StringOutput)
}

// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
// write-only secret key of service account
func (o IamServiceAccountOutput) SecretKeyWo() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *IamServiceAccount) pulumi.StringPtrOutput { return v.SecretKeyWo }).(pulumi.StringPtrOutput)
}

// Version identifier for secret_key_wo. Change this value to trigger secret key rotation when using secret_key_wo.
func (o IamServiceAccountOutput) SecretKeyWoVersion() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *IamServiceAccount) pulumi.Float64PtrOutput { return v.SecretKeyWoVersion }).(pulumi.Float64PtrOutput)
}

func (o IamServiceAccountOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *IamServiceAccount) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// User the service account will be created for
func (o IamServiceAccountOutput) TargetUser() pulumi.StringOutput {
	return o.ApplyT(func(v *IamServiceAccount) pulumi.StringOutput { return v.TargetUser }).(pulumi.StringOutput)
}

// rotate secret key
func (o IamServiceAccountOutput) UpdateSecret() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *IamServiceAccount) pulumi.BoolPtrOutput { return v.UpdateSecret }).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IamServiceAccountInput)(nil)).Elem(), &IamServiceAccount{})
	pulumi.RegisterOutputType(IamServiceAccountOutput{})
}
