// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type IlmPolicy struct {
	pulumi.CustomResourceState

	// Name of the bucket.
	Bucket      pulumi.StringOutput `pulumi:"bucket"`
	IlmPolicyId pulumi.StringOutput `pulumi:"ilmPolicyId"`
	// List of lifecycle rules.
	Rules IlmPolicyRuleArrayOutput `pulumi:"rules"`
}

// NewIlmPolicy registers a new resource with the given unique name, arguments, and options.
func NewIlmPolicy(ctx *pulumi.Context,
	name string, args *IlmPolicyArgs, opts ...pulumi.ResourceOption) (*IlmPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Bucket == nil {
		return nil, errors.New("invalid value for required argument 'Bucket'")
	}
	if args.Rules == nil {
		return nil, errors.New("invalid value for required argument 'Rules'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource IlmPolicy
	err = ctx.RegisterPackageResource("minio:index/ilmPolicy:IlmPolicy", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIlmPolicy gets an existing IlmPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIlmPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IlmPolicyState, opts ...pulumi.ResourceOption) (*IlmPolicy, error) {
	var resource IlmPolicy
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/ilmPolicy:IlmPolicy", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IlmPolicy resources.
type ilmPolicyState struct {
	// Name of the bucket.
	Bucket      *string `pulumi:"bucket"`
	IlmPolicyId *string `pulumi:"ilmPolicyId"`
	// List of lifecycle rules.
	Rules []IlmPolicyRule `pulumi:"rules"`
}

type IlmPolicyState struct {
	// Name of the bucket.
	Bucket      pulumi.StringPtrInput
	IlmPolicyId pulumi.StringPtrInput
	// List of lifecycle rules.
	Rules IlmPolicyRuleArrayInput
}

func (IlmPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*ilmPolicyState)(nil)).Elem()
}

type ilmPolicyArgs struct {
	// Name of the bucket.
	Bucket      string  `pulumi:"bucket"`
	IlmPolicyId *string `pulumi:"ilmPolicyId"`
	// List of lifecycle rules.
	Rules []IlmPolicyRule `pulumi:"rules"`
}

// The set of arguments for constructing a IlmPolicy resource.
type IlmPolicyArgs struct {
	// Name of the bucket.
	Bucket      pulumi.StringInput
	IlmPolicyId pulumi.StringPtrInput
	// List of lifecycle rules.
	Rules IlmPolicyRuleArrayInput
}

func (IlmPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ilmPolicyArgs)(nil)).Elem()
}

type IlmPolicyInput interface {
	pulumi.Input

	ToIlmPolicyOutput() IlmPolicyOutput
	ToIlmPolicyOutputWithContext(ctx context.Context) IlmPolicyOutput
}

func (*IlmPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**IlmPolicy)(nil)).Elem()
}

func (i *IlmPolicy) ToIlmPolicyOutput() IlmPolicyOutput {
	return i.ToIlmPolicyOutputWithContext(context.Background())
}

func (i *IlmPolicy) ToIlmPolicyOutputWithContext(ctx context.Context) IlmPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IlmPolicyOutput)
}

type IlmPolicyOutput struct{ *pulumi.OutputState }

func (IlmPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IlmPolicy)(nil)).Elem()
}

func (o IlmPolicyOutput) ToIlmPolicyOutput() IlmPolicyOutput {
	return o
}

func (o IlmPolicyOutput) ToIlmPolicyOutputWithContext(ctx context.Context) IlmPolicyOutput {
	return o
}

// Name of the bucket.
func (o IlmPolicyOutput) Bucket() pulumi.StringOutput {
	return o.ApplyT(func(v *IlmPolicy) pulumi.StringOutput { return v.Bucket }).(pulumi.StringOutput)
}

func (o IlmPolicyOutput) IlmPolicyId() pulumi.StringOutput {
	return o.ApplyT(func(v *IlmPolicy) pulumi.StringOutput { return v.IlmPolicyId }).(pulumi.StringOutput)
}

// List of lifecycle rules.
func (o IlmPolicyOutput) Rules() IlmPolicyRuleArrayOutput {
	return o.ApplyT(func(v *IlmPolicy) IlmPolicyRuleArrayOutput { return v.Rules }).(IlmPolicyRuleArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IlmPolicyInput)(nil)).Elem(), &IlmPolicy{})
	pulumi.RegisterOutputType(IlmPolicyOutput{})
}
