// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NotifyMysql struct {
	pulumi.CustomResourceState

	// Comment or description for this notification target.
	Comment pulumi.StringPtrOutput `pulumi:"comment"`
	// MySQL DSN connection string (e.g., 'user:password@tcp(host:port)/database'). MinIO does not return this value on read; Terraform keeps the value from your configuration.
	ConnectionString pulumi.StringOutput `pulumi:"connectionString"`
	// Whether this notification target is enabled.
	Enable pulumi.BoolPtrOutput `pulumi:"enable"`
	// Output format for event records: 'namespace' or 'access'.
	Format pulumi.StringOutput `pulumi:"format"`
	// Maximum number of open connections to the MySQL database.
	MaxOpenConnections pulumi.Float64Output `pulumi:"maxOpenConnections"`
	// Target name identifier.
	Name          pulumi.StringOutput `pulumi:"name"`
	NotifyMysqlId pulumi.StringOutput `pulumi:"notifyMysqlId"`
	// Directory path for persistent event store when the target is offline.
	QueueDir pulumi.StringPtrOutput `pulumi:"queueDir"`
	// Maximum number of undelivered messages to queue.
	QueueLimit pulumi.Float64Output `pulumi:"queueLimit"`
	// Indicates whether a MinIO server restart is required.
	RestartRequired pulumi.BoolOutput `pulumi:"restartRequired"`
	// MySQL table name for storing event records.
	Table pulumi.StringOutput `pulumi:"table"`
}

// NewNotifyMysql registers a new resource with the given unique name, arguments, and options.
func NewNotifyMysql(ctx *pulumi.Context,
	name string, args *NotifyMysqlArgs, opts ...pulumi.ResourceOption) (*NotifyMysql, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ConnectionString == nil {
		return nil, errors.New("invalid value for required argument 'ConnectionString'")
	}
	if args.Format == nil {
		return nil, errors.New("invalid value for required argument 'Format'")
	}
	if args.Table == nil {
		return nil, errors.New("invalid value for required argument 'Table'")
	}
	if args.ConnectionString != nil {
		args.ConnectionString = pulumi.ToSecret(args.ConnectionString).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"connectionString",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NotifyMysql
	err = ctx.RegisterPackageResource("minio:index/notifyMysql:NotifyMysql", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNotifyMysql gets an existing NotifyMysql resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNotifyMysql(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NotifyMysqlState, opts ...pulumi.ResourceOption) (*NotifyMysql, error) {
	var resource NotifyMysql
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/notifyMysql:NotifyMysql", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NotifyMysql resources.
type notifyMysqlState struct {
	// Comment or description for this notification target.
	Comment *string `pulumi:"comment"`
	// MySQL DSN connection string (e.g., 'user:password@tcp(host:port)/database'). MinIO does not return this value on read; Terraform keeps the value from your configuration.
	ConnectionString *string `pulumi:"connectionString"`
	// Whether this notification target is enabled.
	Enable *bool `pulumi:"enable"`
	// Output format for event records: 'namespace' or 'access'.
	Format *string `pulumi:"format"`
	// Maximum number of open connections to the MySQL database.
	MaxOpenConnections *float64 `pulumi:"maxOpenConnections"`
	// Target name identifier.
	Name          *string `pulumi:"name"`
	NotifyMysqlId *string `pulumi:"notifyMysqlId"`
	// Directory path for persistent event store when the target is offline.
	QueueDir *string `pulumi:"queueDir"`
	// Maximum number of undelivered messages to queue.
	QueueLimit *float64 `pulumi:"queueLimit"`
	// Indicates whether a MinIO server restart is required.
	RestartRequired *bool `pulumi:"restartRequired"`
	// MySQL table name for storing event records.
	Table *string `pulumi:"table"`
}

type NotifyMysqlState struct {
	// Comment or description for this notification target.
	Comment pulumi.StringPtrInput
	// MySQL DSN connection string (e.g., 'user:password@tcp(host:port)/database'). MinIO does not return this value on read; Terraform keeps the value from your configuration.
	ConnectionString pulumi.StringPtrInput
	// Whether this notification target is enabled.
	Enable pulumi.BoolPtrInput
	// Output format for event records: 'namespace' or 'access'.
	Format pulumi.StringPtrInput
	// Maximum number of open connections to the MySQL database.
	MaxOpenConnections pulumi.Float64PtrInput
	// Target name identifier.
	Name          pulumi.StringPtrInput
	NotifyMysqlId pulumi.StringPtrInput
	// Directory path for persistent event store when the target is offline.
	QueueDir pulumi.StringPtrInput
	// Maximum number of undelivered messages to queue.
	QueueLimit pulumi.Float64PtrInput
	// Indicates whether a MinIO server restart is required.
	RestartRequired pulumi.BoolPtrInput
	// MySQL table name for storing event records.
	Table pulumi.StringPtrInput
}

func (NotifyMysqlState) ElementType() reflect.Type {
	return reflect.TypeOf((*notifyMysqlState)(nil)).Elem()
}

type notifyMysqlArgs struct {
	// Comment or description for this notification target.
	Comment *string `pulumi:"comment"`
	// MySQL DSN connection string (e.g., 'user:password@tcp(host:port)/database'). MinIO does not return this value on read; Terraform keeps the value from your configuration.
	ConnectionString string `pulumi:"connectionString"`
	// Whether this notification target is enabled.
	Enable *bool `pulumi:"enable"`
	// Output format for event records: 'namespace' or 'access'.
	Format string `pulumi:"format"`
	// Maximum number of open connections to the MySQL database.
	MaxOpenConnections *float64 `pulumi:"maxOpenConnections"`
	// Target name identifier.
	Name          *string `pulumi:"name"`
	NotifyMysqlId *string `pulumi:"notifyMysqlId"`
	// Directory path for persistent event store when the target is offline.
	QueueDir *string `pulumi:"queueDir"`
	// Maximum number of undelivered messages to queue.
	QueueLimit *float64 `pulumi:"queueLimit"`
	// MySQL table name for storing event records.
	Table string `pulumi:"table"`
}

// The set of arguments for constructing a NotifyMysql resource.
type NotifyMysqlArgs struct {
	// Comment or description for this notification target.
	Comment pulumi.StringPtrInput
	// MySQL DSN connection string (e.g., 'user:password@tcp(host:port)/database'). MinIO does not return this value on read; Terraform keeps the value from your configuration.
	ConnectionString pulumi.StringInput
	// Whether this notification target is enabled.
	Enable pulumi.BoolPtrInput
	// Output format for event records: 'namespace' or 'access'.
	Format pulumi.StringInput
	// Maximum number of open connections to the MySQL database.
	MaxOpenConnections pulumi.Float64PtrInput
	// Target name identifier.
	Name          pulumi.StringPtrInput
	NotifyMysqlId pulumi.StringPtrInput
	// Directory path for persistent event store when the target is offline.
	QueueDir pulumi.StringPtrInput
	// Maximum number of undelivered messages to queue.
	QueueLimit pulumi.Float64PtrInput
	// MySQL table name for storing event records.
	Table pulumi.StringInput
}

func (NotifyMysqlArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*notifyMysqlArgs)(nil)).Elem()
}

type NotifyMysqlInput interface {
	pulumi.Input

	ToNotifyMysqlOutput() NotifyMysqlOutput
	ToNotifyMysqlOutputWithContext(ctx context.Context) NotifyMysqlOutput
}

func (*NotifyMysql) ElementType() reflect.Type {
	return reflect.TypeOf((**NotifyMysql)(nil)).Elem()
}

func (i *NotifyMysql) ToNotifyMysqlOutput() NotifyMysqlOutput {
	return i.ToNotifyMysqlOutputWithContext(context.Background())
}

func (i *NotifyMysql) ToNotifyMysqlOutputWithContext(ctx context.Context) NotifyMysqlOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NotifyMysqlOutput)
}

type NotifyMysqlOutput struct{ *pulumi.OutputState }

func (NotifyMysqlOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NotifyMysql)(nil)).Elem()
}

func (o NotifyMysqlOutput) ToNotifyMysqlOutput() NotifyMysqlOutput {
	return o
}

func (o NotifyMysqlOutput) ToNotifyMysqlOutputWithContext(ctx context.Context) NotifyMysqlOutput {
	return o
}

// Comment or description for this notification target.
func (o NotifyMysqlOutput) Comment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NotifyMysql) pulumi.StringPtrOutput { return v.Comment }).(pulumi.StringPtrOutput)
}

// MySQL DSN connection string (e.g., 'user:password@tcp(host:port)/database'). MinIO does not return this value on read; Terraform keeps the value from your configuration.
func (o NotifyMysqlOutput) ConnectionString() pulumi.StringOutput {
	return o.ApplyT(func(v *NotifyMysql) pulumi.StringOutput { return v.ConnectionString }).(pulumi.StringOutput)
}

// Whether this notification target is enabled.
func (o NotifyMysqlOutput) Enable() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *NotifyMysql) pulumi.BoolPtrOutput { return v.Enable }).(pulumi.BoolPtrOutput)
}

// Output format for event records: 'namespace' or 'access'.
func (o NotifyMysqlOutput) Format() pulumi.StringOutput {
	return o.ApplyT(func(v *NotifyMysql) pulumi.StringOutput { return v.Format }).(pulumi.StringOutput)
}

// Maximum number of open connections to the MySQL database.
func (o NotifyMysqlOutput) MaxOpenConnections() pulumi.Float64Output {
	return o.ApplyT(func(v *NotifyMysql) pulumi.Float64Output { return v.MaxOpenConnections }).(pulumi.Float64Output)
}

// Target name identifier.
func (o NotifyMysqlOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NotifyMysql) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o NotifyMysqlOutput) NotifyMysqlId() pulumi.StringOutput {
	return o.ApplyT(func(v *NotifyMysql) pulumi.StringOutput { return v.NotifyMysqlId }).(pulumi.StringOutput)
}

// Directory path for persistent event store when the target is offline.
func (o NotifyMysqlOutput) QueueDir() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NotifyMysql) pulumi.StringPtrOutput { return v.QueueDir }).(pulumi.StringPtrOutput)
}

// Maximum number of undelivered messages to queue.
func (o NotifyMysqlOutput) QueueLimit() pulumi.Float64Output {
	return o.ApplyT(func(v *NotifyMysql) pulumi.Float64Output { return v.QueueLimit }).(pulumi.Float64Output)
}

// Indicates whether a MinIO server restart is required.
func (o NotifyMysqlOutput) RestartRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v *NotifyMysql) pulumi.BoolOutput { return v.RestartRequired }).(pulumi.BoolOutput)
}

// MySQL table name for storing event records.
func (o NotifyMysqlOutput) Table() pulumi.StringOutput {
	return o.ApplyT(func(v *NotifyMysql) pulumi.StringOutput { return v.Table }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NotifyMysqlInput)(nil)).Elem(), &NotifyMysql{})
	pulumi.RegisterOutputType(NotifyMysqlOutput{})
}
