// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NotifyKafka struct {
	pulumi.CustomResourceState

	// Number of messages to batch before sending to Kafka.
	BatchSize pulumi.Float64Output `pulumi:"batchSize"`
	// Comma-separated list of Kafka broker addresses (e.g., 'host1:9092,host2:9092').
	Brokers pulumi.StringOutput `pulumi:"brokers"`
	// Path to the client TLS certificate for mTLS authentication.
	ClientTlsCert pulumi.StringPtrOutput `pulumi:"clientTlsCert"`
	// Path to the client TLS private key. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	ClientTlsKey pulumi.StringPtrOutput `pulumi:"clientTlsKey"`
	// Comment or description for this notification target.
	Comment pulumi.StringPtrOutput `pulumi:"comment"`
	// Whether this notification target is enabled.
	Enable pulumi.BoolPtrOutput `pulumi:"enable"`
	// Target name identifier.
	Name          pulumi.StringOutput `pulumi:"name"`
	NotifyKafkaId pulumi.StringOutput `pulumi:"notifyKafkaId"`
	// Directory path for persistent event store when the target is offline.
	QueueDir pulumi.StringPtrOutput `pulumi:"queueDir"`
	// Maximum number of undelivered messages to queue.
	QueueLimit pulumi.Float64Output `pulumi:"queueLimit"`
	// Indicates whether a MinIO server restart is required.
	RestartRequired pulumi.BoolOutput `pulumi:"restartRequired"`
	// SASL authentication mechanism: 'plain', 'scram-sha-256', or 'scram-sha-512'.
	SaslMechanism pulumi.StringPtrOutput `pulumi:"saslMechanism"`
	// SASL password for Kafka authentication. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	SaslPassword pulumi.StringPtrOutput `pulumi:"saslPassword"`
	// SASL username for Kafka authentication.
	SaslUsername pulumi.StringPtrOutput `pulumi:"saslUsername"`
	// Whether to enable TLS for the Kafka connection.
	Tls pulumi.BoolPtrOutput `pulumi:"tls"`
	// TLS client authentication type (0=NoClientCert, 1=RequestClientCert, etc.).
	TlsClientAuth pulumi.Float64PtrOutput `pulumi:"tlsClientAuth"`
	// Whether to skip TLS certificate verification.
	TlsSkipVerify pulumi.BoolPtrOutput `pulumi:"tlsSkipVerify"`
	// Kafka topic to publish event notifications to.
	Topic pulumi.StringOutput `pulumi:"topic"`
	// Kafka cluster version (e.g., '2.8.0').
	Version pulumi.StringPtrOutput `pulumi:"version"`
}

// NewNotifyKafka registers a new resource with the given unique name, arguments, and options.
func NewNotifyKafka(ctx *pulumi.Context,
	name string, args *NotifyKafkaArgs, opts ...pulumi.ResourceOption) (*NotifyKafka, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Brokers == nil {
		return nil, errors.New("invalid value for required argument 'Brokers'")
	}
	if args.Topic == nil {
		return nil, errors.New("invalid value for required argument 'Topic'")
	}
	if args.ClientTlsKey != nil {
		args.ClientTlsKey = pulumi.ToSecret(args.ClientTlsKey).(pulumi.StringPtrInput)
	}
	if args.SaslPassword != nil {
		args.SaslPassword = pulumi.ToSecret(args.SaslPassword).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientTlsKey",
		"saslPassword",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NotifyKafka
	err = ctx.RegisterPackageResource("minio:index/notifyKafka:NotifyKafka", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNotifyKafka gets an existing NotifyKafka resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNotifyKafka(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NotifyKafkaState, opts ...pulumi.ResourceOption) (*NotifyKafka, error) {
	var resource NotifyKafka
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/notifyKafka:NotifyKafka", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NotifyKafka resources.
type notifyKafkaState struct {
	// Number of messages to batch before sending to Kafka.
	BatchSize *float64 `pulumi:"batchSize"`
	// Comma-separated list of Kafka broker addresses (e.g., 'host1:9092,host2:9092').
	Brokers *string `pulumi:"brokers"`
	// Path to the client TLS certificate for mTLS authentication.
	ClientTlsCert *string `pulumi:"clientTlsCert"`
	// Path to the client TLS private key. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	ClientTlsKey *string `pulumi:"clientTlsKey"`
	// Comment or description for this notification target.
	Comment *string `pulumi:"comment"`
	// Whether this notification target is enabled.
	Enable *bool `pulumi:"enable"`
	// Target name identifier.
	Name          *string `pulumi:"name"`
	NotifyKafkaId *string `pulumi:"notifyKafkaId"`
	// Directory path for persistent event store when the target is offline.
	QueueDir *string `pulumi:"queueDir"`
	// Maximum number of undelivered messages to queue.
	QueueLimit *float64 `pulumi:"queueLimit"`
	// Indicates whether a MinIO server restart is required.
	RestartRequired *bool `pulumi:"restartRequired"`
	// SASL authentication mechanism: 'plain', 'scram-sha-256', or 'scram-sha-512'.
	SaslMechanism *string `pulumi:"saslMechanism"`
	// SASL password for Kafka authentication. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	SaslPassword *string `pulumi:"saslPassword"`
	// SASL username for Kafka authentication.
	SaslUsername *string `pulumi:"saslUsername"`
	// Whether to enable TLS for the Kafka connection.
	Tls *bool `pulumi:"tls"`
	// TLS client authentication type (0=NoClientCert, 1=RequestClientCert, etc.).
	TlsClientAuth *float64 `pulumi:"tlsClientAuth"`
	// Whether to skip TLS certificate verification.
	TlsSkipVerify *bool `pulumi:"tlsSkipVerify"`
	// Kafka topic to publish event notifications to.
	Topic *string `pulumi:"topic"`
	// Kafka cluster version (e.g., '2.8.0').
	Version *string `pulumi:"version"`
}

type NotifyKafkaState struct {
	// Number of messages to batch before sending to Kafka.
	BatchSize pulumi.Float64PtrInput
	// Comma-separated list of Kafka broker addresses (e.g., 'host1:9092,host2:9092').
	Brokers pulumi.StringPtrInput
	// Path to the client TLS certificate for mTLS authentication.
	ClientTlsCert pulumi.StringPtrInput
	// Path to the client TLS private key. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	ClientTlsKey pulumi.StringPtrInput
	// Comment or description for this notification target.
	Comment pulumi.StringPtrInput
	// Whether this notification target is enabled.
	Enable pulumi.BoolPtrInput
	// Target name identifier.
	Name          pulumi.StringPtrInput
	NotifyKafkaId pulumi.StringPtrInput
	// Directory path for persistent event store when the target is offline.
	QueueDir pulumi.StringPtrInput
	// Maximum number of undelivered messages to queue.
	QueueLimit pulumi.Float64PtrInput
	// Indicates whether a MinIO server restart is required.
	RestartRequired pulumi.BoolPtrInput
	// SASL authentication mechanism: 'plain', 'scram-sha-256', or 'scram-sha-512'.
	SaslMechanism pulumi.StringPtrInput
	// SASL password for Kafka authentication. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	SaslPassword pulumi.StringPtrInput
	// SASL username for Kafka authentication.
	SaslUsername pulumi.StringPtrInput
	// Whether to enable TLS for the Kafka connection.
	Tls pulumi.BoolPtrInput
	// TLS client authentication type (0=NoClientCert, 1=RequestClientCert, etc.).
	TlsClientAuth pulumi.Float64PtrInput
	// Whether to skip TLS certificate verification.
	TlsSkipVerify pulumi.BoolPtrInput
	// Kafka topic to publish event notifications to.
	Topic pulumi.StringPtrInput
	// Kafka cluster version (e.g., '2.8.0').
	Version pulumi.StringPtrInput
}

func (NotifyKafkaState) ElementType() reflect.Type {
	return reflect.TypeOf((*notifyKafkaState)(nil)).Elem()
}

type notifyKafkaArgs struct {
	// Number of messages to batch before sending to Kafka.
	BatchSize *float64 `pulumi:"batchSize"`
	// Comma-separated list of Kafka broker addresses (e.g., 'host1:9092,host2:9092').
	Brokers string `pulumi:"brokers"`
	// Path to the client TLS certificate for mTLS authentication.
	ClientTlsCert *string `pulumi:"clientTlsCert"`
	// Path to the client TLS private key. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	ClientTlsKey *string `pulumi:"clientTlsKey"`
	// Comment or description for this notification target.
	Comment *string `pulumi:"comment"`
	// Whether this notification target is enabled.
	Enable *bool `pulumi:"enable"`
	// Target name identifier.
	Name          *string `pulumi:"name"`
	NotifyKafkaId *string `pulumi:"notifyKafkaId"`
	// Directory path for persistent event store when the target is offline.
	QueueDir *string `pulumi:"queueDir"`
	// Maximum number of undelivered messages to queue.
	QueueLimit *float64 `pulumi:"queueLimit"`
	// SASL authentication mechanism: 'plain', 'scram-sha-256', or 'scram-sha-512'.
	SaslMechanism *string `pulumi:"saslMechanism"`
	// SASL password for Kafka authentication. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	SaslPassword *string `pulumi:"saslPassword"`
	// SASL username for Kafka authentication.
	SaslUsername *string `pulumi:"saslUsername"`
	// Whether to enable TLS for the Kafka connection.
	Tls *bool `pulumi:"tls"`
	// TLS client authentication type (0=NoClientCert, 1=RequestClientCert, etc.).
	TlsClientAuth *float64 `pulumi:"tlsClientAuth"`
	// Whether to skip TLS certificate verification.
	TlsSkipVerify *bool `pulumi:"tlsSkipVerify"`
	// Kafka topic to publish event notifications to.
	Topic string `pulumi:"topic"`
	// Kafka cluster version (e.g., '2.8.0').
	Version *string `pulumi:"version"`
}

// The set of arguments for constructing a NotifyKafka resource.
type NotifyKafkaArgs struct {
	// Number of messages to batch before sending to Kafka.
	BatchSize pulumi.Float64PtrInput
	// Comma-separated list of Kafka broker addresses (e.g., 'host1:9092,host2:9092').
	Brokers pulumi.StringInput
	// Path to the client TLS certificate for mTLS authentication.
	ClientTlsCert pulumi.StringPtrInput
	// Path to the client TLS private key. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	ClientTlsKey pulumi.StringPtrInput
	// Comment or description for this notification target.
	Comment pulumi.StringPtrInput
	// Whether this notification target is enabled.
	Enable pulumi.BoolPtrInput
	// Target name identifier.
	Name          pulumi.StringPtrInput
	NotifyKafkaId pulumi.StringPtrInput
	// Directory path for persistent event store when the target is offline.
	QueueDir pulumi.StringPtrInput
	// Maximum number of undelivered messages to queue.
	QueueLimit pulumi.Float64PtrInput
	// SASL authentication mechanism: 'plain', 'scram-sha-256', or 'scram-sha-512'.
	SaslMechanism pulumi.StringPtrInput
	// SASL password for Kafka authentication. MinIO does not return this value on read; Terraform keeps the value from your configuration.
	SaslPassword pulumi.StringPtrInput
	// SASL username for Kafka authentication.
	SaslUsername pulumi.StringPtrInput
	// Whether to enable TLS for the Kafka connection.
	Tls pulumi.BoolPtrInput
	// TLS client authentication type (0=NoClientCert, 1=RequestClientCert, etc.).
	TlsClientAuth pulumi.Float64PtrInput
	// Whether to skip TLS certificate verification.
	TlsSkipVerify pulumi.BoolPtrInput
	// Kafka topic to publish event notifications to.
	Topic pulumi.StringInput
	// Kafka cluster version (e.g., '2.8.0').
	Version pulumi.StringPtrInput
}

func (NotifyKafkaArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*notifyKafkaArgs)(nil)).Elem()
}

type NotifyKafkaInput interface {
	pulumi.Input

	ToNotifyKafkaOutput() NotifyKafkaOutput
	ToNotifyKafkaOutputWithContext(ctx context.Context) NotifyKafkaOutput
}

func (*NotifyKafka) ElementType() reflect.Type {
	return reflect.TypeOf((**NotifyKafka)(nil)).Elem()
}

func (i *NotifyKafka) ToNotifyKafkaOutput() NotifyKafkaOutput {
	return i.ToNotifyKafkaOutputWithContext(context.Background())
}

func (i *NotifyKafka) ToNotifyKafkaOutputWithContext(ctx context.Context) NotifyKafkaOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NotifyKafkaOutput)
}

type NotifyKafkaOutput struct{ *pulumi.OutputState }

func (NotifyKafkaOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NotifyKafka)(nil)).Elem()
}

func (o NotifyKafkaOutput) ToNotifyKafkaOutput() NotifyKafkaOutput {
	return o
}

func (o NotifyKafkaOutput) ToNotifyKafkaOutputWithContext(ctx context.Context) NotifyKafkaOutput {
	return o
}

// Number of messages to batch before sending to Kafka.
func (o NotifyKafkaOutput) BatchSize() pulumi.Float64Output {
	return o.ApplyT(func(v *NotifyKafka) pulumi.Float64Output { return v.BatchSize }).(pulumi.Float64Output)
}

// Comma-separated list of Kafka broker addresses (e.g., 'host1:9092,host2:9092').
func (o NotifyKafkaOutput) Brokers() pulumi.StringOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.StringOutput { return v.Brokers }).(pulumi.StringOutput)
}

// Path to the client TLS certificate for mTLS authentication.
func (o NotifyKafkaOutput) ClientTlsCert() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.StringPtrOutput { return v.ClientTlsCert }).(pulumi.StringPtrOutput)
}

// Path to the client TLS private key. MinIO does not return this value on read; Terraform keeps the value from your configuration.
func (o NotifyKafkaOutput) ClientTlsKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.StringPtrOutput { return v.ClientTlsKey }).(pulumi.StringPtrOutput)
}

// Comment or description for this notification target.
func (o NotifyKafkaOutput) Comment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.StringPtrOutput { return v.Comment }).(pulumi.StringPtrOutput)
}

// Whether this notification target is enabled.
func (o NotifyKafkaOutput) Enable() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.BoolPtrOutput { return v.Enable }).(pulumi.BoolPtrOutput)
}

// Target name identifier.
func (o NotifyKafkaOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o NotifyKafkaOutput) NotifyKafkaId() pulumi.StringOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.StringOutput { return v.NotifyKafkaId }).(pulumi.StringOutput)
}

// Directory path for persistent event store when the target is offline.
func (o NotifyKafkaOutput) QueueDir() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.StringPtrOutput { return v.QueueDir }).(pulumi.StringPtrOutput)
}

// Maximum number of undelivered messages to queue.
func (o NotifyKafkaOutput) QueueLimit() pulumi.Float64Output {
	return o.ApplyT(func(v *NotifyKafka) pulumi.Float64Output { return v.QueueLimit }).(pulumi.Float64Output)
}

// Indicates whether a MinIO server restart is required.
func (o NotifyKafkaOutput) RestartRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.BoolOutput { return v.RestartRequired }).(pulumi.BoolOutput)
}

// SASL authentication mechanism: 'plain', 'scram-sha-256', or 'scram-sha-512'.
func (o NotifyKafkaOutput) SaslMechanism() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.StringPtrOutput { return v.SaslMechanism }).(pulumi.StringPtrOutput)
}

// SASL password for Kafka authentication. MinIO does not return this value on read; Terraform keeps the value from your configuration.
func (o NotifyKafkaOutput) SaslPassword() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.StringPtrOutput { return v.SaslPassword }).(pulumi.StringPtrOutput)
}

// SASL username for Kafka authentication.
func (o NotifyKafkaOutput) SaslUsername() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.StringPtrOutput { return v.SaslUsername }).(pulumi.StringPtrOutput)
}

// Whether to enable TLS for the Kafka connection.
func (o NotifyKafkaOutput) Tls() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.BoolPtrOutput { return v.Tls }).(pulumi.BoolPtrOutput)
}

// TLS client authentication type (0=NoClientCert, 1=RequestClientCert, etc.).
func (o NotifyKafkaOutput) TlsClientAuth() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.Float64PtrOutput { return v.TlsClientAuth }).(pulumi.Float64PtrOutput)
}

// Whether to skip TLS certificate verification.
func (o NotifyKafkaOutput) TlsSkipVerify() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.BoolPtrOutput { return v.TlsSkipVerify }).(pulumi.BoolPtrOutput)
}

// Kafka topic to publish event notifications to.
func (o NotifyKafkaOutput) Topic() pulumi.StringOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.StringOutput { return v.Topic }).(pulumi.StringOutput)
}

// Kafka cluster version (e.g., '2.8.0').
func (o NotifyKafkaOutput) Version() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NotifyKafka) pulumi.StringPtrOutput { return v.Version }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NotifyKafkaInput)(nil)).Elem(), &NotifyKafka{})
	pulumi.RegisterOutputType(NotifyKafkaOutput{})
}
