// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NotifyNsq struct {
	pulumi.CustomResourceState

	// Comment or description for this notification target.
	Comment pulumi.StringPtrOutput `pulumi:"comment"`
	// Whether this notification target is enabled.
	Enable pulumi.BoolPtrOutput `pulumi:"enable"`
	// Target name identifier.
	Name        pulumi.StringOutput `pulumi:"name"`
	NotifyNsqId pulumi.StringOutput `pulumi:"notifyNsqId"`
	// NSQ daemon address (e.g., 'localhost:4150').
	NsqdAddress pulumi.StringOutput `pulumi:"nsqdAddress"`
	// Directory path for persistent event store when the target is offline.
	QueueDir pulumi.StringPtrOutput `pulumi:"queueDir"`
	// Maximum number of undelivered messages to queue.
	QueueLimit pulumi.Float64Output `pulumi:"queueLimit"`
	// Indicates whether a MinIO server restart is required.
	RestartRequired pulumi.BoolOutput `pulumi:"restartRequired"`
	// Whether to enable TLS for the NSQ connection.
	Tls pulumi.BoolPtrOutput `pulumi:"tls"`
	// Whether to skip TLS certificate verification.
	TlsSkipVerify pulumi.BoolPtrOutput `pulumi:"tlsSkipVerify"`
	// NSQ topic to publish notifications to.
	Topic pulumi.StringOutput `pulumi:"topic"`
}

// NewNotifyNsq registers a new resource with the given unique name, arguments, and options.
func NewNotifyNsq(ctx *pulumi.Context,
	name string, args *NotifyNsqArgs, opts ...pulumi.ResourceOption) (*NotifyNsq, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.NsqdAddress == nil {
		return nil, errors.New("invalid value for required argument 'NsqdAddress'")
	}
	if args.Topic == nil {
		return nil, errors.New("invalid value for required argument 'Topic'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NotifyNsq
	err = ctx.RegisterPackageResource("minio:index/notifyNsq:NotifyNsq", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNotifyNsq gets an existing NotifyNsq resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNotifyNsq(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NotifyNsqState, opts ...pulumi.ResourceOption) (*NotifyNsq, error) {
	var resource NotifyNsq
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/notifyNsq:NotifyNsq", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NotifyNsq resources.
type notifyNsqState struct {
	// Comment or description for this notification target.
	Comment *string `pulumi:"comment"`
	// Whether this notification target is enabled.
	Enable *bool `pulumi:"enable"`
	// Target name identifier.
	Name        *string `pulumi:"name"`
	NotifyNsqId *string `pulumi:"notifyNsqId"`
	// NSQ daemon address (e.g., 'localhost:4150').
	NsqdAddress *string `pulumi:"nsqdAddress"`
	// Directory path for persistent event store when the target is offline.
	QueueDir *string `pulumi:"queueDir"`
	// Maximum number of undelivered messages to queue.
	QueueLimit *float64 `pulumi:"queueLimit"`
	// Indicates whether a MinIO server restart is required.
	RestartRequired *bool `pulumi:"restartRequired"`
	// Whether to enable TLS for the NSQ connection.
	Tls *bool `pulumi:"tls"`
	// Whether to skip TLS certificate verification.
	TlsSkipVerify *bool `pulumi:"tlsSkipVerify"`
	// NSQ topic to publish notifications to.
	Topic *string `pulumi:"topic"`
}

type NotifyNsqState struct {
	// Comment or description for this notification target.
	Comment pulumi.StringPtrInput
	// Whether this notification target is enabled.
	Enable pulumi.BoolPtrInput
	// Target name identifier.
	Name        pulumi.StringPtrInput
	NotifyNsqId pulumi.StringPtrInput
	// NSQ daemon address (e.g., 'localhost:4150').
	NsqdAddress pulumi.StringPtrInput
	// Directory path for persistent event store when the target is offline.
	QueueDir pulumi.StringPtrInput
	// Maximum number of undelivered messages to queue.
	QueueLimit pulumi.Float64PtrInput
	// Indicates whether a MinIO server restart is required.
	RestartRequired pulumi.BoolPtrInput
	// Whether to enable TLS for the NSQ connection.
	Tls pulumi.BoolPtrInput
	// Whether to skip TLS certificate verification.
	TlsSkipVerify pulumi.BoolPtrInput
	// NSQ topic to publish notifications to.
	Topic pulumi.StringPtrInput
}

func (NotifyNsqState) ElementType() reflect.Type {
	return reflect.TypeOf((*notifyNsqState)(nil)).Elem()
}

type notifyNsqArgs struct {
	// Comment or description for this notification target.
	Comment *string `pulumi:"comment"`
	// Whether this notification target is enabled.
	Enable *bool `pulumi:"enable"`
	// Target name identifier.
	Name        *string `pulumi:"name"`
	NotifyNsqId *string `pulumi:"notifyNsqId"`
	// NSQ daemon address (e.g., 'localhost:4150').
	NsqdAddress string `pulumi:"nsqdAddress"`
	// Directory path for persistent event store when the target is offline.
	QueueDir *string `pulumi:"queueDir"`
	// Maximum number of undelivered messages to queue.
	QueueLimit *float64 `pulumi:"queueLimit"`
	// Whether to enable TLS for the NSQ connection.
	Tls *bool `pulumi:"tls"`
	// Whether to skip TLS certificate verification.
	TlsSkipVerify *bool `pulumi:"tlsSkipVerify"`
	// NSQ topic to publish notifications to.
	Topic string `pulumi:"topic"`
}

// The set of arguments for constructing a NotifyNsq resource.
type NotifyNsqArgs struct {
	// Comment or description for this notification target.
	Comment pulumi.StringPtrInput
	// Whether this notification target is enabled.
	Enable pulumi.BoolPtrInput
	// Target name identifier.
	Name        pulumi.StringPtrInput
	NotifyNsqId pulumi.StringPtrInput
	// NSQ daemon address (e.g., 'localhost:4150').
	NsqdAddress pulumi.StringInput
	// Directory path for persistent event store when the target is offline.
	QueueDir pulumi.StringPtrInput
	// Maximum number of undelivered messages to queue.
	QueueLimit pulumi.Float64PtrInput
	// Whether to enable TLS for the NSQ connection.
	Tls pulumi.BoolPtrInput
	// Whether to skip TLS certificate verification.
	TlsSkipVerify pulumi.BoolPtrInput
	// NSQ topic to publish notifications to.
	Topic pulumi.StringInput
}

func (NotifyNsqArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*notifyNsqArgs)(nil)).Elem()
}

type NotifyNsqInput interface {
	pulumi.Input

	ToNotifyNsqOutput() NotifyNsqOutput
	ToNotifyNsqOutputWithContext(ctx context.Context) NotifyNsqOutput
}

func (*NotifyNsq) ElementType() reflect.Type {
	return reflect.TypeOf((**NotifyNsq)(nil)).Elem()
}

func (i *NotifyNsq) ToNotifyNsqOutput() NotifyNsqOutput {
	return i.ToNotifyNsqOutputWithContext(context.Background())
}

func (i *NotifyNsq) ToNotifyNsqOutputWithContext(ctx context.Context) NotifyNsqOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NotifyNsqOutput)
}

type NotifyNsqOutput struct{ *pulumi.OutputState }

func (NotifyNsqOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NotifyNsq)(nil)).Elem()
}

func (o NotifyNsqOutput) ToNotifyNsqOutput() NotifyNsqOutput {
	return o
}

func (o NotifyNsqOutput) ToNotifyNsqOutputWithContext(ctx context.Context) NotifyNsqOutput {
	return o
}

// Comment or description for this notification target.
func (o NotifyNsqOutput) Comment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NotifyNsq) pulumi.StringPtrOutput { return v.Comment }).(pulumi.StringPtrOutput)
}

// Whether this notification target is enabled.
func (o NotifyNsqOutput) Enable() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *NotifyNsq) pulumi.BoolPtrOutput { return v.Enable }).(pulumi.BoolPtrOutput)
}

// Target name identifier.
func (o NotifyNsqOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NotifyNsq) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o NotifyNsqOutput) NotifyNsqId() pulumi.StringOutput {
	return o.ApplyT(func(v *NotifyNsq) pulumi.StringOutput { return v.NotifyNsqId }).(pulumi.StringOutput)
}

// NSQ daemon address (e.g., 'localhost:4150').
func (o NotifyNsqOutput) NsqdAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *NotifyNsq) pulumi.StringOutput { return v.NsqdAddress }).(pulumi.StringOutput)
}

// Directory path for persistent event store when the target is offline.
func (o NotifyNsqOutput) QueueDir() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NotifyNsq) pulumi.StringPtrOutput { return v.QueueDir }).(pulumi.StringPtrOutput)
}

// Maximum number of undelivered messages to queue.
func (o NotifyNsqOutput) QueueLimit() pulumi.Float64Output {
	return o.ApplyT(func(v *NotifyNsq) pulumi.Float64Output { return v.QueueLimit }).(pulumi.Float64Output)
}

// Indicates whether a MinIO server restart is required.
func (o NotifyNsqOutput) RestartRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v *NotifyNsq) pulumi.BoolOutput { return v.RestartRequired }).(pulumi.BoolOutput)
}

// Whether to enable TLS for the NSQ connection.
func (o NotifyNsqOutput) Tls() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *NotifyNsq) pulumi.BoolPtrOutput { return v.Tls }).(pulumi.BoolPtrOutput)
}

// Whether to skip TLS certificate verification.
func (o NotifyNsqOutput) TlsSkipVerify() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *NotifyNsq) pulumi.BoolPtrOutput { return v.TlsSkipVerify }).(pulumi.BoolPtrOutput)
}

// NSQ topic to publish notifications to.
func (o NotifyNsqOutput) Topic() pulumi.StringOutput {
	return o.ApplyT(func(v *NotifyNsq) pulumi.StringOutput { return v.Topic }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NotifyNsqInput)(nil)).Elem(), &NotifyNsq{})
	pulumi.RegisterOutputType(NotifyNsqOutput{})
}
