// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type PoolDecommission struct {
	pulumi.CustomResourceState

	PoolDecommissionId pulumi.StringOutput `pulumi:"poolDecommissionId"`
	// Pool ID to decommission, as reported by the <span pulumi-lang-nodejs="`index`" pulumi-lang-dotnet="`Index`" pulumi-lang-go="`index`" pulumi-lang-python="`index`" pulumi-lang-yaml="`index`" pulumi-lang-java="`index`" pulumi-lang-hcl="`index`">`index`</span> attribute of the <span pulumi-lang-nodejs="`minio.getPoolStatus`" pulumi-lang-dotnet="`minio.getPoolStatus`" pulumi-lang-go="`getPoolStatus`" pulumi-lang-python="`get_pool_status`" pulumi-lang-yaml="`minio.getPoolStatus`" pulumi-lang-java="`minio.getPoolStatus`" pulumi-lang-hcl="`data.minio_pool_status`">`minio.getPoolStatus`</span> data source.
	PoolIndex pulumi.Float64Output `pulumi:"poolIndex"`
	// RFC3339 timestamp when decommission started. Empty when imported after the pool has already been removed.
	StartedAt pulumi.StringOutput `pulumi:"startedAt"`
	// Current state of the decommission: <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`" pulumi-lang-hcl="`decommissioning`">`decommissioning`</span>, <span pulumi-lang-nodejs="`decommissioned`" pulumi-lang-dotnet="`Decommissioned`" pulumi-lang-go="`decommissioned`" pulumi-lang-python="`decommissioned`" pulumi-lang-yaml="`decommissioned`" pulumi-lang-java="`decommissioned`" pulumi-lang-hcl="`decommissioned`">`decommissioned`</span>, <span pulumi-lang-nodejs="`canceled`" pulumi-lang-dotnet="`Canceled`" pulumi-lang-go="`canceled`" pulumi-lang-python="`canceled`" pulumi-lang-yaml="`canceled`" pulumi-lang-java="`canceled`" pulumi-lang-hcl="`canceled`">`canceled`</span>, or <span pulumi-lang-nodejs="`failed`" pulumi-lang-dotnet="`Failed`" pulumi-lang-go="`failed`" pulumi-lang-python="`failed`" pulumi-lang-yaml="`failed`" pulumi-lang-java="`failed`" pulumi-lang-hcl="`failed`">`failed`</span>.
	State pulumi.StringOutput `pulumi:"state"`
	// JSON-marshalled MinIO `PoolDecommissionInfo` snapshot, or an empty string when the pool has already been removed from the cluster.
	Status pulumi.StringOutput `pulumi:"status"`
}

// NewPoolDecommission registers a new resource with the given unique name, arguments, and options.
func NewPoolDecommission(ctx *pulumi.Context,
	name string, args *PoolDecommissionArgs, opts ...pulumi.ResourceOption) (*PoolDecommission, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PoolIndex == nil {
		return nil, errors.New("invalid value for required argument 'PoolIndex'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource PoolDecommission
	err = ctx.RegisterPackageResource("minio:index/poolDecommission:PoolDecommission", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPoolDecommission gets an existing PoolDecommission resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPoolDecommission(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PoolDecommissionState, opts ...pulumi.ResourceOption) (*PoolDecommission, error) {
	var resource PoolDecommission
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/poolDecommission:PoolDecommission", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PoolDecommission resources.
type poolDecommissionState struct {
	PoolDecommissionId *string `pulumi:"poolDecommissionId"`
	// Pool ID to decommission, as reported by the <span pulumi-lang-nodejs="`index`" pulumi-lang-dotnet="`Index`" pulumi-lang-go="`index`" pulumi-lang-python="`index`" pulumi-lang-yaml="`index`" pulumi-lang-java="`index`" pulumi-lang-hcl="`index`">`index`</span> attribute of the <span pulumi-lang-nodejs="`minio.getPoolStatus`" pulumi-lang-dotnet="`minio.getPoolStatus`" pulumi-lang-go="`getPoolStatus`" pulumi-lang-python="`get_pool_status`" pulumi-lang-yaml="`minio.getPoolStatus`" pulumi-lang-java="`minio.getPoolStatus`" pulumi-lang-hcl="`data.minio_pool_status`">`minio.getPoolStatus`</span> data source.
	PoolIndex *float64 `pulumi:"poolIndex"`
	// RFC3339 timestamp when decommission started. Empty when imported after the pool has already been removed.
	StartedAt *string `pulumi:"startedAt"`
	// Current state of the decommission: <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`" pulumi-lang-hcl="`decommissioning`">`decommissioning`</span>, <span pulumi-lang-nodejs="`decommissioned`" pulumi-lang-dotnet="`Decommissioned`" pulumi-lang-go="`decommissioned`" pulumi-lang-python="`decommissioned`" pulumi-lang-yaml="`decommissioned`" pulumi-lang-java="`decommissioned`" pulumi-lang-hcl="`decommissioned`">`decommissioned`</span>, <span pulumi-lang-nodejs="`canceled`" pulumi-lang-dotnet="`Canceled`" pulumi-lang-go="`canceled`" pulumi-lang-python="`canceled`" pulumi-lang-yaml="`canceled`" pulumi-lang-java="`canceled`" pulumi-lang-hcl="`canceled`">`canceled`</span>, or <span pulumi-lang-nodejs="`failed`" pulumi-lang-dotnet="`Failed`" pulumi-lang-go="`failed`" pulumi-lang-python="`failed`" pulumi-lang-yaml="`failed`" pulumi-lang-java="`failed`" pulumi-lang-hcl="`failed`">`failed`</span>.
	State *string `pulumi:"state"`
	// JSON-marshalled MinIO `PoolDecommissionInfo` snapshot, or an empty string when the pool has already been removed from the cluster.
	Status *string `pulumi:"status"`
}

type PoolDecommissionState struct {
	PoolDecommissionId pulumi.StringPtrInput
	// Pool ID to decommission, as reported by the <span pulumi-lang-nodejs="`index`" pulumi-lang-dotnet="`Index`" pulumi-lang-go="`index`" pulumi-lang-python="`index`" pulumi-lang-yaml="`index`" pulumi-lang-java="`index`" pulumi-lang-hcl="`index`">`index`</span> attribute of the <span pulumi-lang-nodejs="`minio.getPoolStatus`" pulumi-lang-dotnet="`minio.getPoolStatus`" pulumi-lang-go="`getPoolStatus`" pulumi-lang-python="`get_pool_status`" pulumi-lang-yaml="`minio.getPoolStatus`" pulumi-lang-java="`minio.getPoolStatus`" pulumi-lang-hcl="`data.minio_pool_status`">`minio.getPoolStatus`</span> data source.
	PoolIndex pulumi.Float64PtrInput
	// RFC3339 timestamp when decommission started. Empty when imported after the pool has already been removed.
	StartedAt pulumi.StringPtrInput
	// Current state of the decommission: <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`" pulumi-lang-hcl="`decommissioning`">`decommissioning`</span>, <span pulumi-lang-nodejs="`decommissioned`" pulumi-lang-dotnet="`Decommissioned`" pulumi-lang-go="`decommissioned`" pulumi-lang-python="`decommissioned`" pulumi-lang-yaml="`decommissioned`" pulumi-lang-java="`decommissioned`" pulumi-lang-hcl="`decommissioned`">`decommissioned`</span>, <span pulumi-lang-nodejs="`canceled`" pulumi-lang-dotnet="`Canceled`" pulumi-lang-go="`canceled`" pulumi-lang-python="`canceled`" pulumi-lang-yaml="`canceled`" pulumi-lang-java="`canceled`" pulumi-lang-hcl="`canceled`">`canceled`</span>, or <span pulumi-lang-nodejs="`failed`" pulumi-lang-dotnet="`Failed`" pulumi-lang-go="`failed`" pulumi-lang-python="`failed`" pulumi-lang-yaml="`failed`" pulumi-lang-java="`failed`" pulumi-lang-hcl="`failed`">`failed`</span>.
	State pulumi.StringPtrInput
	// JSON-marshalled MinIO `PoolDecommissionInfo` snapshot, or an empty string when the pool has already been removed from the cluster.
	Status pulumi.StringPtrInput
}

func (PoolDecommissionState) ElementType() reflect.Type {
	return reflect.TypeOf((*poolDecommissionState)(nil)).Elem()
}

type poolDecommissionArgs struct {
	PoolDecommissionId *string `pulumi:"poolDecommissionId"`
	// Pool ID to decommission, as reported by the <span pulumi-lang-nodejs="`index`" pulumi-lang-dotnet="`Index`" pulumi-lang-go="`index`" pulumi-lang-python="`index`" pulumi-lang-yaml="`index`" pulumi-lang-java="`index`" pulumi-lang-hcl="`index`">`index`</span> attribute of the <span pulumi-lang-nodejs="`minio.getPoolStatus`" pulumi-lang-dotnet="`minio.getPoolStatus`" pulumi-lang-go="`getPoolStatus`" pulumi-lang-python="`get_pool_status`" pulumi-lang-yaml="`minio.getPoolStatus`" pulumi-lang-java="`minio.getPoolStatus`" pulumi-lang-hcl="`data.minio_pool_status`">`minio.getPoolStatus`</span> data source.
	PoolIndex float64 `pulumi:"poolIndex"`
}

// The set of arguments for constructing a PoolDecommission resource.
type PoolDecommissionArgs struct {
	PoolDecommissionId pulumi.StringPtrInput
	// Pool ID to decommission, as reported by the <span pulumi-lang-nodejs="`index`" pulumi-lang-dotnet="`Index`" pulumi-lang-go="`index`" pulumi-lang-python="`index`" pulumi-lang-yaml="`index`" pulumi-lang-java="`index`" pulumi-lang-hcl="`index`">`index`</span> attribute of the <span pulumi-lang-nodejs="`minio.getPoolStatus`" pulumi-lang-dotnet="`minio.getPoolStatus`" pulumi-lang-go="`getPoolStatus`" pulumi-lang-python="`get_pool_status`" pulumi-lang-yaml="`minio.getPoolStatus`" pulumi-lang-java="`minio.getPoolStatus`" pulumi-lang-hcl="`data.minio_pool_status`">`minio.getPoolStatus`</span> data source.
	PoolIndex pulumi.Float64Input
}

func (PoolDecommissionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*poolDecommissionArgs)(nil)).Elem()
}

type PoolDecommissionInput interface {
	pulumi.Input

	ToPoolDecommissionOutput() PoolDecommissionOutput
	ToPoolDecommissionOutputWithContext(ctx context.Context) PoolDecommissionOutput
}

func (*PoolDecommission) ElementType() reflect.Type {
	return reflect.TypeOf((**PoolDecommission)(nil)).Elem()
}

func (i *PoolDecommission) ToPoolDecommissionOutput() PoolDecommissionOutput {
	return i.ToPoolDecommissionOutputWithContext(context.Background())
}

func (i *PoolDecommission) ToPoolDecommissionOutputWithContext(ctx context.Context) PoolDecommissionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PoolDecommissionOutput)
}

type PoolDecommissionOutput struct{ *pulumi.OutputState }

func (PoolDecommissionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PoolDecommission)(nil)).Elem()
}

func (o PoolDecommissionOutput) ToPoolDecommissionOutput() PoolDecommissionOutput {
	return o
}

func (o PoolDecommissionOutput) ToPoolDecommissionOutputWithContext(ctx context.Context) PoolDecommissionOutput {
	return o
}

func (o PoolDecommissionOutput) PoolDecommissionId() pulumi.StringOutput {
	return o.ApplyT(func(v *PoolDecommission) pulumi.StringOutput { return v.PoolDecommissionId }).(pulumi.StringOutput)
}

// Pool ID to decommission, as reported by the <span pulumi-lang-nodejs="`index`" pulumi-lang-dotnet="`Index`" pulumi-lang-go="`index`" pulumi-lang-python="`index`" pulumi-lang-yaml="`index`" pulumi-lang-java="`index`" pulumi-lang-hcl="`index`">`index`</span> attribute of the <span pulumi-lang-nodejs="`minio.getPoolStatus`" pulumi-lang-dotnet="`minio.getPoolStatus`" pulumi-lang-go="`getPoolStatus`" pulumi-lang-python="`get_pool_status`" pulumi-lang-yaml="`minio.getPoolStatus`" pulumi-lang-java="`minio.getPoolStatus`" pulumi-lang-hcl="`data.minio_pool_status`">`minio.getPoolStatus`</span> data source.
func (o PoolDecommissionOutput) PoolIndex() pulumi.Float64Output {
	return o.ApplyT(func(v *PoolDecommission) pulumi.Float64Output { return v.PoolIndex }).(pulumi.Float64Output)
}

// RFC3339 timestamp when decommission started. Empty when imported after the pool has already been removed.
func (o PoolDecommissionOutput) StartedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *PoolDecommission) pulumi.StringOutput { return v.StartedAt }).(pulumi.StringOutput)
}

// Current state of the decommission: <span pulumi-lang-nodejs="`decommissioning`" pulumi-lang-dotnet="`Decommissioning`" pulumi-lang-go="`decommissioning`" pulumi-lang-python="`decommissioning`" pulumi-lang-yaml="`decommissioning`" pulumi-lang-java="`decommissioning`" pulumi-lang-hcl="`decommissioning`">`decommissioning`</span>, <span pulumi-lang-nodejs="`decommissioned`" pulumi-lang-dotnet="`Decommissioned`" pulumi-lang-go="`decommissioned`" pulumi-lang-python="`decommissioned`" pulumi-lang-yaml="`decommissioned`" pulumi-lang-java="`decommissioned`" pulumi-lang-hcl="`decommissioned`">`decommissioned`</span>, <span pulumi-lang-nodejs="`canceled`" pulumi-lang-dotnet="`Canceled`" pulumi-lang-go="`canceled`" pulumi-lang-python="`canceled`" pulumi-lang-yaml="`canceled`" pulumi-lang-java="`canceled`" pulumi-lang-hcl="`canceled`">`canceled`</span>, or <span pulumi-lang-nodejs="`failed`" pulumi-lang-dotnet="`Failed`" pulumi-lang-go="`failed`" pulumi-lang-python="`failed`" pulumi-lang-yaml="`failed`" pulumi-lang-java="`failed`" pulumi-lang-hcl="`failed`">`failed`</span>.
func (o PoolDecommissionOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *PoolDecommission) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

// JSON-marshalled MinIO `PoolDecommissionInfo` snapshot, or an empty string when the pool has already been removed from the cluster.
func (o PoolDecommissionOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *PoolDecommission) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PoolDecommissionInput)(nil)).Elem(), &PoolDecommission{})
	pulumi.RegisterOutputType(PoolDecommissionOutput{})
}
