// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the minio package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// MinIO access key (deprecated: use<span pulumi-lang-nodejs=" minioUser " pulumi-lang-dotnet=" MinioUser " pulumi-lang-go=" minioUser " pulumi-lang-python=" minio_user " pulumi-lang-yaml=" minioUser " pulumi-lang-java=" minioUser " pulumi-lang-hcl=" minio_user "> minioUser </span>instead)
	//
	// Deprecated: Deprecated
	MinioAccessKey pulumi.StringPtrOutput `pulumi:"minioAccessKey"`
	// MinIO API Version (v2 or v4)
	MinioApiVersion pulumi.StringPtrOutput `pulumi:"minioApiVersion"`
	// Path to CA certificate file for SSL verification
	MinioCacertFile pulumi.StringPtrOutput `pulumi:"minioCacertFile"`
	// Path to client certificate file for SSL authentication
	MinioCertFile pulumi.StringPtrOutput `pulumi:"minioCertFile"`
	// Override the auto-detected MinIO edition (e.g. `AIStor` to force AIStor-shaped behaviors). Leave empty to auto-detect from `ServerInfo`. Set this only when the provider misclassifies your server — for example an AIStor build whose `ServerInfo` response does not surface the <span pulumi-lang-nodejs="`edition`" pulumi-lang-dotnet="`Edition`" pulumi-lang-go="`edition`" pulumi-lang-python="`edition`" pulumi-lang-yaml="`edition`" pulumi-lang-java="`edition`" pulumi-lang-hcl="`edition`">`edition`</span> field.
	MinioEdition pulumi.StringPtrOutput `pulumi:"minioEdition"`
	// Path to client private key file for SSL authentication
	MinioKeyFile pulumi.StringPtrOutput `pulumi:"minioKeyFile"`
	// MinIO password (or secret key) for authentication
	MinioPassword pulumi.StringPtrOutput `pulumi:"minioPassword"`
	// Region used for request signing and sent to the S3 client. Defaults to `us-east-1`. Set this to match the region configured on your server, or to any non-empty string when using S3-compatible stores that require a specific region (e.g. Versity Gateway, Hetzner Object Storage).
	MinioRegion pulumi.StringPtrOutput `pulumi:"minioRegion"`
	// MinIO secret key (deprecated: use<span pulumi-lang-nodejs=" minioPassword " pulumi-lang-dotnet=" MinioPassword " pulumi-lang-go=" minioPassword " pulumi-lang-python=" minio_password " pulumi-lang-yaml=" minioPassword " pulumi-lang-java=" minioPassword " pulumi-lang-hcl=" minio_password "> minioPassword </span>instead)
	//
	// Deprecated: Deprecated
	MinioSecretKey pulumi.StringPtrOutput `pulumi:"minioSecretKey"`
	// MinIO server endpoint in the format host:port
	MinioServer pulumi.StringOutput `pulumi:"minioServer"`
	// MinIO session token for temporary credentials
	MinioSessionToken pulumi.StringPtrOutput `pulumi:"minioSessionToken"`
	// MinIO user (or access key) for authentication
	MinioUser pulumi.StringPtrOutput `pulumi:"minioUser"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.MinioServer == nil {
		return nil, errors.New("invalid value for required argument 'MinioServer'")
	}
	if args.MinioKeyFile != nil {
		args.MinioKeyFile = pulumi.ToSecret(args.MinioKeyFile).(pulumi.StringPtrInput)
	}
	if args.MinioPassword != nil {
		args.MinioPassword = pulumi.ToSecret(args.MinioPassword).(pulumi.StringPtrInput)
	}
	if args.MinioSecretKey != nil {
		args.MinioSecretKey = pulumi.ToSecret(args.MinioSecretKey).(pulumi.StringPtrInput)
	}
	if args.MinioSessionToken != nil {
		args.MinioSessionToken = pulumi.ToSecret(args.MinioSessionToken).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"minioKeyFile",
		"minioPassword",
		"minioSecretKey",
		"minioSessionToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Provider
	err = ctx.RegisterPackageResource("pulumi:providers:minio", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// Use STS AssumeRole to obtain temporary credentials. When configured, the provider exchanges the static credentials for short-lived session credentials.
	AssumeRole *ProviderAssumeRole `pulumi:"assumeRole"`
	// Use STS AssumeRoleWithWebIdentity to obtain credentials from an OIDC token (e.g., GitHub Actions, GitLab CI).
	AssumeRoleWithWebIdentity *ProviderAssumeRoleWithWebIdentity `pulumi:"assumeRoleWithWebIdentity"`
	// Maximum number of retries for failed operations (default: 6)
	MaxRetries *float64 `pulumi:"maxRetries"`
	// MinIO access key (deprecated: use<span pulumi-lang-nodejs=" minioUser " pulumi-lang-dotnet=" MinioUser " pulumi-lang-go=" minioUser " pulumi-lang-python=" minio_user " pulumi-lang-yaml=" minioUser " pulumi-lang-java=" minioUser " pulumi-lang-hcl=" minio_user "> minioUser </span>instead)
	//
	// Deprecated: Deprecated
	MinioAccessKey *string `pulumi:"minioAccessKey"`
	// MinIO API Version (v2 or v4)
	MinioApiVersion *string `pulumi:"minioApiVersion"`
	// Path to CA certificate file for SSL verification
	MinioCacertFile *string `pulumi:"minioCacertFile"`
	// Path to client certificate file for SSL authentication
	MinioCertFile *string `pulumi:"minioCertFile"`
	// Enable debug logging for API requests
	MinioDebug *bool `pulumi:"minioDebug"`
	// Override the auto-detected MinIO edition (e.g. `AIStor` to force AIStor-shaped behaviors). Leave empty to auto-detect from `ServerInfo`. Set this only when the provider misclassifies your server — for example an AIStor build whose `ServerInfo` response does not surface the <span pulumi-lang-nodejs="`edition`" pulumi-lang-dotnet="`Edition`" pulumi-lang-go="`edition`" pulumi-lang-python="`edition`" pulumi-lang-yaml="`edition`" pulumi-lang-java="`edition`" pulumi-lang-hcl="`edition`">`edition`</span> field.
	MinioEdition *string `pulumi:"minioEdition"`
	// Skip SSL certificate verification (not recommended for production)
	MinioInsecure *bool `pulumi:"minioInsecure"`
	// Path to client private key file for SSL authentication
	MinioKeyFile *string `pulumi:"minioKeyFile"`
	// MinIO password (or secret key) for authentication
	MinioPassword *string `pulumi:"minioPassword"`
	// Region used for request signing and sent to the S3 client. Defaults to `us-east-1`. Set this to match the region configured on your server, or to any non-empty string when using S3-compatible stores that require a specific region (e.g. Versity Gateway, Hetzner Object Storage).
	MinioRegion *string `pulumi:"minioRegion"`
	// MinIO secret key (deprecated: use<span pulumi-lang-nodejs=" minioPassword " pulumi-lang-dotnet=" MinioPassword " pulumi-lang-go=" minioPassword " pulumi-lang-python=" minio_password " pulumi-lang-yaml=" minioPassword " pulumi-lang-java=" minioPassword " pulumi-lang-hcl=" minio_password "> minioPassword </span>instead)
	//
	// Deprecated: Deprecated
	MinioSecretKey *string `pulumi:"minioSecretKey"`
	// MinIO server endpoint in the format host:port
	MinioServer string `pulumi:"minioServer"`
	// MinIO session token for temporary credentials
	MinioSessionToken *string `pulumi:"minioSessionToken"`
	// Enable SSL/TLS for MinIO connection
	MinioSsl *bool `pulumi:"minioSsl"`
	// MinIO user (or access key) for authentication
	MinioUser *string `pulumi:"minioUser"`
	// Global HTTP request timeout in seconds for all MinIO API calls (default: 30)
	RequestTimeoutSeconds *float64 `pulumi:"requestTimeoutSeconds"`
	// Base delay in milliseconds between retries, used with exponential backoff (default: 1000)
	RetryDelayMs *float64 `pulumi:"retryDelayMs"`
	// Enable S3 compatibility mode for non-MinIO backends (Hetzner, Cloudflare R2, Backblaze B2, DigitalOcean Spaces). Gracefully handles unsupported S3 features instead of erroring.
	S3CompatMode *bool `pulumi:"s3CompatMode"`
	// Skip bucket tagging API calls. Useful when your S3-compatible endpoint does not support tagging.
	SkipBucketTagging *bool `pulumi:"skipBucketTagging"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// Use STS AssumeRole to obtain temporary credentials. When configured, the provider exchanges the static credentials for short-lived session credentials.
	AssumeRole ProviderAssumeRolePtrInput
	// Use STS AssumeRoleWithWebIdentity to obtain credentials from an OIDC token (e.g., GitHub Actions, GitLab CI).
	AssumeRoleWithWebIdentity ProviderAssumeRoleWithWebIdentityPtrInput
	// Maximum number of retries for failed operations (default: 6)
	MaxRetries pulumi.Float64PtrInput
	// MinIO access key (deprecated: use<span pulumi-lang-nodejs=" minioUser " pulumi-lang-dotnet=" MinioUser " pulumi-lang-go=" minioUser " pulumi-lang-python=" minio_user " pulumi-lang-yaml=" minioUser " pulumi-lang-java=" minioUser " pulumi-lang-hcl=" minio_user "> minioUser </span>instead)
	//
	// Deprecated: Deprecated
	MinioAccessKey pulumi.StringPtrInput
	// MinIO API Version (v2 or v4)
	MinioApiVersion pulumi.StringPtrInput
	// Path to CA certificate file for SSL verification
	MinioCacertFile pulumi.StringPtrInput
	// Path to client certificate file for SSL authentication
	MinioCertFile pulumi.StringPtrInput
	// Enable debug logging for API requests
	MinioDebug pulumi.BoolPtrInput
	// Override the auto-detected MinIO edition (e.g. `AIStor` to force AIStor-shaped behaviors). Leave empty to auto-detect from `ServerInfo`. Set this only when the provider misclassifies your server — for example an AIStor build whose `ServerInfo` response does not surface the <span pulumi-lang-nodejs="`edition`" pulumi-lang-dotnet="`Edition`" pulumi-lang-go="`edition`" pulumi-lang-python="`edition`" pulumi-lang-yaml="`edition`" pulumi-lang-java="`edition`" pulumi-lang-hcl="`edition`">`edition`</span> field.
	MinioEdition pulumi.StringPtrInput
	// Skip SSL certificate verification (not recommended for production)
	MinioInsecure pulumi.BoolPtrInput
	// Path to client private key file for SSL authentication
	MinioKeyFile pulumi.StringPtrInput
	// MinIO password (or secret key) for authentication
	MinioPassword pulumi.StringPtrInput
	// Region used for request signing and sent to the S3 client. Defaults to `us-east-1`. Set this to match the region configured on your server, or to any non-empty string when using S3-compatible stores that require a specific region (e.g. Versity Gateway, Hetzner Object Storage).
	MinioRegion pulumi.StringPtrInput
	// MinIO secret key (deprecated: use<span pulumi-lang-nodejs=" minioPassword " pulumi-lang-dotnet=" MinioPassword " pulumi-lang-go=" minioPassword " pulumi-lang-python=" minio_password " pulumi-lang-yaml=" minioPassword " pulumi-lang-java=" minioPassword " pulumi-lang-hcl=" minio_password "> minioPassword </span>instead)
	//
	// Deprecated: Deprecated
	MinioSecretKey pulumi.StringPtrInput
	// MinIO server endpoint in the format host:port
	MinioServer pulumi.StringInput
	// MinIO session token for temporary credentials
	MinioSessionToken pulumi.StringPtrInput
	// Enable SSL/TLS for MinIO connection
	MinioSsl pulumi.BoolPtrInput
	// MinIO user (or access key) for authentication
	MinioUser pulumi.StringPtrInput
	// Global HTTP request timeout in seconds for all MinIO API calls (default: 30)
	RequestTimeoutSeconds pulumi.Float64PtrInput
	// Base delay in milliseconds between retries, used with exponential backoff (default: 1000)
	RetryDelayMs pulumi.Float64PtrInput
	// Enable S3 compatibility mode for non-MinIO backends (Hetzner, Cloudflare R2, Backblaze B2, DigitalOcean Spaces). Gracefully handles unsupported S3 features instead of erroring.
	S3CompatMode pulumi.BoolPtrInput
	// Skip bucket tagging API calls. Useful when your S3-compatible endpoint does not support tagging.
	SkipBucketTagging pulumi.BoolPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

// This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
func (r *Provider) TerraformConfig(ctx *pulumi.Context) (pulumi.MapOutput, error) {
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return pulumi.MapOutput{}, err
	}
	out, err := ctx.CallPackage("pulumi:providers:minio/terraformConfig", nil, providerTerraformConfigResultOutput{}, r, ref)
	if err != nil {
		return pulumi.MapOutput{}, err
	}
	return out.(providerTerraformConfigResultOutput).Result(), nil
}

type providerTerraformConfigResult struct {
	Result map[string]interface{} `pulumi:"result"`
}

type providerTerraformConfigResultOutput struct{ *pulumi.OutputState }

func (providerTerraformConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*providerTerraformConfigResult)(nil)).Elem()
}

func (o providerTerraformConfigResultOutput) Result() pulumi.MapOutput {
	return o.ApplyT(func(v providerTerraformConfigResult) map[string]interface{} { return v.Result }).(pulumi.MapOutput)
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// MinIO access key (deprecated: use<span pulumi-lang-nodejs=" minioUser " pulumi-lang-dotnet=" MinioUser " pulumi-lang-go=" minioUser " pulumi-lang-python=" minio_user " pulumi-lang-yaml=" minioUser " pulumi-lang-java=" minioUser " pulumi-lang-hcl=" minio_user "> minioUser </span>instead)
//
// Deprecated: Deprecated
func (o ProviderOutput) MinioAccessKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioAccessKey }).(pulumi.StringPtrOutput)
}

// MinIO API Version (v2 or v4)
func (o ProviderOutput) MinioApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioApiVersion }).(pulumi.StringPtrOutput)
}

// Path to CA certificate file for SSL verification
func (o ProviderOutput) MinioCacertFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioCacertFile }).(pulumi.StringPtrOutput)
}

// Path to client certificate file for SSL authentication
func (o ProviderOutput) MinioCertFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioCertFile }).(pulumi.StringPtrOutput)
}

// Override the auto-detected MinIO edition (e.g. `AIStor` to force AIStor-shaped behaviors). Leave empty to auto-detect from `ServerInfo`. Set this only when the provider misclassifies your server — for example an AIStor build whose `ServerInfo` response does not surface the <span pulumi-lang-nodejs="`edition`" pulumi-lang-dotnet="`Edition`" pulumi-lang-go="`edition`" pulumi-lang-python="`edition`" pulumi-lang-yaml="`edition`" pulumi-lang-java="`edition`" pulumi-lang-hcl="`edition`">`edition`</span> field.
func (o ProviderOutput) MinioEdition() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioEdition }).(pulumi.StringPtrOutput)
}

// Path to client private key file for SSL authentication
func (o ProviderOutput) MinioKeyFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioKeyFile }).(pulumi.StringPtrOutput)
}

// MinIO password (or secret key) for authentication
func (o ProviderOutput) MinioPassword() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioPassword }).(pulumi.StringPtrOutput)
}

// Region used for request signing and sent to the S3 client. Defaults to `us-east-1`. Set this to match the region configured on your server, or to any non-empty string when using S3-compatible stores that require a specific region (e.g. Versity Gateway, Hetzner Object Storage).
func (o ProviderOutput) MinioRegion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioRegion }).(pulumi.StringPtrOutput)
}

// MinIO secret key (deprecated: use<span pulumi-lang-nodejs=" minioPassword " pulumi-lang-dotnet=" MinioPassword " pulumi-lang-go=" minioPassword " pulumi-lang-python=" minio_password " pulumi-lang-yaml=" minioPassword " pulumi-lang-java=" minioPassword " pulumi-lang-hcl=" minio_password "> minioPassword </span>instead)
//
// Deprecated: Deprecated
func (o ProviderOutput) MinioSecretKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioSecretKey }).(pulumi.StringPtrOutput)
}

// MinIO server endpoint in the format host:port
func (o ProviderOutput) MinioServer() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.MinioServer }).(pulumi.StringOutput)
}

// MinIO session token for temporary credentials
func (o ProviderOutput) MinioSessionToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioSessionToken }).(pulumi.StringPtrOutput)
}

// MinIO user (or access key) for authentication
func (o ProviderOutput) MinioUser() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioUser }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
	pulumi.RegisterOutputType(providerTerraformConfigResultOutput{})
}
