// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type S3BucketAnonymousAccess struct {
	pulumi.CustomResourceState

	// Canned access type for anonymous access
	AccessType pulumi.StringPtrOutput `pulumi:"accessType"`
	// Name of the bucket
	Bucket pulumi.StringOutput `pulumi:"bucket"`
	// Custom policy JSON string for anonymous access. For canned policies (public, public-read, public-read-write, public-write), use the<span pulumi-lang-nodejs=" accessType " pulumi-lang-dotnet=" AccessType " pulumi-lang-go=" accessType " pulumi-lang-python=" access_type " pulumi-lang-yaml=" accessType " pulumi-lang-java=" accessType " pulumi-lang-hcl=" access_type "> accessType </span>field instead.
	Policy                    pulumi.StringOutput                      `pulumi:"policy"`
	S3BucketAnonymousAccessId pulumi.StringOutput                      `pulumi:"s3BucketAnonymousAccessId"`
	Timeouts                  S3BucketAnonymousAccessTimeoutsPtrOutput `pulumi:"timeouts"`
}

// NewS3BucketAnonymousAccess registers a new resource with the given unique name, arguments, and options.
func NewS3BucketAnonymousAccess(ctx *pulumi.Context,
	name string, args *S3BucketAnonymousAccessArgs, opts ...pulumi.ResourceOption) (*S3BucketAnonymousAccess, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Bucket == nil {
		return nil, errors.New("invalid value for required argument 'Bucket'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource S3BucketAnonymousAccess
	err = ctx.RegisterPackageResource("minio:index/s3BucketAnonymousAccess:S3BucketAnonymousAccess", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetS3BucketAnonymousAccess gets an existing S3BucketAnonymousAccess resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetS3BucketAnonymousAccess(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *S3BucketAnonymousAccessState, opts ...pulumi.ResourceOption) (*S3BucketAnonymousAccess, error) {
	var resource S3BucketAnonymousAccess
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/s3BucketAnonymousAccess:S3BucketAnonymousAccess", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering S3BucketAnonymousAccess resources.
type s3bucketAnonymousAccessState struct {
	// Canned access type for anonymous access
	AccessType *string `pulumi:"accessType"`
	// Name of the bucket
	Bucket *string `pulumi:"bucket"`
	// Custom policy JSON string for anonymous access. For canned policies (public, public-read, public-read-write, public-write), use the<span pulumi-lang-nodejs=" accessType " pulumi-lang-dotnet=" AccessType " pulumi-lang-go=" accessType " pulumi-lang-python=" access_type " pulumi-lang-yaml=" accessType " pulumi-lang-java=" accessType " pulumi-lang-hcl=" access_type "> accessType </span>field instead.
	Policy                    *string                          `pulumi:"policy"`
	S3BucketAnonymousAccessId *string                          `pulumi:"s3BucketAnonymousAccessId"`
	Timeouts                  *S3BucketAnonymousAccessTimeouts `pulumi:"timeouts"`
}

type S3BucketAnonymousAccessState struct {
	// Canned access type for anonymous access
	AccessType pulumi.StringPtrInput
	// Name of the bucket
	Bucket pulumi.StringPtrInput
	// Custom policy JSON string for anonymous access. For canned policies (public, public-read, public-read-write, public-write), use the<span pulumi-lang-nodejs=" accessType " pulumi-lang-dotnet=" AccessType " pulumi-lang-go=" accessType " pulumi-lang-python=" access_type " pulumi-lang-yaml=" accessType " pulumi-lang-java=" accessType " pulumi-lang-hcl=" access_type "> accessType </span>field instead.
	Policy                    pulumi.StringPtrInput
	S3BucketAnonymousAccessId pulumi.StringPtrInput
	Timeouts                  S3BucketAnonymousAccessTimeoutsPtrInput
}

func (S3BucketAnonymousAccessState) ElementType() reflect.Type {
	return reflect.TypeOf((*s3bucketAnonymousAccessState)(nil)).Elem()
}

type s3bucketAnonymousAccessArgs struct {
	// Canned access type for anonymous access
	AccessType *string `pulumi:"accessType"`
	// Name of the bucket
	Bucket string `pulumi:"bucket"`
	// Custom policy JSON string for anonymous access. For canned policies (public, public-read, public-read-write, public-write), use the<span pulumi-lang-nodejs=" accessType " pulumi-lang-dotnet=" AccessType " pulumi-lang-go=" accessType " pulumi-lang-python=" access_type " pulumi-lang-yaml=" accessType " pulumi-lang-java=" accessType " pulumi-lang-hcl=" access_type "> accessType </span>field instead.
	Policy                    *string                          `pulumi:"policy"`
	S3BucketAnonymousAccessId *string                          `pulumi:"s3BucketAnonymousAccessId"`
	Timeouts                  *S3BucketAnonymousAccessTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a S3BucketAnonymousAccess resource.
type S3BucketAnonymousAccessArgs struct {
	// Canned access type for anonymous access
	AccessType pulumi.StringPtrInput
	// Name of the bucket
	Bucket pulumi.StringInput
	// Custom policy JSON string for anonymous access. For canned policies (public, public-read, public-read-write, public-write), use the<span pulumi-lang-nodejs=" accessType " pulumi-lang-dotnet=" AccessType " pulumi-lang-go=" accessType " pulumi-lang-python=" access_type " pulumi-lang-yaml=" accessType " pulumi-lang-java=" accessType " pulumi-lang-hcl=" access_type "> accessType </span>field instead.
	Policy                    pulumi.StringPtrInput
	S3BucketAnonymousAccessId pulumi.StringPtrInput
	Timeouts                  S3BucketAnonymousAccessTimeoutsPtrInput
}

func (S3BucketAnonymousAccessArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*s3bucketAnonymousAccessArgs)(nil)).Elem()
}

type S3BucketAnonymousAccessInput interface {
	pulumi.Input

	ToS3BucketAnonymousAccessOutput() S3BucketAnonymousAccessOutput
	ToS3BucketAnonymousAccessOutputWithContext(ctx context.Context) S3BucketAnonymousAccessOutput
}

func (*S3BucketAnonymousAccess) ElementType() reflect.Type {
	return reflect.TypeOf((**S3BucketAnonymousAccess)(nil)).Elem()
}

func (i *S3BucketAnonymousAccess) ToS3BucketAnonymousAccessOutput() S3BucketAnonymousAccessOutput {
	return i.ToS3BucketAnonymousAccessOutputWithContext(context.Background())
}

func (i *S3BucketAnonymousAccess) ToS3BucketAnonymousAccessOutputWithContext(ctx context.Context) S3BucketAnonymousAccessOutput {
	return pulumi.ToOutputWithContext(ctx, i).(S3BucketAnonymousAccessOutput)
}

type S3BucketAnonymousAccessOutput struct{ *pulumi.OutputState }

func (S3BucketAnonymousAccessOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**S3BucketAnonymousAccess)(nil)).Elem()
}

func (o S3BucketAnonymousAccessOutput) ToS3BucketAnonymousAccessOutput() S3BucketAnonymousAccessOutput {
	return o
}

func (o S3BucketAnonymousAccessOutput) ToS3BucketAnonymousAccessOutputWithContext(ctx context.Context) S3BucketAnonymousAccessOutput {
	return o
}

// Canned access type for anonymous access
func (o S3BucketAnonymousAccessOutput) AccessType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *S3BucketAnonymousAccess) pulumi.StringPtrOutput { return v.AccessType }).(pulumi.StringPtrOutput)
}

// Name of the bucket
func (o S3BucketAnonymousAccessOutput) Bucket() pulumi.StringOutput {
	return o.ApplyT(func(v *S3BucketAnonymousAccess) pulumi.StringOutput { return v.Bucket }).(pulumi.StringOutput)
}

// Custom policy JSON string for anonymous access. For canned policies (public, public-read, public-read-write, public-write), use the<span pulumi-lang-nodejs=" accessType " pulumi-lang-dotnet=" AccessType " pulumi-lang-go=" accessType " pulumi-lang-python=" access_type " pulumi-lang-yaml=" accessType " pulumi-lang-java=" accessType " pulumi-lang-hcl=" access_type "> accessType </span>field instead.
func (o S3BucketAnonymousAccessOutput) Policy() pulumi.StringOutput {
	return o.ApplyT(func(v *S3BucketAnonymousAccess) pulumi.StringOutput { return v.Policy }).(pulumi.StringOutput)
}

func (o S3BucketAnonymousAccessOutput) S3BucketAnonymousAccessId() pulumi.StringOutput {
	return o.ApplyT(func(v *S3BucketAnonymousAccess) pulumi.StringOutput { return v.S3BucketAnonymousAccessId }).(pulumi.StringOutput)
}

func (o S3BucketAnonymousAccessOutput) Timeouts() S3BucketAnonymousAccessTimeoutsPtrOutput {
	return o.ApplyT(func(v *S3BucketAnonymousAccess) S3BucketAnonymousAccessTimeoutsPtrOutput { return v.Timeouts }).(S3BucketAnonymousAccessTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*S3BucketAnonymousAccessInput)(nil)).Elem(), &S3BucketAnonymousAccess{})
	pulumi.RegisterOutputType(S3BucketAnonymousAccessOutput{})
}
