// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type S3BucketRetention struct {
	pulumi.CustomResourceState

	// Name of the bucket to configure object locking. The bucket must be created with object locking enabled.
	Bucket pulumi.StringOutput `pulumi:"bucket"`
	// Retention mode for the bucket. Valid values are:
	//                 - GOVERNANCE: Prevents object modification by non-privileged users. Users with s3:BypassGovernanceRetention permission can modify objects.
	//                 - COMPLIANCE: Prevents any object modification by all users, including the root user, until retention period expires.
	Mode                pulumi.StringOutput `pulumi:"mode"`
	S3BucketRetentionId pulumi.StringOutput `pulumi:"s3BucketRetentionId"`
	// Time unit for the validity period. Valid values are DAYS or YEARS.
	Unit pulumi.StringOutput `pulumi:"unit"`
	// Duration for which objects should be retained under WORM lock, in the specified unit. Must be a positive integer.
	ValidityPeriod pulumi.Float64Output `pulumi:"validityPeriod"`
}

// NewS3BucketRetention registers a new resource with the given unique name, arguments, and options.
func NewS3BucketRetention(ctx *pulumi.Context,
	name string, args *S3BucketRetentionArgs, opts ...pulumi.ResourceOption) (*S3BucketRetention, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Bucket == nil {
		return nil, errors.New("invalid value for required argument 'Bucket'")
	}
	if args.Mode == nil {
		return nil, errors.New("invalid value for required argument 'Mode'")
	}
	if args.Unit == nil {
		return nil, errors.New("invalid value for required argument 'Unit'")
	}
	if args.ValidityPeriod == nil {
		return nil, errors.New("invalid value for required argument 'ValidityPeriod'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource S3BucketRetention
	err = ctx.RegisterPackageResource("minio:index/s3BucketRetention:S3BucketRetention", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetS3BucketRetention gets an existing S3BucketRetention resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetS3BucketRetention(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *S3BucketRetentionState, opts ...pulumi.ResourceOption) (*S3BucketRetention, error) {
	var resource S3BucketRetention
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/s3BucketRetention:S3BucketRetention", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering S3BucketRetention resources.
type s3bucketRetentionState struct {
	// Name of the bucket to configure object locking. The bucket must be created with object locking enabled.
	Bucket *string `pulumi:"bucket"`
	// Retention mode for the bucket. Valid values are:
	//                 - GOVERNANCE: Prevents object modification by non-privileged users. Users with s3:BypassGovernanceRetention permission can modify objects.
	//                 - COMPLIANCE: Prevents any object modification by all users, including the root user, until retention period expires.
	Mode                *string `pulumi:"mode"`
	S3BucketRetentionId *string `pulumi:"s3BucketRetentionId"`
	// Time unit for the validity period. Valid values are DAYS or YEARS.
	Unit *string `pulumi:"unit"`
	// Duration for which objects should be retained under WORM lock, in the specified unit. Must be a positive integer.
	ValidityPeriod *float64 `pulumi:"validityPeriod"`
}

type S3BucketRetentionState struct {
	// Name of the bucket to configure object locking. The bucket must be created with object locking enabled.
	Bucket pulumi.StringPtrInput
	// Retention mode for the bucket. Valid values are:
	//                 - GOVERNANCE: Prevents object modification by non-privileged users. Users with s3:BypassGovernanceRetention permission can modify objects.
	//                 - COMPLIANCE: Prevents any object modification by all users, including the root user, until retention period expires.
	Mode                pulumi.StringPtrInput
	S3BucketRetentionId pulumi.StringPtrInput
	// Time unit for the validity period. Valid values are DAYS or YEARS.
	Unit pulumi.StringPtrInput
	// Duration for which objects should be retained under WORM lock, in the specified unit. Must be a positive integer.
	ValidityPeriod pulumi.Float64PtrInput
}

func (S3BucketRetentionState) ElementType() reflect.Type {
	return reflect.TypeOf((*s3bucketRetentionState)(nil)).Elem()
}

type s3bucketRetentionArgs struct {
	// Name of the bucket to configure object locking. The bucket must be created with object locking enabled.
	Bucket string `pulumi:"bucket"`
	// Retention mode for the bucket. Valid values are:
	//                 - GOVERNANCE: Prevents object modification by non-privileged users. Users with s3:BypassGovernanceRetention permission can modify objects.
	//                 - COMPLIANCE: Prevents any object modification by all users, including the root user, until retention period expires.
	Mode                string  `pulumi:"mode"`
	S3BucketRetentionId *string `pulumi:"s3BucketRetentionId"`
	// Time unit for the validity period. Valid values are DAYS or YEARS.
	Unit string `pulumi:"unit"`
	// Duration for which objects should be retained under WORM lock, in the specified unit. Must be a positive integer.
	ValidityPeriod float64 `pulumi:"validityPeriod"`
}

// The set of arguments for constructing a S3BucketRetention resource.
type S3BucketRetentionArgs struct {
	// Name of the bucket to configure object locking. The bucket must be created with object locking enabled.
	Bucket pulumi.StringInput
	// Retention mode for the bucket. Valid values are:
	//                 - GOVERNANCE: Prevents object modification by non-privileged users. Users with s3:BypassGovernanceRetention permission can modify objects.
	//                 - COMPLIANCE: Prevents any object modification by all users, including the root user, until retention period expires.
	Mode                pulumi.StringInput
	S3BucketRetentionId pulumi.StringPtrInput
	// Time unit for the validity period. Valid values are DAYS or YEARS.
	Unit pulumi.StringInput
	// Duration for which objects should be retained under WORM lock, in the specified unit. Must be a positive integer.
	ValidityPeriod pulumi.Float64Input
}

func (S3BucketRetentionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*s3bucketRetentionArgs)(nil)).Elem()
}

type S3BucketRetentionInput interface {
	pulumi.Input

	ToS3BucketRetentionOutput() S3BucketRetentionOutput
	ToS3BucketRetentionOutputWithContext(ctx context.Context) S3BucketRetentionOutput
}

func (*S3BucketRetention) ElementType() reflect.Type {
	return reflect.TypeOf((**S3BucketRetention)(nil)).Elem()
}

func (i *S3BucketRetention) ToS3BucketRetentionOutput() S3BucketRetentionOutput {
	return i.ToS3BucketRetentionOutputWithContext(context.Background())
}

func (i *S3BucketRetention) ToS3BucketRetentionOutputWithContext(ctx context.Context) S3BucketRetentionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(S3BucketRetentionOutput)
}

type S3BucketRetentionOutput struct{ *pulumi.OutputState }

func (S3BucketRetentionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**S3BucketRetention)(nil)).Elem()
}

func (o S3BucketRetentionOutput) ToS3BucketRetentionOutput() S3BucketRetentionOutput {
	return o
}

func (o S3BucketRetentionOutput) ToS3BucketRetentionOutputWithContext(ctx context.Context) S3BucketRetentionOutput {
	return o
}

// Name of the bucket to configure object locking. The bucket must be created with object locking enabled.
func (o S3BucketRetentionOutput) Bucket() pulumi.StringOutput {
	return o.ApplyT(func(v *S3BucketRetention) pulumi.StringOutput { return v.Bucket }).(pulumi.StringOutput)
}

// Retention mode for the bucket. Valid values are:
//   - GOVERNANCE: Prevents object modification by non-privileged users. Users with s3:BypassGovernanceRetention permission can modify objects.
//   - COMPLIANCE: Prevents any object modification by all users, including the root user, until retention period expires.
func (o S3BucketRetentionOutput) Mode() pulumi.StringOutput {
	return o.ApplyT(func(v *S3BucketRetention) pulumi.StringOutput { return v.Mode }).(pulumi.StringOutput)
}

func (o S3BucketRetentionOutput) S3BucketRetentionId() pulumi.StringOutput {
	return o.ApplyT(func(v *S3BucketRetention) pulumi.StringOutput { return v.S3BucketRetentionId }).(pulumi.StringOutput)
}

// Time unit for the validity period. Valid values are DAYS or YEARS.
func (o S3BucketRetentionOutput) Unit() pulumi.StringOutput {
	return o.ApplyT(func(v *S3BucketRetention) pulumi.StringOutput { return v.Unit }).(pulumi.StringOutput)
}

// Duration for which objects should be retained under WORM lock, in the specified unit. Must be a positive integer.
func (o S3BucketRetentionOutput) ValidityPeriod() pulumi.Float64Output {
	return o.ApplyT(func(v *S3BucketRetention) pulumi.Float64Output { return v.ValidityPeriod }).(pulumi.Float64Output)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*S3BucketRetentionInput)(nil)).Elem(), &S3BucketRetention{})
	pulumi.RegisterOutputType(S3BucketRetentionOutput{})
}
