// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type S3BucketVersioning struct {
	pulumi.CustomResourceState

	// Name of the bucket
	Bucket               pulumi.StringOutput                 `pulumi:"bucket"`
	S3BucketVersioningId pulumi.StringOutput                 `pulumi:"s3BucketVersioningId"`
	Timeouts             S3BucketVersioningTimeoutsPtrOutput `pulumi:"timeouts"`
	// Versioning configuration for the bucket.
	VersioningConfiguration S3BucketVersioningVersioningConfigurationOutput `pulumi:"versioningConfiguration"`
}

// NewS3BucketVersioning registers a new resource with the given unique name, arguments, and options.
func NewS3BucketVersioning(ctx *pulumi.Context,
	name string, args *S3BucketVersioningArgs, opts ...pulumi.ResourceOption) (*S3BucketVersioning, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Bucket == nil {
		return nil, errors.New("invalid value for required argument 'Bucket'")
	}
	if args.VersioningConfiguration == nil {
		return nil, errors.New("invalid value for required argument 'VersioningConfiguration'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource S3BucketVersioning
	err = ctx.RegisterPackageResource("minio:index/s3BucketVersioning:S3BucketVersioning", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetS3BucketVersioning gets an existing S3BucketVersioning resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetS3BucketVersioning(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *S3BucketVersioningState, opts ...pulumi.ResourceOption) (*S3BucketVersioning, error) {
	var resource S3BucketVersioning
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/s3BucketVersioning:S3BucketVersioning", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering S3BucketVersioning resources.
type s3bucketVersioningState struct {
	// Name of the bucket
	Bucket               *string                     `pulumi:"bucket"`
	S3BucketVersioningId *string                     `pulumi:"s3BucketVersioningId"`
	Timeouts             *S3BucketVersioningTimeouts `pulumi:"timeouts"`
	// Versioning configuration for the bucket.
	VersioningConfiguration *S3BucketVersioningVersioningConfiguration `pulumi:"versioningConfiguration"`
}

type S3BucketVersioningState struct {
	// Name of the bucket
	Bucket               pulumi.StringPtrInput
	S3BucketVersioningId pulumi.StringPtrInput
	Timeouts             S3BucketVersioningTimeoutsPtrInput
	// Versioning configuration for the bucket.
	VersioningConfiguration S3BucketVersioningVersioningConfigurationPtrInput
}

func (S3BucketVersioningState) ElementType() reflect.Type {
	return reflect.TypeOf((*s3bucketVersioningState)(nil)).Elem()
}

type s3bucketVersioningArgs struct {
	// Name of the bucket
	Bucket               string                      `pulumi:"bucket"`
	S3BucketVersioningId *string                     `pulumi:"s3BucketVersioningId"`
	Timeouts             *S3BucketVersioningTimeouts `pulumi:"timeouts"`
	// Versioning configuration for the bucket.
	VersioningConfiguration S3BucketVersioningVersioningConfiguration `pulumi:"versioningConfiguration"`
}

// The set of arguments for constructing a S3BucketVersioning resource.
type S3BucketVersioningArgs struct {
	// Name of the bucket
	Bucket               pulumi.StringInput
	S3BucketVersioningId pulumi.StringPtrInput
	Timeouts             S3BucketVersioningTimeoutsPtrInput
	// Versioning configuration for the bucket.
	VersioningConfiguration S3BucketVersioningVersioningConfigurationInput
}

func (S3BucketVersioningArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*s3bucketVersioningArgs)(nil)).Elem()
}

type S3BucketVersioningInput interface {
	pulumi.Input

	ToS3BucketVersioningOutput() S3BucketVersioningOutput
	ToS3BucketVersioningOutputWithContext(ctx context.Context) S3BucketVersioningOutput
}

func (*S3BucketVersioning) ElementType() reflect.Type {
	return reflect.TypeOf((**S3BucketVersioning)(nil)).Elem()
}

func (i *S3BucketVersioning) ToS3BucketVersioningOutput() S3BucketVersioningOutput {
	return i.ToS3BucketVersioningOutputWithContext(context.Background())
}

func (i *S3BucketVersioning) ToS3BucketVersioningOutputWithContext(ctx context.Context) S3BucketVersioningOutput {
	return pulumi.ToOutputWithContext(ctx, i).(S3BucketVersioningOutput)
}

type S3BucketVersioningOutput struct{ *pulumi.OutputState }

func (S3BucketVersioningOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**S3BucketVersioning)(nil)).Elem()
}

func (o S3BucketVersioningOutput) ToS3BucketVersioningOutput() S3BucketVersioningOutput {
	return o
}

func (o S3BucketVersioningOutput) ToS3BucketVersioningOutputWithContext(ctx context.Context) S3BucketVersioningOutput {
	return o
}

// Name of the bucket
func (o S3BucketVersioningOutput) Bucket() pulumi.StringOutput {
	return o.ApplyT(func(v *S3BucketVersioning) pulumi.StringOutput { return v.Bucket }).(pulumi.StringOutput)
}

func (o S3BucketVersioningOutput) S3BucketVersioningId() pulumi.StringOutput {
	return o.ApplyT(func(v *S3BucketVersioning) pulumi.StringOutput { return v.S3BucketVersioningId }).(pulumi.StringOutput)
}

func (o S3BucketVersioningOutput) Timeouts() S3BucketVersioningTimeoutsPtrOutput {
	return o.ApplyT(func(v *S3BucketVersioning) S3BucketVersioningTimeoutsPtrOutput { return v.Timeouts }).(S3BucketVersioningTimeoutsPtrOutput)
}

// Versioning configuration for the bucket.
func (o S3BucketVersioningOutput) VersioningConfiguration() S3BucketVersioningVersioningConfigurationOutput {
	return o.ApplyT(func(v *S3BucketVersioning) S3BucketVersioningVersioningConfigurationOutput {
		return v.VersioningConfiguration
	}).(S3BucketVersioningVersioningConfigurationOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*S3BucketVersioningInput)(nil)).Elem(), &S3BucketVersioning{})
	pulumi.RegisterOutputType(S3BucketVersioningOutput{})
}
