// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type S3BucketObjectLockConfiguration struct {
	pulumi.CustomResourceState

	// Bucket name. Must have object locking enabled at creation time.
	Bucket pulumi.StringOutput `pulumi:"bucket"`
	// Object lock status. Only valid value is 'Enabled'.
	ObjectLockEnabled pulumi.StringPtrOutput `pulumi:"objectLockEnabled"`
	// Retention rule configuration
	Rule                              S3BucketObjectLockConfigurationRulePtrOutput `pulumi:"rule"`
	S3BucketObjectLockConfigurationId pulumi.StringOutput                          `pulumi:"s3BucketObjectLockConfigurationId"`
}

// NewS3BucketObjectLockConfiguration registers a new resource with the given unique name, arguments, and options.
func NewS3BucketObjectLockConfiguration(ctx *pulumi.Context,
	name string, args *S3BucketObjectLockConfigurationArgs, opts ...pulumi.ResourceOption) (*S3BucketObjectLockConfiguration, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Bucket == nil {
		return nil, errors.New("invalid value for required argument 'Bucket'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource S3BucketObjectLockConfiguration
	err = ctx.RegisterPackageResource("minio:index/s3BucketObjectLockConfiguration:S3BucketObjectLockConfiguration", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetS3BucketObjectLockConfiguration gets an existing S3BucketObjectLockConfiguration resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetS3BucketObjectLockConfiguration(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *S3BucketObjectLockConfigurationState, opts ...pulumi.ResourceOption) (*S3BucketObjectLockConfiguration, error) {
	var resource S3BucketObjectLockConfiguration
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/s3BucketObjectLockConfiguration:S3BucketObjectLockConfiguration", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering S3BucketObjectLockConfiguration resources.
type s3bucketObjectLockConfigurationState struct {
	// Bucket name. Must have object locking enabled at creation time.
	Bucket *string `pulumi:"bucket"`
	// Object lock status. Only valid value is 'Enabled'.
	ObjectLockEnabled *string `pulumi:"objectLockEnabled"`
	// Retention rule configuration
	Rule                              *S3BucketObjectLockConfigurationRule `pulumi:"rule"`
	S3BucketObjectLockConfigurationId *string                              `pulumi:"s3BucketObjectLockConfigurationId"`
}

type S3BucketObjectLockConfigurationState struct {
	// Bucket name. Must have object locking enabled at creation time.
	Bucket pulumi.StringPtrInput
	// Object lock status. Only valid value is 'Enabled'.
	ObjectLockEnabled pulumi.StringPtrInput
	// Retention rule configuration
	Rule                              S3BucketObjectLockConfigurationRulePtrInput
	S3BucketObjectLockConfigurationId pulumi.StringPtrInput
}

func (S3BucketObjectLockConfigurationState) ElementType() reflect.Type {
	return reflect.TypeOf((*s3bucketObjectLockConfigurationState)(nil)).Elem()
}

type s3bucketObjectLockConfigurationArgs struct {
	// Bucket name. Must have object locking enabled at creation time.
	Bucket string `pulumi:"bucket"`
	// Object lock status. Only valid value is 'Enabled'.
	ObjectLockEnabled *string `pulumi:"objectLockEnabled"`
	// Retention rule configuration
	Rule                              *S3BucketObjectLockConfigurationRule `pulumi:"rule"`
	S3BucketObjectLockConfigurationId *string                              `pulumi:"s3BucketObjectLockConfigurationId"`
}

// The set of arguments for constructing a S3BucketObjectLockConfiguration resource.
type S3BucketObjectLockConfigurationArgs struct {
	// Bucket name. Must have object locking enabled at creation time.
	Bucket pulumi.StringInput
	// Object lock status. Only valid value is 'Enabled'.
	ObjectLockEnabled pulumi.StringPtrInput
	// Retention rule configuration
	Rule                              S3BucketObjectLockConfigurationRulePtrInput
	S3BucketObjectLockConfigurationId pulumi.StringPtrInput
}

func (S3BucketObjectLockConfigurationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*s3bucketObjectLockConfigurationArgs)(nil)).Elem()
}

type S3BucketObjectLockConfigurationInput interface {
	pulumi.Input

	ToS3BucketObjectLockConfigurationOutput() S3BucketObjectLockConfigurationOutput
	ToS3BucketObjectLockConfigurationOutputWithContext(ctx context.Context) S3BucketObjectLockConfigurationOutput
}

func (*S3BucketObjectLockConfiguration) ElementType() reflect.Type {
	return reflect.TypeOf((**S3BucketObjectLockConfiguration)(nil)).Elem()
}

func (i *S3BucketObjectLockConfiguration) ToS3BucketObjectLockConfigurationOutput() S3BucketObjectLockConfigurationOutput {
	return i.ToS3BucketObjectLockConfigurationOutputWithContext(context.Background())
}

func (i *S3BucketObjectLockConfiguration) ToS3BucketObjectLockConfigurationOutputWithContext(ctx context.Context) S3BucketObjectLockConfigurationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(S3BucketObjectLockConfigurationOutput)
}

type S3BucketObjectLockConfigurationOutput struct{ *pulumi.OutputState }

func (S3BucketObjectLockConfigurationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**S3BucketObjectLockConfiguration)(nil)).Elem()
}

func (o S3BucketObjectLockConfigurationOutput) ToS3BucketObjectLockConfigurationOutput() S3BucketObjectLockConfigurationOutput {
	return o
}

func (o S3BucketObjectLockConfigurationOutput) ToS3BucketObjectLockConfigurationOutputWithContext(ctx context.Context) S3BucketObjectLockConfigurationOutput {
	return o
}

// Bucket name. Must have object locking enabled at creation time.
func (o S3BucketObjectLockConfigurationOutput) Bucket() pulumi.StringOutput {
	return o.ApplyT(func(v *S3BucketObjectLockConfiguration) pulumi.StringOutput { return v.Bucket }).(pulumi.StringOutput)
}

// Object lock status. Only valid value is 'Enabled'.
func (o S3BucketObjectLockConfigurationOutput) ObjectLockEnabled() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *S3BucketObjectLockConfiguration) pulumi.StringPtrOutput { return v.ObjectLockEnabled }).(pulumi.StringPtrOutput)
}

// Retention rule configuration
func (o S3BucketObjectLockConfigurationOutput) Rule() S3BucketObjectLockConfigurationRulePtrOutput {
	return o.ApplyT(func(v *S3BucketObjectLockConfiguration) S3BucketObjectLockConfigurationRulePtrOutput { return v.Rule }).(S3BucketObjectLockConfigurationRulePtrOutput)
}

func (o S3BucketObjectLockConfigurationOutput) S3BucketObjectLockConfigurationId() pulumi.StringOutput {
	return o.ApplyT(func(v *S3BucketObjectLockConfiguration) pulumi.StringOutput {
		return v.S3BucketObjectLockConfigurationId
	}).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*S3BucketObjectLockConfigurationInput)(nil)).Elem(), &S3BucketObjectLockConfiguration{})
	pulumi.RegisterOutputType(S3BucketObjectLockConfigurationOutput{})
}
