// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type S3IncompleteUploadCleanup struct {
	pulumi.CustomResourceState

	// Name of the bucket to clean up incomplete uploads from.
	Bucket pulumi.StringOutput `pulumi:"bucket"`
	// Timestamp of the last cleanup operation.
	LastCleanup pulumi.StringOutput `pulumi:"lastCleanup"`
	// Object prefix to filter incomplete uploads (default: all objects).
	Prefix                      pulumi.StringPtrOutput `pulumi:"prefix"`
	S3IncompleteUploadCleanupId pulumi.StringOutput    `pulumi:"s3IncompleteUploadCleanupId"`
	// Map of arbitrary values. When any value changes, Terraform will re-run the cleanup. Use this to schedule repeated cleanups, e.g. triggers = { run = timestamp() }.
	Triggers pulumi.StringMapOutput `pulumi:"triggers"`
}

// NewS3IncompleteUploadCleanup registers a new resource with the given unique name, arguments, and options.
func NewS3IncompleteUploadCleanup(ctx *pulumi.Context,
	name string, args *S3IncompleteUploadCleanupArgs, opts ...pulumi.ResourceOption) (*S3IncompleteUploadCleanup, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Bucket == nil {
		return nil, errors.New("invalid value for required argument 'Bucket'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource S3IncompleteUploadCleanup
	err = ctx.RegisterPackageResource("minio:index/s3IncompleteUploadCleanup:S3IncompleteUploadCleanup", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetS3IncompleteUploadCleanup gets an existing S3IncompleteUploadCleanup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetS3IncompleteUploadCleanup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *S3IncompleteUploadCleanupState, opts ...pulumi.ResourceOption) (*S3IncompleteUploadCleanup, error) {
	var resource S3IncompleteUploadCleanup
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/s3IncompleteUploadCleanup:S3IncompleteUploadCleanup", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering S3IncompleteUploadCleanup resources.
type s3incompleteUploadCleanupState struct {
	// Name of the bucket to clean up incomplete uploads from.
	Bucket *string `pulumi:"bucket"`
	// Timestamp of the last cleanup operation.
	LastCleanup *string `pulumi:"lastCleanup"`
	// Object prefix to filter incomplete uploads (default: all objects).
	Prefix                      *string `pulumi:"prefix"`
	S3IncompleteUploadCleanupId *string `pulumi:"s3IncompleteUploadCleanupId"`
	// Map of arbitrary values. When any value changes, Terraform will re-run the cleanup. Use this to schedule repeated cleanups, e.g. triggers = { run = timestamp() }.
	Triggers map[string]string `pulumi:"triggers"`
}

type S3IncompleteUploadCleanupState struct {
	// Name of the bucket to clean up incomplete uploads from.
	Bucket pulumi.StringPtrInput
	// Timestamp of the last cleanup operation.
	LastCleanup pulumi.StringPtrInput
	// Object prefix to filter incomplete uploads (default: all objects).
	Prefix                      pulumi.StringPtrInput
	S3IncompleteUploadCleanupId pulumi.StringPtrInput
	// Map of arbitrary values. When any value changes, Terraform will re-run the cleanup. Use this to schedule repeated cleanups, e.g. triggers = { run = timestamp() }.
	Triggers pulumi.StringMapInput
}

func (S3IncompleteUploadCleanupState) ElementType() reflect.Type {
	return reflect.TypeOf((*s3incompleteUploadCleanupState)(nil)).Elem()
}

type s3incompleteUploadCleanupArgs struct {
	// Name of the bucket to clean up incomplete uploads from.
	Bucket string `pulumi:"bucket"`
	// Object prefix to filter incomplete uploads (default: all objects).
	Prefix                      *string `pulumi:"prefix"`
	S3IncompleteUploadCleanupId *string `pulumi:"s3IncompleteUploadCleanupId"`
	// Map of arbitrary values. When any value changes, Terraform will re-run the cleanup. Use this to schedule repeated cleanups, e.g. triggers = { run = timestamp() }.
	Triggers map[string]string `pulumi:"triggers"`
}

// The set of arguments for constructing a S3IncompleteUploadCleanup resource.
type S3IncompleteUploadCleanupArgs struct {
	// Name of the bucket to clean up incomplete uploads from.
	Bucket pulumi.StringInput
	// Object prefix to filter incomplete uploads (default: all objects).
	Prefix                      pulumi.StringPtrInput
	S3IncompleteUploadCleanupId pulumi.StringPtrInput
	// Map of arbitrary values. When any value changes, Terraform will re-run the cleanup. Use this to schedule repeated cleanups, e.g. triggers = { run = timestamp() }.
	Triggers pulumi.StringMapInput
}

func (S3IncompleteUploadCleanupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*s3incompleteUploadCleanupArgs)(nil)).Elem()
}

type S3IncompleteUploadCleanupInput interface {
	pulumi.Input

	ToS3IncompleteUploadCleanupOutput() S3IncompleteUploadCleanupOutput
	ToS3IncompleteUploadCleanupOutputWithContext(ctx context.Context) S3IncompleteUploadCleanupOutput
}

func (*S3IncompleteUploadCleanup) ElementType() reflect.Type {
	return reflect.TypeOf((**S3IncompleteUploadCleanup)(nil)).Elem()
}

func (i *S3IncompleteUploadCleanup) ToS3IncompleteUploadCleanupOutput() S3IncompleteUploadCleanupOutput {
	return i.ToS3IncompleteUploadCleanupOutputWithContext(context.Background())
}

func (i *S3IncompleteUploadCleanup) ToS3IncompleteUploadCleanupOutputWithContext(ctx context.Context) S3IncompleteUploadCleanupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(S3IncompleteUploadCleanupOutput)
}

type S3IncompleteUploadCleanupOutput struct{ *pulumi.OutputState }

func (S3IncompleteUploadCleanupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**S3IncompleteUploadCleanup)(nil)).Elem()
}

func (o S3IncompleteUploadCleanupOutput) ToS3IncompleteUploadCleanupOutput() S3IncompleteUploadCleanupOutput {
	return o
}

func (o S3IncompleteUploadCleanupOutput) ToS3IncompleteUploadCleanupOutputWithContext(ctx context.Context) S3IncompleteUploadCleanupOutput {
	return o
}

// Name of the bucket to clean up incomplete uploads from.
func (o S3IncompleteUploadCleanupOutput) Bucket() pulumi.StringOutput {
	return o.ApplyT(func(v *S3IncompleteUploadCleanup) pulumi.StringOutput { return v.Bucket }).(pulumi.StringOutput)
}

// Timestamp of the last cleanup operation.
func (o S3IncompleteUploadCleanupOutput) LastCleanup() pulumi.StringOutput {
	return o.ApplyT(func(v *S3IncompleteUploadCleanup) pulumi.StringOutput { return v.LastCleanup }).(pulumi.StringOutput)
}

// Object prefix to filter incomplete uploads (default: all objects).
func (o S3IncompleteUploadCleanupOutput) Prefix() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *S3IncompleteUploadCleanup) pulumi.StringPtrOutput { return v.Prefix }).(pulumi.StringPtrOutput)
}

func (o S3IncompleteUploadCleanupOutput) S3IncompleteUploadCleanupId() pulumi.StringOutput {
	return o.ApplyT(func(v *S3IncompleteUploadCleanup) pulumi.StringOutput { return v.S3IncompleteUploadCleanupId }).(pulumi.StringOutput)
}

// Map of arbitrary values. When any value changes, Terraform will re-run the cleanup. Use this to schedule repeated cleanups, e.g. triggers = { run = timestamp() }.
func (o S3IncompleteUploadCleanupOutput) Triggers() pulumi.StringMapOutput {
	return o.ApplyT(func(v *S3IncompleteUploadCleanup) pulumi.StringMapOutput { return v.Triggers }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*S3IncompleteUploadCleanupInput)(nil)).Elem(), &S3IncompleteUploadCleanup{})
	pulumi.RegisterOutputType(S3IncompleteUploadCleanupOutput{})
}
