// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ServiceAction struct {
	pulumi.CustomResourceState

	// The service action to perform. One of: freeze, unfreeze, restart, stop.
	Action pulumi.StringOutput `pulumi:"action"`
	// RFC3339 timestamp of when the action was executed.
	ExecutedAt pulumi.StringOutput `pulumi:"executedAt"`
	// Short text summary of what was done.
	Result          pulumi.StringOutput            `pulumi:"result"`
	ServiceActionId pulumi.StringOutput            `pulumi:"serviceActionId"`
	Timeouts        ServiceActionTimeoutsPtrOutput `pulumi:"timeouts"`
	// Arbitrary map of strings to force re-execution when changed (like the<span pulumi-lang-nodejs=" terraformData " pulumi-lang-dotnet=" TerraformData " pulumi-lang-go=" terraformData " pulumi-lang-python=" terraform_data " pulumi-lang-yaml=" terraformData " pulumi-lang-java=" terraformData " pulumi-lang-hcl=" terraform_data "> terraformData </span>pattern).
	Triggers pulumi.StringMapOutput `pulumi:"triggers"`
}

// NewServiceAction registers a new resource with the given unique name, arguments, and options.
func NewServiceAction(ctx *pulumi.Context,
	name string, args *ServiceActionArgs, opts ...pulumi.ResourceOption) (*ServiceAction, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Action == nil {
		return nil, errors.New("invalid value for required argument 'Action'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource ServiceAction
	err = ctx.RegisterPackageResource("minio:index/serviceAction:ServiceAction", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetServiceAction gets an existing ServiceAction resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetServiceAction(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ServiceActionState, opts ...pulumi.ResourceOption) (*ServiceAction, error) {
	var resource ServiceAction
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/serviceAction:ServiceAction", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ServiceAction resources.
type serviceActionState struct {
	// The service action to perform. One of: freeze, unfreeze, restart, stop.
	Action *string `pulumi:"action"`
	// RFC3339 timestamp of when the action was executed.
	ExecutedAt *string `pulumi:"executedAt"`
	// Short text summary of what was done.
	Result          *string                `pulumi:"result"`
	ServiceActionId *string                `pulumi:"serviceActionId"`
	Timeouts        *ServiceActionTimeouts `pulumi:"timeouts"`
	// Arbitrary map of strings to force re-execution when changed (like the<span pulumi-lang-nodejs=" terraformData " pulumi-lang-dotnet=" TerraformData " pulumi-lang-go=" terraformData " pulumi-lang-python=" terraform_data " pulumi-lang-yaml=" terraformData " pulumi-lang-java=" terraformData " pulumi-lang-hcl=" terraform_data "> terraformData </span>pattern).
	Triggers map[string]string `pulumi:"triggers"`
}

type ServiceActionState struct {
	// The service action to perform. One of: freeze, unfreeze, restart, stop.
	Action pulumi.StringPtrInput
	// RFC3339 timestamp of when the action was executed.
	ExecutedAt pulumi.StringPtrInput
	// Short text summary of what was done.
	Result          pulumi.StringPtrInput
	ServiceActionId pulumi.StringPtrInput
	Timeouts        ServiceActionTimeoutsPtrInput
	// Arbitrary map of strings to force re-execution when changed (like the<span pulumi-lang-nodejs=" terraformData " pulumi-lang-dotnet=" TerraformData " pulumi-lang-go=" terraformData " pulumi-lang-python=" terraform_data " pulumi-lang-yaml=" terraformData " pulumi-lang-java=" terraformData " pulumi-lang-hcl=" terraform_data "> terraformData </span>pattern).
	Triggers pulumi.StringMapInput
}

func (ServiceActionState) ElementType() reflect.Type {
	return reflect.TypeOf((*serviceActionState)(nil)).Elem()
}

type serviceActionArgs struct {
	// The service action to perform. One of: freeze, unfreeze, restart, stop.
	Action          string                 `pulumi:"action"`
	ServiceActionId *string                `pulumi:"serviceActionId"`
	Timeouts        *ServiceActionTimeouts `pulumi:"timeouts"`
	// Arbitrary map of strings to force re-execution when changed (like the<span pulumi-lang-nodejs=" terraformData " pulumi-lang-dotnet=" TerraformData " pulumi-lang-go=" terraformData " pulumi-lang-python=" terraform_data " pulumi-lang-yaml=" terraformData " pulumi-lang-java=" terraformData " pulumi-lang-hcl=" terraform_data "> terraformData </span>pattern).
	Triggers map[string]string `pulumi:"triggers"`
}

// The set of arguments for constructing a ServiceAction resource.
type ServiceActionArgs struct {
	// The service action to perform. One of: freeze, unfreeze, restart, stop.
	Action          pulumi.StringInput
	ServiceActionId pulumi.StringPtrInput
	Timeouts        ServiceActionTimeoutsPtrInput
	// Arbitrary map of strings to force re-execution when changed (like the<span pulumi-lang-nodejs=" terraformData " pulumi-lang-dotnet=" TerraformData " pulumi-lang-go=" terraformData " pulumi-lang-python=" terraform_data " pulumi-lang-yaml=" terraformData " pulumi-lang-java=" terraformData " pulumi-lang-hcl=" terraform_data "> terraformData </span>pattern).
	Triggers pulumi.StringMapInput
}

func (ServiceActionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*serviceActionArgs)(nil)).Elem()
}

type ServiceActionInput interface {
	pulumi.Input

	ToServiceActionOutput() ServiceActionOutput
	ToServiceActionOutputWithContext(ctx context.Context) ServiceActionOutput
}

func (*ServiceAction) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceAction)(nil)).Elem()
}

func (i *ServiceAction) ToServiceActionOutput() ServiceActionOutput {
	return i.ToServiceActionOutputWithContext(context.Background())
}

func (i *ServiceAction) ToServiceActionOutputWithContext(ctx context.Context) ServiceActionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceActionOutput)
}

type ServiceActionOutput struct{ *pulumi.OutputState }

func (ServiceActionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceAction)(nil)).Elem()
}

func (o ServiceActionOutput) ToServiceActionOutput() ServiceActionOutput {
	return o
}

func (o ServiceActionOutput) ToServiceActionOutputWithContext(ctx context.Context) ServiceActionOutput {
	return o
}

// The service action to perform. One of: freeze, unfreeze, restart, stop.
func (o ServiceActionOutput) Action() pulumi.StringOutput {
	return o.ApplyT(func(v *ServiceAction) pulumi.StringOutput { return v.Action }).(pulumi.StringOutput)
}

// RFC3339 timestamp of when the action was executed.
func (o ServiceActionOutput) ExecutedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ServiceAction) pulumi.StringOutput { return v.ExecutedAt }).(pulumi.StringOutput)
}

// Short text summary of what was done.
func (o ServiceActionOutput) Result() pulumi.StringOutput {
	return o.ApplyT(func(v *ServiceAction) pulumi.StringOutput { return v.Result }).(pulumi.StringOutput)
}

func (o ServiceActionOutput) ServiceActionId() pulumi.StringOutput {
	return o.ApplyT(func(v *ServiceAction) pulumi.StringOutput { return v.ServiceActionId }).(pulumi.StringOutput)
}

func (o ServiceActionOutput) Timeouts() ServiceActionTimeoutsPtrOutput {
	return o.ApplyT(func(v *ServiceAction) ServiceActionTimeoutsPtrOutput { return v.Timeouts }).(ServiceActionTimeoutsPtrOutput)
}

// Arbitrary map of strings to force re-execution when changed (like the<span pulumi-lang-nodejs=" terraformData " pulumi-lang-dotnet=" TerraformData " pulumi-lang-go=" terraformData " pulumi-lang-python=" terraform_data " pulumi-lang-yaml=" terraformData " pulumi-lang-java=" terraformData " pulumi-lang-hcl=" terraform_data "> terraformData </span>pattern).
func (o ServiceActionOutput) Triggers() pulumi.StringMapOutput {
	return o.ApplyT(func(v *ServiceAction) pulumi.StringMapOutput { return v.Triggers }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceActionInput)(nil)).Elem(), &ServiceAction{})
	pulumi.RegisterOutputType(ServiceActionOutput{})
}
