// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/minio/v3/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ServerConfigRegion struct {
	pulumi.CustomResourceState

	// Region description.
	Comment pulumi.StringOutput `pulumi:"comment"`
	// Region or site name (e.g., "us-east-1", "dc1-rack2").
	Name pulumi.StringOutput `pulumi:"name"`
	// Whether a MinIO server restart is required.
	RestartRequired      pulumi.BoolOutput   `pulumi:"restartRequired"`
	ServerConfigRegionId pulumi.StringOutput `pulumi:"serverConfigRegionId"`
}

// NewServerConfigRegion registers a new resource with the given unique name, arguments, and options.
func NewServerConfigRegion(ctx *pulumi.Context,
	name string, args *ServerConfigRegionArgs, opts ...pulumi.ResourceOption) (*ServerConfigRegion, error) {
	if args == nil {
		args = &ServerConfigRegionArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource ServerConfigRegion
	err = ctx.RegisterPackageResource("minio:index/serverConfigRegion:ServerConfigRegion", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetServerConfigRegion gets an existing ServerConfigRegion resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetServerConfigRegion(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ServerConfigRegionState, opts ...pulumi.ResourceOption) (*ServerConfigRegion, error) {
	var resource ServerConfigRegion
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("minio:index/serverConfigRegion:ServerConfigRegion", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ServerConfigRegion resources.
type serverConfigRegionState struct {
	// Region description.
	Comment *string `pulumi:"comment"`
	// Region or site name (e.g., "us-east-1", "dc1-rack2").
	Name *string `pulumi:"name"`
	// Whether a MinIO server restart is required.
	RestartRequired      *bool   `pulumi:"restartRequired"`
	ServerConfigRegionId *string `pulumi:"serverConfigRegionId"`
}

type ServerConfigRegionState struct {
	// Region description.
	Comment pulumi.StringPtrInput
	// Region or site name (e.g., "us-east-1", "dc1-rack2").
	Name pulumi.StringPtrInput
	// Whether a MinIO server restart is required.
	RestartRequired      pulumi.BoolPtrInput
	ServerConfigRegionId pulumi.StringPtrInput
}

func (ServerConfigRegionState) ElementType() reflect.Type {
	return reflect.TypeOf((*serverConfigRegionState)(nil)).Elem()
}

type serverConfigRegionArgs struct {
	// Region description.
	Comment *string `pulumi:"comment"`
	// Region or site name (e.g., "us-east-1", "dc1-rack2").
	Name                 *string `pulumi:"name"`
	ServerConfigRegionId *string `pulumi:"serverConfigRegionId"`
}

// The set of arguments for constructing a ServerConfigRegion resource.
type ServerConfigRegionArgs struct {
	// Region description.
	Comment pulumi.StringPtrInput
	// Region or site name (e.g., "us-east-1", "dc1-rack2").
	Name                 pulumi.StringPtrInput
	ServerConfigRegionId pulumi.StringPtrInput
}

func (ServerConfigRegionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*serverConfigRegionArgs)(nil)).Elem()
}

type ServerConfigRegionInput interface {
	pulumi.Input

	ToServerConfigRegionOutput() ServerConfigRegionOutput
	ToServerConfigRegionOutputWithContext(ctx context.Context) ServerConfigRegionOutput
}

func (*ServerConfigRegion) ElementType() reflect.Type {
	return reflect.TypeOf((**ServerConfigRegion)(nil)).Elem()
}

func (i *ServerConfigRegion) ToServerConfigRegionOutput() ServerConfigRegionOutput {
	return i.ToServerConfigRegionOutputWithContext(context.Background())
}

func (i *ServerConfigRegion) ToServerConfigRegionOutputWithContext(ctx context.Context) ServerConfigRegionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerConfigRegionOutput)
}

type ServerConfigRegionOutput struct{ *pulumi.OutputState }

func (ServerConfigRegionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServerConfigRegion)(nil)).Elem()
}

func (o ServerConfigRegionOutput) ToServerConfigRegionOutput() ServerConfigRegionOutput {
	return o
}

func (o ServerConfigRegionOutput) ToServerConfigRegionOutputWithContext(ctx context.Context) ServerConfigRegionOutput {
	return o
}

// Region description.
func (o ServerConfigRegionOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerConfigRegion) pulumi.StringOutput { return v.Comment }).(pulumi.StringOutput)
}

// Region or site name (e.g., "us-east-1", "dc1-rack2").
func (o ServerConfigRegionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerConfigRegion) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Whether a MinIO server restart is required.
func (o ServerConfigRegionOutput) RestartRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v *ServerConfigRegion) pulumi.BoolOutput { return v.RestartRequired }).(pulumi.BoolOutput)
}

func (o ServerConfigRegionOutput) ServerConfigRegionId() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerConfigRegion) pulumi.StringOutput { return v.ServerConfigRegionId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServerConfigRegionInput)(nil)).Elem(), &ServerConfigRegion{})
	pulumi.RegisterOutputType(ServerConfigRegionOutput{})
}
